package jobs

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/riverqueue/river"

	"github.com/apex42group/ledgermancy/backend/internal/ai"
	"github.com/apex42group/ledgermancy/backend/internal/db/dbgen"
	"github.com/apex42group/ledgermancy/backend/internal/reporting"
)

// --------------------------------------------------------------------------
// Monthly recap auto-generation.
//
// The recap used to be generated only on demand (a Regenerate button) or,
// incidentally, as a side effect of the monthly digest warming its cache. Two
// problems followed: a household that never opened the Spending page had no
// recap at all, and the current month's in-progress recap went stale the moment
// it was written.
//
// This job fixes both, per household, on a self-scheduling sweep:
//
//   - Finalise the just-completed month. If its cached summary is missing, or
//     was written while the month was still in progress, regenerate it in the
//     past tense and overwrite. This happens exactly once per month (the first
//     sweep after rollover), independent of whether anyone has a digest enabled.
//   - Refresh the current, in-progress month at most weekly, so the "so far this
//     month…" recap keeps pace as the month fills in — but never clobbers a
//     summary a member generated by hand in the last few days.
//
// Generation is household-shared (uuid.Nil visibility), the same view the
// insight feed uses for household-wide figures. It self-gates on AI being
// enabled, so the sweep is only registered when a model is configured.
// --------------------------------------------------------------------------

// summaryRefreshMinAge is how fresh the current month's cached recap must be to
// be left alone. Older than this and the weekly-ish refresh regenerates it. A
// side benefit: a summary a member just generated on demand is younger than this
// and so is never overwritten out from under them.
const summaryRefreshMinAge = 6 * 24 * time.Hour

// SummaryRefreshSweepArgs is the periodic entry point. Recaps are per household,
// so it fans out one job per household.
type SummaryRefreshSweepArgs struct{}

func (SummaryRefreshSweepArgs) Kind() string { return "summary_refresh_sweep" }

// SummaryRefreshSweepWorker enqueues a per-household recap refresh.
type SummaryRefreshSweepWorker struct {
	river.WorkerDefaults[SummaryRefreshSweepArgs]
	Queries *dbgen.Queries
	Client  *river.Client[pgx.Tx]
}

func (w *SummaryRefreshSweepWorker) Work(ctx context.Context, job *river.Job[SummaryRefreshSweepArgs]) error {
	ids, err := w.Queries.ListHouseholdIDs(ctx)
	if err != nil {
		return fmt.Errorf("list households: %w", err)
	}
	for _, id := range ids {
		if _, err := w.Client.Insert(ctx, SummaryRefreshArgs{HouseholdID: id}, nil); err != nil {
			slog.Error("enqueue summary refresh", "error", err, "household_id", id)
		}
	}
	return nil
}

// SummaryRefreshArgs refreshes one household's cached recaps.
type SummaryRefreshArgs struct {
	HouseholdID uuid.UUID `json:"household_id"`
}

func (SummaryRefreshArgs) Kind() string { return "summary_refresh" }

// SummaryRefreshWorker regenerates the finalised previous month and the
// in-progress current month for one household.
type SummaryRefreshWorker struct {
	river.WorkerDefaults[SummaryRefreshArgs]
	Queries *dbgen.Queries
	AI      *ai.Client
}

func (w *SummaryRefreshWorker) Work(ctx context.Context, job *river.Job[SummaryRefreshArgs]) error {
	// Nothing to generate without a model. The sweep is normally only registered
	// when AI is enabled, but guard here too so a manual enqueue can't error.
	if !w.AI.Enabled() {
		return nil
	}
	now := time.Now().UTC()
	householdID := job.Args.HouseholdID

	curStart := firstOfMonth(now)
	curEnd := curStart.AddDate(0, 1, -1)
	prevStart := curStart.AddDate(0, -1, 0)
	prevEnd := curStart.AddDate(0, 0, -1)

	// Finalise the previous month. Regenerate when there is no cached summary, or
	// when the cached one was written before this month began — meaning it was
	// produced while that month was still in progress (present tense) and needs
	// its past-tense final. A summary already finalised this month is left alone,
	// so this fires at most once per month.
	prevCached, err := w.Queries.GetMonthlySummary(ctx, dbgen.GetMonthlySummaryParams{
		HouseholdID: householdID, Month: prevStart,
	})
	needsFinal := errors.Is(err, pgx.ErrNoRows) || (err == nil && prevCached.CreatedAt.UTC().Before(curStart))
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		slog.Warn("summary refresh: read previous month", "error", err, "household_id", householdID)
	} else if needsFinal {
		w.generateAndCache(ctx, householdID, prevStart, prevEnd, prevStart.Format("January 2006"), now)
	}

	// Refresh the current in-progress month, but only weekly-ish: skip when the
	// cached recap is younger than summaryRefreshMinAge (which also spares a
	// member's just-generated on-demand recap).
	curCached, err := w.Queries.GetMonthlySummary(ctx, dbgen.GetMonthlySummaryParams{
		HouseholdID: householdID, Month: curStart,
	})
	stale := errors.Is(err, pgx.ErrNoRows) || (err == nil && now.Sub(curCached.CreatedAt.UTC()) >= summaryRefreshMinAge)
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		slog.Warn("summary refresh: read current month", "error", err, "household_id", householdID)
	} else if stale {
		w.generateAndCache(ctx, householdID, curStart, curEnd, curStart.Format("January 2006"), now)
	}

	return nil
}

// generateAndCache builds the recap input, asks the model, and upserts the
// result into the household+month cache. Failures are logged and swallowed: a
// missed recap is not worth failing (and retrying) the job over.
func (w *SummaryRefreshWorker) generateAndCache(
	ctx context.Context,
	householdID uuid.UUID,
	from, to time.Time,
	label string,
	asOf time.Time,
) {
	// uuid.Nil = household-shared visibility, matching the insight feed's view.
	input, err := reporting.BuildMonthlySummaryInput(ctx, w.Queries, householdID, uuid.Nil, from, to, label, asOf)
	if err != nil {
		slog.Warn("summary refresh: build input", "error", err, "household_id", householdID, "month", label)
		return
	}
	text, err := w.AI.MonthlySummary(ctx, input)
	if err != nil {
		if !errors.Is(err, ai.ErrDisabled) {
			slog.Warn("summary refresh: generate", "error", err, "household_id", householdID, "month", label)
		}
		return
	}
	if strings.TrimSpace(text) == "" {
		return
	}
	if _, err := w.Queries.UpsertMonthlySummary(ctx, dbgen.UpsertMonthlySummaryParams{
		HouseholdID: householdID, Month: from, Summary: text, Model: w.AI.Model(),
	}); err != nil {
		slog.Warn("summary refresh: cache", "error", err, "household_id", householdID, "month", label)
	}
}
