// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

const getAccountByPlaidID = `-- name: GetAccountByPlaidID :one
SELECT id, plaid_item_id, plaid_account_id, name, official_name, mask, type, subtype, current_balance, available_balance, credit_limit, currency, is_active, created_at, updated_at FROM accounts WHERE plaid_account_id = $1
`

func (q *Queries) GetAccountByPlaidID(ctx context.Context, plaidAccountID string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPlaidID, plaidAccountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PlaidItemID,
		&i.PlaidAccountID,
		&i.Name,
		&i.OfficialName,
		&i.Mask,
		&i.Type,
		&i.Subtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.CreditLimit,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsForItem = `-- name: ListAccountsForItem :many
SELECT id, plaid_item_id, plaid_account_id, name, official_name, mask, type, subtype, current_balance, available_balance, credit_limit, currency, is_active, created_at, updated_at FROM accounts WHERE plaid_item_id = $1 ORDER BY name
`

func (q *Queries) ListAccountsForItem(ctx context.Context, plaidItemID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsForItem, plaidItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.PlaidItemID,
			&i.PlaidAccountID,
			&i.Name,
			&i.OfficialName,
			&i.Mask,
			&i.Type,
			&i.Subtype,
			&i.CurrentBalance,
			&i.AvailableBalance,
			&i.CreditLimit,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleAccounts = `-- name: ListVisibleAccounts :many
SELECT a.id, a.plaid_item_id, a.plaid_account_id, a.name, a.official_name, a.mask, a.type, a.subtype, a.current_balance, a.available_balance, a.credit_limit, a.currency, a.is_active, a.created_at, a.updated_at, i.institution_name, i.user_id AS owner_id
FROM accounts a
JOIN plaid_items i ON i.id = a.plaid_item_id
JOIN users u       ON u.id = i.user_id
WHERE u.household_id = $1
  AND (i.user_id = $2 OR i.is_shared)
  AND a.is_active
ORDER BY i.institution_name, a.name
`

type ListVisibleAccountsParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type ListVisibleAccountsRow struct {
	ID               uuid.UUID           `json:"id"`
	PlaidItemID      uuid.UUID           `json:"plaid_item_id"`
	PlaidAccountID   string              `json:"plaid_account_id"`
	Name             string              `json:"name"`
	OfficialName     *string             `json:"official_name"`
	Mask             *string             `json:"mask"`
	Type             string              `json:"type"`
	Subtype          *string             `json:"subtype"`
	CurrentBalance   decimal.NullDecimal `json:"current_balance"`
	AvailableBalance decimal.NullDecimal `json:"available_balance"`
	CreditLimit      decimal.NullDecimal `json:"credit_limit"`
	Currency         string              `json:"currency"`
	IsActive         bool                `json:"is_active"`
	CreatedAt        stdtime.Time        `json:"created_at"`
	UpdatedAt        stdtime.Time        `json:"updated_at"`
	InstitutionName  *string             `json:"institution_name"`
	OwnerID          uuid.UUID           `json:"owner_id"`
}

// Accounts belonging to items the caller can see. Mirrors ListVisiblePlaidItems.
func (q *Queries) ListVisibleAccounts(ctx context.Context, arg ListVisibleAccountsParams) ([]ListVisibleAccountsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleAccounts, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleAccountsRow{}
	for rows.Next() {
		var i ListVisibleAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlaidItemID,
			&i.PlaidAccountID,
			&i.Name,
			&i.OfficialName,
			&i.Mask,
			&i.Type,
			&i.Subtype,
			&i.CurrentBalance,
			&i.AvailableBalance,
			&i.CreditLimit,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstitutionName,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountActive = `-- name: SetAccountActive :one
UPDATE accounts SET is_active = $2 WHERE id = $1 RETURNING id, plaid_item_id, plaid_account_id, name, official_name, mask, type, subtype, current_balance, available_balance, credit_limit, currency, is_active, created_at, updated_at
`

type SetAccountActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetAccountActive(ctx context.Context, arg SetAccountActiveParams) (Account, error) {
	row := q.db.QueryRow(ctx, setAccountActive, arg.ID, arg.IsActive)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PlaidItemID,
		&i.PlaidAccountID,
		&i.Name,
		&i.OfficialName,
		&i.Mask,
		&i.Type,
		&i.Subtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.CreditLimit,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccount = `-- name: UpsertAccount :one
INSERT INTO accounts (
    plaid_item_id, plaid_account_id, name, official_name, mask,
    type, subtype, current_balance, available_balance, credit_limit, currency
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (plaid_account_id) DO UPDATE SET
    name              = EXCLUDED.name,
    official_name     = EXCLUDED.official_name,
    mask              = EXCLUDED.mask,
    type              = EXCLUDED.type,
    subtype           = EXCLUDED.subtype,
    current_balance   = EXCLUDED.current_balance,
    available_balance = EXCLUDED.available_balance,
    credit_limit      = EXCLUDED.credit_limit,
    currency          = EXCLUDED.currency
RETURNING id, plaid_item_id, plaid_account_id, name, official_name, mask, type, subtype, current_balance, available_balance, credit_limit, currency, is_active, created_at, updated_at
`

type UpsertAccountParams struct {
	PlaidItemID      uuid.UUID           `json:"plaid_item_id"`
	PlaidAccountID   string              `json:"plaid_account_id"`
	Name             string              `json:"name"`
	OfficialName     *string             `json:"official_name"`
	Mask             *string             `json:"mask"`
	Type             string              `json:"type"`
	Subtype          *string             `json:"subtype"`
	CurrentBalance   decimal.NullDecimal `json:"current_balance"`
	AvailableBalance decimal.NullDecimal `json:"available_balance"`
	CreditLimit      decimal.NullDecimal `json:"credit_limit"`
	Currency         string              `json:"currency"`
}

// Plaid is authoritative for account identity and balances, so re-syncing an
// existing account refreshes it in place rather than creating a duplicate.
// is_active is deliberately not touched: excluding an account from reports is
// a user decision that must survive every sync.
func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, upsertAccount,
		arg.PlaidItemID,
		arg.PlaidAccountID,
		arg.Name,
		arg.OfficialName,
		arg.Mask,
		arg.Type,
		arg.Subtype,
		arg.CurrentBalance,
		arg.AvailableBalance,
		arg.CreditLimit,
		arg.Currency,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PlaidItemID,
		&i.PlaidAccountID,
		&i.Name,
		&i.OfficialName,
		&i.Mask,
		&i.Type,
		&i.Subtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.CreditLimit,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
