// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	stdtime "time"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, scopes, last_used_at, expires_at, created_at
`

type CreateAPITokenParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	Name      string        `json:"name"`
	TokenHash string        `json:"token_hash"`
	Scopes    []string      `json:"scopes"`
	ExpiresAt *stdtime.Time `json:"expires_at"`
}

type CreateAPITokenRow struct {
	ID         uuid.UUID     `json:"id"`
	Name       string        `json:"name"`
	Scopes     []string      `json:"scopes"`
	LastUsedAt *stdtime.Time `json:"last_used_at"`
	ExpiresAt  *stdtime.Time `json:"expires_at"`
	CreatedAt  stdtime.Time  `json:"created_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i CreateAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
DELETE FROM api_tokens WHERE id = $1 AND user_id = $2
`

type DeleteAPITokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// user_id is part of the predicate, so a caller cannot revoke someone else's
// token even with a valid id — the same shape as DeleteSessionByID. execrows
// lets the handler tell "not yours" from "deleted" without a second query.
func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAPITokens = `-- name: DeleteExpiredAPITokens :execrows
DELETE FROM api_tokens WHERE expires_at IS NOT NULL AND expires_at <= now()
`

// Housekeeping only. GetAPITokenUser already refuses an expired token, so a row
// left here is never honoured; this just stops them accumulating.
func (q *Queries) DeleteExpiredAPITokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAPITokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPITokenUser = `-- name: GetAPITokenUser :one
SELECT
    t.id           AS token_id,
    t.scopes       AS token_scopes,
    t.last_used_at AS token_last_used_at,
    u.id           AS user_id,
    u.household_id,
    u.email,
    u.display_name,
    u.role,
    p.id           AS person_id
FROM api_tokens t
JOIN users u ON u.id = t.user_id
LEFT JOIN household_people p ON p.user_id = u.id
WHERE t.token_hash = $1
  AND (t.expires_at IS NULL OR t.expires_at > now())
`

type GetAPITokenUserRow struct {
	TokenID         uuid.UUID     `json:"token_id"`
	TokenScopes     []string      `json:"token_scopes"`
	TokenLastUsedAt *stdtime.Time `json:"token_last_used_at"`
	UserID          uuid.UUID     `json:"user_id"`
	HouseholdID     uuid.UUID     `json:"household_id"`
	Email           string        `json:"email"`
	DisplayName     string        `json:"display_name"`
	Role            string        `json:"role"`
	PersonID        *uuid.UUID    `json:"person_id"`
}

// Resolves a bearer token straight to the authenticated user in one round trip,
// returning the SAME columns GetSessionUser does. That symmetry is the point:
// the middleware builds one Identity from either row, so every handler's
// visibility scoping is unchanged by which credential arrived.
//
// Expiry lives in the SQL rather than in Go, exactly as it does for sessions, so
// there is no window where a lapsed token authenticates a request. There is no
// idle cap here — a token that has sat unused for a month is an integration that
// runs monthly, not an abandoned browser.
//
// The LEFT JOIN on household_people matches GetSessionUser: a login whose person
// row was removed still authenticates, it simply has no person-scoped data.
func (q *Queries) GetAPITokenUser(ctx context.Context, tokenHash string) (GetAPITokenUserRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenUser, tokenHash)
	var i GetAPITokenUserRow
	err := row.Scan(
		&i.TokenID,
		&i.TokenScopes,
		&i.TokenLastUsedAt,
		&i.UserID,
		&i.HouseholdID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PersonID,
	)
	return i, err
}

const listUserAPITokens = `-- name: ListUserAPITokens :many
SELECT id, name, scopes, last_used_at, expires_at, created_at
FROM api_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListUserAPITokensRow struct {
	ID         uuid.UUID     `json:"id"`
	Name       string        `json:"name"`
	Scopes     []string      `json:"scopes"`
	LastUsedAt *stdtime.Time `json:"last_used_at"`
	ExpiresAt  *stdtime.Time `json:"expires_at"`
	CreatedAt  stdtime.Time  `json:"created_at"`
}

// Powers the revoke list. The hash is deliberately absent: nothing outside
// authentication has any use for it, and a credential digest has no business in
// a JSON response.
func (q *Queries) ListUserAPITokens(ctx context.Context, userID uuid.UUID) ([]ListUserAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listUserAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAPITokensRow{}
	for rows.Next() {
		var i ListUserAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - $2::interval)
`

type TouchAPITokenParams struct {
	ID     uuid.UUID       `json:"id"`
	MinAge pgtype.Interval `json:"min_age"`
}

// Records activity on a token. The predicate makes this a no-op unless the
// stored value is already stale, so an integration polling on a timer does not
// turn every read into a database write. A token that has never been used has a
// NULL last_used_at and is always written, so the first call is visible
// immediately rather than after the coalescing window.
func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.Exec(ctx, touchAPIToken, arg.ID, arg.MinAge)
	return err
}
