// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_events.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	stdtime "time"
)

const deleteOldAuthEvents = `-- name: DeleteOldAuthEvents :execrows
DELETE FROM auth_events WHERE created_at < now() - $1::interval
`

// Retention sweep. An audit log nobody prunes is just an ever-growing table,
// and the security value of a three-year-old login record is nil.
func (q *Queries) DeleteOldAuthEvents(ctx context.Context, maxAge pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldAuthEvents, maxAge)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserAuthEvents = `-- name: ListUserAuthEvents :many
SELECT event_type, client_ip, user_agent, metadata, created_at
FROM auth_events
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListUserAuthEventsParams struct {
	UserID *uuid.UUID `json:"user_id"`
	Limit  int32      `json:"limit"`
}

type ListUserAuthEventsRow struct {
	EventType string       `json:"event_type"`
	ClientIp  *string      `json:"client_ip"`
	UserAgent *string      `json:"user_agent"`
	Metadata  []byte       `json:"metadata"`
	CreatedAt stdtime.Time `json:"created_at"`
}

func (q *Queries) ListUserAuthEvents(ctx context.Context, arg ListUserAuthEventsParams) ([]ListUserAuthEventsRow, error) {
	rows, err := q.db.Query(ctx, listUserAuthEvents, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAuthEventsRow{}
	for rows.Next() {
		var i ListUserAuthEventsRow
		if err := rows.Scan(
			&i.EventType,
			&i.ClientIp,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuthEvent = `-- name: RecordAuthEvent :exec
INSERT INTO auth_events (user_id, email_attempted, event_type, client_ip, user_agent, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordAuthEventParams struct {
	UserID         *uuid.UUID `json:"user_id"`
	EmailAttempted *string    `json:"email_attempted"`
	EventType      string     `json:"event_type"`
	ClientIp       *string    `json:"client_ip"`
	UserAgent      *string    `json:"user_agent"`
	Metadata       []byte     `json:"metadata"`
}

func (q *Queries) RecordAuthEvent(ctx context.Context, arg RecordAuthEventParams) error {
	_, err := q.db.Exec(ctx, recordAuthEvent,
		arg.UserID,
		arg.EmailAttempted,
		arg.EventType,
		arg.ClientIp,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}
