// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const applyCategory = `-- name: ApplyCategory :exec
UPDATE transactions
SET category_id = $2, category_source = $3
WHERE id = $1 AND category_source IS DISTINCT FROM 'manual'
`

type ApplyCategoryParams struct {
	ID             uuid.UUID  `json:"id"`
	CategoryID     *uuid.UUID `json:"category_id"`
	CategorySource *string    `json:"category_source"`
}

// Applies a resolved category without disturbing a manual choice.
func (q *Queries) ApplyCategory(ctx context.Context, arg ApplyCategoryParams) error {
	_, err := q.db.Exec(ctx, applyCategory, arg.ID, arg.CategoryID, arg.CategorySource)
	return err
}

const applyMerchantCategory = `-- name: ApplyMerchantCategory :exec
UPDATE transactions t
SET category_id = $3, category_source = 'llm'
FROM accounts a, plaid_items i, users u
WHERE t.account_id = a.id
  AND a.plaid_item_id = i.id
  AND i.user_id = u.id
  AND u.household_id = $1
  AND t.merchant_key = $2
  AND t.category_source IS DISTINCT FROM 'manual'
`

type ApplyMerchantCategoryParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	MerchantKey *string    `json:"merchant_key"`
	CategoryID  *uuid.UUID `json:"category_id"`
}

// Applies an LLM-resolved category to every one of a merchant's transactions in
// the household, not just the sampled row — so transactions already sitting in
// the fallback category are lifted out in one statement. Never touches a manual
// choice.
func (q *Queries) ApplyMerchantCategory(ctx context.Context, arg ApplyMerchantCategoryParams) error {
	_, err := q.db.Exec(ctx, applyMerchantCategory, arg.HouseholdID, arg.MerchantKey, arg.CategoryID)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (household_id, name, slug, parent_id, icon, color, is_fixed, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, household_id, parent_id, name, slug, icon, color, is_fixed, is_income, is_transfer, sort_order, created_at, updated_at
`

type CreateCategoryParams struct {
	HouseholdID *uuid.UUID `json:"household_id"`
	Name        string     `json:"name"`
	Slug        string     `json:"slug"`
	ParentID    *uuid.UUID `json:"parent_id"`
	Icon        *string    `json:"icon"`
	Color       *string    `json:"color"`
	IsFixed     bool       `json:"is_fixed"`
	SortOrder   int32      `json:"sort_order"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.HouseholdID,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.Icon,
		arg.Color,
		arg.IsFixed,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsFixed,
		&i.IsIncome,
		&i.IsTransfer,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategoryRule = `-- name: CreateCategoryRule :one
INSERT INTO category_rules (household_id, match_type, pattern, category_id, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, household_id, match_type, pattern, category_id, priority, enabled, created_at, updated_at
`

type CreateCategoryRuleParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	MatchType   string    `json:"match_type"`
	Pattern     string    `json:"pattern"`
	CategoryID  uuid.UUID `json:"category_id"`
	Priority    int32     `json:"priority"`
}

func (q *Queries) CreateCategoryRule(ctx context.Context, arg CreateCategoryRuleParams) (CategoryRule, error) {
	row := q.db.QueryRow(ctx, createCategoryRule,
		arg.HouseholdID,
		arg.MatchType,
		arg.Pattern,
		arg.CategoryID,
		arg.Priority,
	)
	var i CategoryRule
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.MatchType,
		&i.Pattern,
		&i.CategoryID,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategoryRule = `-- name: DeleteCategoryRule :exec
DELETE FROM category_rules WHERE id = $1 AND household_id = $2
`

type DeleteCategoryRuleParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteCategoryRule(ctx context.Context, arg DeleteCategoryRuleParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryRule, arg.ID, arg.HouseholdID)
	return err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, household_id, parent_id, name, slug, icon, color, is_fixed, is_income, is_transfer, sort_order, created_at, updated_at FROM categories
WHERE slug = $1 AND (household_id IS NULL OR household_id = $2)
ORDER BY household_id NULLS LAST
LIMIT 1
`

type GetCategoryBySlugParams struct {
	Slug        string     `json:"slug"`
	HouseholdID *uuid.UUID `json:"household_id"`
}

func (q *Queries) GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, arg.Slug, arg.HouseholdID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsFixed,
		&i.IsIncome,
		&i.IsTransfer,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, household_id, parent_id, name, slug, icon, color, is_fixed, is_income, is_transfer, sort_order, created_at, updated_at FROM categories
WHERE household_id IS NULL OR household_id = $1
ORDER BY sort_order, name
`

// System categories plus this household's own.
func (q *Queries) ListCategories(ctx context.Context, householdID *uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.Color,
			&i.IsFixed,
			&i.IsIncome,
			&i.IsTransfer,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryRules = `-- name: ListCategoryRules :many
SELECT id, household_id, match_type, pattern, category_id, priority, enabled, created_at, updated_at FROM category_rules
WHERE household_id = $1 AND enabled
ORDER BY priority DESC, created_at
`

func (q *Queries) ListCategoryRules(ctx context.Context, householdID uuid.UUID) ([]CategoryRule, error) {
	rows, err := q.db.Query(ctx, listCategoryRules, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryRule{}
	for rows.Next() {
		var i CategoryRule
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.MatchType,
			&i.Pattern,
			&i.CategoryID,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdIDs = `-- name: ListHouseholdIDs :many
SELECT id FROM households ORDER BY created_at
`

func (q *Queries) ListHouseholdIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listHouseholdIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMCandidates = `-- name: ListLLMCandidates :many
SELECT t.id, t.merchant_key, t.merchant_name, t.name,
       t.plaid_pfc_primary, t.plaid_pfc_detailed
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN plaid_items i ON i.id = a.plaid_item_id
JOIN users u       ON u.id = i.user_id
WHERE u.household_id = $1
  AND t.category_id = $2
  AND t.category_source IS DISTINCT FROM 'manual'
  AND t.merchant_key IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM merchant_category_map m
      WHERE m.household_id = $1 AND m.merchant_key = t.merchant_key
  )
ORDER BY t.merchant_key
LIMIT $3
`

type ListLLMCandidatesParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	CategoryID  *uuid.UUID `json:"category_id"`
	Limit       int32      `json:"limit"`
}

type ListLLMCandidatesRow struct {
	ID               uuid.UUID `json:"id"`
	MerchantKey      *string   `json:"merchant_key"`
	MerchantName     *string   `json:"merchant_name"`
	Name             string    `json:"name"`
	PlaidPfcPrimary  *string   `json:"plaid_pfc_primary"`
	PlaidPfcDetailed *string   `json:"plaid_pfc_detailed"`
}

// Transactions the deterministic pass left in the fallback category ($2, the
// household's "uncategorised" category) and that the LLM has not been asked
// about yet. A merchant already in merchant_category_map is excluded: caching
// every answer is what makes a merchant cost at most one model call, ever.
// Rows without a merchant_key are skipped — there is nothing to cache them by.
func (q *Queries) ListLLMCandidates(ctx context.Context, arg ListLLMCandidatesParams) ([]ListLLMCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listLLMCandidates, arg.HouseholdID, arg.CategoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLLMCandidatesRow{}
	for rows.Next() {
		var i ListLLMCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantKey,
			&i.MerchantName,
			&i.Name,
			&i.PlaidPfcPrimary,
			&i.PlaidPfcDetailed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncategorisedTransactions = `-- name: ListUncategorisedTransactions :many
SELECT t.id, t.merchant_key, t.merchant_name, t.name,
       t.plaid_pfc_primary, t.plaid_pfc_detailed
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN plaid_items i ON i.id = a.plaid_item_id
JOIN users u       ON u.id = i.user_id
WHERE u.household_id = $1
  AND t.category_id IS NULL
LIMIT $2
`

type ListUncategorisedTransactionsParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Limit       int32     `json:"limit"`
}

type ListUncategorisedTransactionsRow struct {
	ID               uuid.UUID `json:"id"`
	MerchantKey      *string   `json:"merchant_key"`
	MerchantName     *string   `json:"merchant_name"`
	Name             string    `json:"name"`
	PlaidPfcPrimary  *string   `json:"plaid_pfc_primary"`
	PlaidPfcDetailed *string   `json:"plaid_pfc_detailed"`
}

// Transactions still needing a category, scoped to one household. merchant_name
// and name are selected because household rules (match step 2) match against
// them — without them the deterministic pass could never fire a rule.
func (q *Queries) ListUncategorisedTransactions(ctx context.Context, arg ListUncategorisedTransactionsParams) ([]ListUncategorisedTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listUncategorisedTransactions, arg.HouseholdID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUncategorisedTransactionsRow{}
	for rows.Next() {
		var i ListUncategorisedTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantKey,
			&i.MerchantName,
			&i.Name,
			&i.PlaidPfcPrimary,
			&i.PlaidPfcDetailed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupMerchantCategory = `-- name: LookupMerchantCategory :one
SELECT category_id FROM merchant_category_map
WHERE household_id = $1 AND merchant_key = $2
`

type LookupMerchantCategoryParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	MerchantKey string    `json:"merchant_key"`
}

func (q *Queries) LookupMerchantCategory(ctx context.Context, arg LookupMerchantCategoryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lookupMerchantCategory, arg.HouseholdID, arg.MerchantKey)
	var category_id uuid.UUID
	err := row.Scan(&category_id)
	return category_id, err
}

const resolvePFCCategory = `-- name: ResolvePFCCategory :one
SELECT c.id, c.household_id, c.parent_id, c.name, c.slug, c.icon, c.color, c.is_fixed, c.is_income, c.is_transfer, c.sort_order, c.created_at, c.updated_at
FROM pfc_category_map m
JOIN categories c ON c.slug = m.category_slug AND c.household_id IS NULL
WHERE m.pfc_primary = $1
  AND (m.pfc_detailed = $2 OR m.pfc_detailed IS NULL)
ORDER BY m.pfc_detailed NULLS LAST
LIMIT 1
`

type ResolvePFCCategoryParams struct {
	PfcPrimary  string  `json:"pfc_primary"`
	PfcDetailed *string `json:"pfc_detailed"`
}

// Maps a Plaid category onto ours, preferring a detailed-level match so
// specific overrides (credit-card payments) beat the broad primary mapping.
func (q *Queries) ResolvePFCCategory(ctx context.Context, arg ResolvePFCCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, resolvePFCCategory, arg.PfcPrimary, arg.PfcDetailed)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsFixed,
		&i.IsIncome,
		&i.IsTransfer,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTransactionCategory = `-- name: SetTransactionCategory :one
UPDATE transactions t
SET category_id = $3, category_source = 'manual'
FROM accounts a, plaid_items i, users u
WHERE t.id = $1
  AND a.id = t.account_id
  AND i.id = a.plaid_item_id
  AND u.id = i.user_id
  AND u.household_id = $2
RETURNING t.id, t.account_id, t.plaid_transaction_id, t.amount, t.currency, t.date, t.authorized_date, t.name, t.merchant_name, t.merchant_key, t.pending, t.pending_transaction_id, t.plaid_pfc_primary, t.plaid_pfc_detailed, t.category_id, t.category_source, t.is_recurring, t.excluded_from_reports, t.notes, t.source, t.raw, t.created_at, t.updated_at
`

type SetTransactionCategoryParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	CategoryID  *uuid.UUID `json:"category_id"`
}

// Manual recategorisation. category_source = 'manual' makes the choice sticky:
// the sync upsert preserves it, so Plaid can never overwrite it.
func (q *Queries) SetTransactionCategory(ctx context.Context, arg SetTransactionCategoryParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, setTransactionCategory, arg.ID, arg.HouseholdID, arg.CategoryID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PlaidTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.AuthorizedDate,
		&i.Name,
		&i.MerchantName,
		&i.MerchantKey,
		&i.Pending,
		&i.PendingTransactionID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.CategoryID,
		&i.CategorySource,
		&i.IsRecurring,
		&i.ExcludedFromReports,
		&i.Notes,
		&i.Source,
		&i.Raw,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMerchantCategory = `-- name: UpsertMerchantCategory :exec
INSERT INTO merchant_category_map (household_id, merchant_key, category_id, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (household_id, merchant_key) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    source      = EXCLUDED.source
WHERE merchant_category_map.source <> 'manual' OR EXCLUDED.source = 'manual'
`

type UpsertMerchantCategoryParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	MerchantKey string    `json:"merchant_key"`
	CategoryID  uuid.UUID `json:"category_id"`
	Source      string    `json:"source"`
}

// Caches a resolved merchant so the same decision is never recomputed. A
// manual choice outranks anything previously learned.
func (q *Queries) UpsertMerchantCategory(ctx context.Context, arg UpsertMerchantCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertMerchantCategory,
		arg.HouseholdID,
		arg.MerchantKey,
		arg.CategoryID,
		arg.Source,
	)
	return err
}
