// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const digestDeliveryExists = `-- name: DigestDeliveryExists :one
SELECT EXISTS (
    SELECT 1 FROM digest_deliveries WHERE user_id = $1 AND period_key = $2
)
`

type DigestDeliveryExistsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	PeriodKey string    `json:"period_key"`
}

// True once a digest for this (user, period) has been recorded, so the sweep and
// the worker both skip a user already served this week/month.
func (q *Queries) DigestDeliveryExists(ctx context.Context, arg DigestDeliveryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, digestDeliveryExists, arg.UserID, arg.PeriodKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDigestEnabledUsers = `-- name: ListDigestEnabledUsers :many

SELECT
    u.id           AS user_id,
    u.household_id AS household_id,
    COALESCE(c.value #>> '{}', 'weekly')::text AS cadence
FROM users u
JOIN preferences e
  ON e.scope = 'user' AND e.user_id = u.id
 AND e.key = 'digest.enabled' AND e.value = 'true'::jsonb
LEFT JOIN preferences c
  ON c.scope = 'user' AND c.user_id = u.id AND c.key = 'digest.cadence'
`

type ListDigestEnabledUsersRow struct {
	UserID      uuid.UUID `json:"user_id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Cadence     string    `json:"cadence"`
}

// Scheduled digest: who is opted in, the dedupe guard, and the top unread
// insights the digest carries. Opt-in is per user, so the sweep enumerates
// users (not households) and resolves each user's household for the figures.
// Users who have turned the digest on, with their household and cadence. The
// cadence is read out of JSONB as text (defaulting to weekly) so the sweep can
// gate on it without a second per-user lookup.
func (q *Queries) ListDigestEnabledUsers(ctx context.Context) ([]ListDigestEnabledUsersRow, error) {
	rows, err := q.db.Query(ctx, listDigestEnabledUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDigestEnabledUsersRow{}
	for rows.Next() {
		var i ListDigestEnabledUsersRow
		if err := rows.Scan(&i.UserID, &i.HouseholdID, &i.Cadence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadInsightsForDigest = `-- name: ListUnreadInsightsForDigest :many
SELECT id, household_id, kind, priority, title, body, data, period, dedupe_key, created_at, read_at, dismissed_at FROM insights
WHERE household_id = $1 AND dismissed_at IS NULL AND read_at IS NULL
ORDER BY priority DESC, created_at DESC
LIMIT $2
`

type ListUnreadInsightsForDigestParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Limit       int32     `json:"limit"`
}

// The top unread, non-dismissed insights for a household, in feed order, capped
// for the digest body.
func (q *Queries) ListUnreadInsightsForDigest(ctx context.Context, arg ListUnreadInsightsForDigestParams) ([]Insight, error) {
	rows, err := q.db.Query(ctx, listUnreadInsightsForDigest, arg.HouseholdID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Insight{}
	for rows.Next() {
		var i Insight
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Kind,
			&i.Priority,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.Period,
			&i.DedupeKey,
			&i.CreatedAt,
			&i.ReadAt,
			&i.DismissedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDigestDelivery = `-- name: RecordDigestDelivery :exec
INSERT INTO digest_deliveries (user_id, period_key)
VALUES ($1, $2)
ON CONFLICT (user_id, period_key) DO NOTHING
`

type RecordDigestDeliveryParams struct {
	UserID    uuid.UUID `json:"user_id"`
	PeriodKey string    `json:"period_key"`
}

// Insert-on-send. DO NOTHING makes a re-run harmless if two workers race.
func (q *Queries) RecordDigestDelivery(ctx context.Context, arg RecordDigestDeliveryParams) error {
	_, err := q.db.Exec(ctx, recordDigestDelivery, arg.UserID, arg.PeriodKey)
	return err
}
