// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

const archiveGoal = `-- name: ArchiveGoal :exec
UPDATE goals
SET archived_at = now()
WHERE id = $1
  AND household_id = $2
  AND (
        scope = 'household'
     OR (scope = 'user'   AND user_id = $3)
     OR (scope = 'person' AND ($4::boolean
                               OR person_id = $5))
  )
`

type ArchiveGoalParams struct {
	ID             uuid.UUID  `json:"id"`
	HouseholdID    uuid.UUID  `json:"household_id"`
	UserID         *uuid.UUID `json:"user_id"`
	AllPersonGoals bool       `json:"all_person_goals"`
	PersonID       *uuid.UUID `json:"person_id"`
}

func (q *Queries) ArchiveGoal(ctx context.Context, arg ArchiveGoalParams) error {
	_, err := q.db.Exec(ctx, archiveGoal,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
		arg.AllPersonGoals,
		arg.PersonID,
	)
	return err
}

const createGoal = `-- name: CreateGoal :one

INSERT INTO goals (
    household_id, scope, user_id, person_id, kind, name, target_amount,
    target_date, account_id, category_id, college_years
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    COALESCE($11::smallint, 4)
)
RETURNING id, household_id, scope, user_id, kind, name, target_amount, target_date, account_id, category_id, created_at, achieved_at, archived_at, person_id, college_years
`

type CreateGoalParams struct {
	HouseholdID  uuid.UUID       `json:"household_id"`
	Scope        string          `json:"scope"`
	UserID       *uuid.UUID      `json:"user_id"`
	PersonID     *uuid.UUID      `json:"person_id"`
	Kind         string          `json:"kind"`
	Name         string          `json:"name"`
	TargetAmount decimal.Decimal `json:"target_amount"`
	TargetDate   *stdtime.Time   `json:"target_date"`
	AccountID    *uuid.UUID      `json:"account_id"`
	CategoryID   *uuid.UUID      `json:"category_id"`
	CollegeYears *int16          `json:"college_years"`
}

// Goals: savings/target goals and the derived-progress lookups behind them.
// Every read is scoped so a caller sees their household's shared goals plus
// their own, never another member's private goal.
//
// Three scopes, and the visibility rule differs per scope:
//
//	household — everyone in the household
//	user      — only the login that owns it
//	person    — the person it belongs to, plus any adult (a parent manages a
//	            child's goals, and a child who cannot see their own goal has
//	            no teaching surface at all)
//
// `all_person_goals` carries the adult/child decision into the SQL rather than
// letting each caller re-derive it. It is set from the caller's role, which is
// checked server-side; a child session always passes false.
// college_years is only meaningful for a 'college' goal; every other kind
// carries the default of 4 and ignores it. For a college goal target_amount is
// ONE YEAR'S cost in today's dollars — see allocation/college.go, which inflates
// each year separately and draws them down, and the migration comment on
// goals.college_years.
//
// NULLABLE, and COALESCEd rather than taken as a plain argument. A plain one
// makes the Go zero value (0) a real argument, and 0 violates the column's
// CHECK — so every caller that had no opinion about college years, including
// ones written years before this column existed, would start failing on INSERT.
// "I did not say" has to be expressible, and here it means four.
//
// The literal 4 mirrors the column DEFAULT in 00055_allocation_planner.sql and
// api.defaultCollegeYears. Three copies is two too many, but a column default
// cannot be read from a parameterised INSERT; keep them in step.
func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.HouseholdID,
		arg.Scope,
		arg.UserID,
		arg.PersonID,
		arg.Kind,
		arg.Name,
		arg.TargetAmount,
		arg.TargetDate,
		arg.AccountID,
		arg.CategoryID,
		arg.CollegeYears,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Scope,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.TargetAmount,
		&i.TargetDate,
		&i.AccountID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.AchievedAt,
		&i.ArchivedAt,
		&i.PersonID,
		&i.CollegeYears,
	)
	return i, err
}

const createGoalContribution = `-- name: CreateGoalContribution :one

INSERT INTO goal_contributions (goal_id, person_id, amount, occurred_on, note)
SELECT g.id, p.id, $1::numeric,
       $2::date, $3
FROM goals g
JOIN household_people p
  ON p.id = $4 AND p.household_id = g.household_id
WHERE g.id = $5
  AND g.household_id = $6
RETURNING id, goal_id, person_id, amount, occurred_on, note, created_at
`

type CreateGoalContributionParams struct {
	Amount      decimal.Decimal `json:"amount"`
	OccurredOn  stdtime.Time    `json:"occurred_on"`
	Note        *string         `json:"note"`
	PersonID    uuid.UUID       `json:"person_id"`
	GoalID      uuid.UUID       `json:"goal_id"`
	HouseholdID uuid.UUID       `json:"household_id"`
}

// --------------------------------------------------------------------------
// Contributions
// --------------------------------------------------------------------------
//
// ATTRIBUTION, not progress. For an account-linked goal, progress remains the
// account balance (see the 00012 header rule: progress is DERIVED, never
// stored); these rows record who funded what. For an unlinked goal they are the
// natural progress source. Never let the two become one number.
// Goal and person are both re-resolved through the household guard rather than
// trusted from the request.
func (q *Queries) CreateGoalContribution(ctx context.Context, arg CreateGoalContributionParams) (GoalContribution, error) {
	row := q.db.QueryRow(ctx, createGoalContribution,
		arg.Amount,
		arg.OccurredOn,
		arg.Note,
		arg.PersonID,
		arg.GoalID,
		arg.HouseholdID,
	)
	var i GoalContribution
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.PersonID,
		&i.Amount,
		&i.OccurredOn,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGoalContribution = `-- name: DeleteGoalContribution :execrows
DELETE FROM goal_contributions c
USING goals g
WHERE c.id = $1
  AND g.id = c.goal_id
  AND g.household_id = $2
`

type DeleteGoalContributionParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteGoalContribution(ctx context.Context, arg DeleteGoalContributionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoalContribution, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGoal = `-- name: GetGoal :one
SELECT id, household_id, scope, user_id, kind, name, target_amount, target_date, account_id, category_id, created_at, achieved_at, archived_at, person_id, college_years FROM goals
WHERE id = $1
  AND household_id = $2
  AND (
        scope = 'household'
     OR (scope = 'user'   AND user_id = $3)
     OR (scope = 'person' AND ($4::boolean
                               OR person_id = $5))
  )
`

type GetGoalParams struct {
	ID             uuid.UUID  `json:"id"`
	HouseholdID    uuid.UUID  `json:"household_id"`
	UserID         *uuid.UUID `json:"user_id"`
	AllPersonGoals bool       `json:"all_person_goals"`
	PersonID       *uuid.UUID `json:"person_id"`
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
		arg.AllPersonGoals,
		arg.PersonID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Scope,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.TargetAmount,
		&i.TargetDate,
		&i.AccountID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.AchievedAt,
		&i.ArchivedAt,
		&i.PersonID,
		&i.CollegeYears,
	)
	return i, err
}

const getGoalAccountBalance = `-- name: GetGoalAccountBalance :one
SELECT COALESCE(a.current_balance, 0)::numeric AS balance
FROM accounts a
JOIN account_access v ON v.account_id = a.id
WHERE a.id = $1 AND v.household_id = $2
`

type GetGoalAccountBalanceParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

// Current balance of a goal's linked account, scoped to the household so a goal
// can never read another household's account. Coalesced to 0 when unknown.
func (q *Queries) GetGoalAccountBalance(ctx context.Context, arg GetGoalAccountBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getGoalAccountBalance, arg.ID, arg.HouseholdID)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const getGoalDebtTerms = `-- name: GetGoalDebtTerms :one
SELECT
    a.type,
    a.subtype,
    COALESCE(a.current_balance, 0)::numeric AS balance,
    t.apr             AS manual_apr,
    t.minimum_payment AS manual_minimum_payment,
    -- The scheduled bill outranks the typed minimum payment, so a schedule
    -- edited on the bill calendar and a payoff projection can never quote
    -- different numbers for the same payment.
    o.amount          AS obligation_amount,
    l.apr,
    l.interest_rate_percentage,
    l.minimum_payment
FROM accounts a
JOIN account_access v ON v.account_id = a.id
LEFT JOIN liabilities l   ON l.account_id = a.id
LEFT JOIN account_terms t ON t.account_id = a.id
LEFT JOIN recurring_obligations o
       ON o.id = t.payment_obligation_id AND o.is_active
WHERE a.id = $1 AND v.household_id = $2
`

type GetGoalDebtTermsParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetGoalDebtTermsRow struct {
	Type                   string              `json:"type"`
	Subtype                *string             `json:"subtype"`
	Balance                decimal.Decimal     `json:"balance"`
	ManualApr              decimal.NullDecimal `json:"manual_apr"`
	ManualMinimumPayment   decimal.NullDecimal `json:"manual_minimum_payment"`
	ObligationAmount       decimal.NullDecimal `json:"obligation_amount"`
	Apr                    decimal.NullDecimal `json:"apr"`
	InterestRatePercentage decimal.NullDecimal `json:"interest_rate_percentage"`
	MinimumPayment         decimal.NullDecimal `json:"minimum_payment"`
}

// Everything a debt-payoff goal needs to know about its linked account: whether
// it is a debt at all, what is owed on it right now, and the terms to amortize
// at — the institution's, and the household's own, which override them.
//
// Replaces GetGoalLiability, which selected FROM liabilities and so answered
// "does Plaid serve terms for this account?" when the question is "is this
// account a debt?". Those are different questions with different answers: Plaid
// serves the Liabilities product for a minority of institutions, and the answer
// to the first was no for every debt the household that found this bug had. The
// gate is now a.type, matching ComputeNetWorth and money.ts isLiability().
//
// Scoped through the same account → plaid_item → user chain as
// GetGoalAccountBalance, and deliberately with the same household-wide rule
// rather than the stricter is_shared one, so no goal that resolves today stops
// resolving.
//
// BALANCE is the account's current_balance, never liabilities.balance: the
// latter is the last statement balance for a card, and a payoff schedule must
// start from what is owed now. Coalesced to 0 when unknown, as
// GetGoalAccountBalance does.
//
// Student loans and mortgages report interest_rate_percentage rather than apr,
// so both are returned and mergeDebtTerms falls back between them.
func (q *Queries) GetGoalDebtTerms(ctx context.Context, arg GetGoalDebtTermsParams) (GetGoalDebtTermsRow, error) {
	row := q.db.QueryRow(ctx, getGoalDebtTerms, arg.ID, arg.HouseholdID)
	var i GetGoalDebtTermsRow
	err := row.Scan(
		&i.Type,
		&i.Subtype,
		&i.Balance,
		&i.ManualApr,
		&i.ManualMinimumPayment,
		&i.ObligationAmount,
		&i.Apr,
		&i.InterestRatePercentage,
		&i.MinimumPayment,
	)
	return i, err
}

const listActiveHouseholdGoals = `-- name: ListActiveHouseholdGoals :many
SELECT id, household_id, scope, user_id, kind, name, target_amount, target_date, account_id, category_id, created_at, achieved_at, archived_at, person_id, college_years FROM goals
WHERE household_id = $1 AND scope = 'household' AND archived_at IS NULL
`

// Household-scoped active goals only. The insight feed is household-shared and
// has no per-user visibility, so the coaching producer coaches shared goals
// exclusively — a personal goal never leaks into a feed the whole household
// reads. Personal goals still work everywhere else (CRUD + feasibility on the
// Goals page).
func (q *Queries) ListActiveHouseholdGoals(ctx context.Context, householdID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listActiveHouseholdGoals, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Scope,
			&i.UserID,
			&i.Kind,
			&i.Name,
			&i.TargetAmount,
			&i.TargetDate,
			&i.AccountID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.AchievedAt,
			&i.ArchivedAt,
			&i.PersonID,
			&i.CollegeYears,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalContributions = `-- name: ListGoalContributions :many
SELECT c.id, c.goal_id, c.person_id, c.amount, c.occurred_on, c.note, c.created_at, p.display_name
FROM goal_contributions c
JOIN goals g            ON g.id = c.goal_id
JOIN household_people p ON p.id = c.person_id
WHERE c.goal_id = $1 AND g.household_id = $2
ORDER BY c.occurred_on DESC, c.created_at DESC
`

type ListGoalContributionsParams struct {
	GoalID      uuid.UUID `json:"goal_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type ListGoalContributionsRow struct {
	ID          uuid.UUID       `json:"id"`
	GoalID      uuid.UUID       `json:"goal_id"`
	PersonID    uuid.UUID       `json:"person_id"`
	Amount      decimal.Decimal `json:"amount"`
	OccurredOn  stdtime.Time    `json:"occurred_on"`
	Note        *string         `json:"note"`
	CreatedAt   stdtime.Time    `json:"created_at"`
	DisplayName string          `json:"display_name"`
}

func (q *Queries) ListGoalContributions(ctx context.Context, arg ListGoalContributionsParams) ([]ListGoalContributionsRow, error) {
	rows, err := q.db.Query(ctx, listGoalContributions, arg.GoalID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalContributionsRow{}
	for rows.Next() {
		var i ListGoalContributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.PersonID,
			&i.Amount,
			&i.OccurredOn,
			&i.Note,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, household_id, scope, user_id, kind, name, target_amount, target_date, account_id, category_id, created_at, achieved_at, archived_at, person_id, college_years FROM goals
WHERE household_id = $1
  AND archived_at IS NULL
  AND (
        scope = 'household'
     OR (scope = 'user'   AND user_id = $2)
     OR (scope = 'person' AND ($3::boolean
                               OR person_id = $4))
  )
ORDER BY created_at DESC
`

type ListGoalsParams struct {
	HouseholdID    uuid.UUID  `json:"household_id"`
	UserID         *uuid.UUID `json:"user_id"`
	AllPersonGoals bool       `json:"all_person_goals"`
	PersonID       *uuid.UUID `json:"person_id"`
}

// Active goals visible to the caller.
func (q *Queries) ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals,
		arg.HouseholdID,
		arg.UserID,
		arg.AllPersonGoals,
		arg.PersonID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Scope,
			&i.UserID,
			&i.Kind,
			&i.Name,
			&i.TargetAmount,
			&i.TargetDate,
			&i.AccountID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.AchievedAt,
			&i.ArchivedAt,
			&i.PersonID,
			&i.CollegeYears,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGoalAchieved = `-- name: MarkGoalAchieved :exec
UPDATE goals
SET achieved_at = now()
WHERE id = $1 AND household_id = $2 AND achieved_at IS NULL
`

type MarkGoalAchievedParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

// Stamps the first time progress reaches the target; the guard keeps the
// original achievement time even if the producer re-runs.
func (q *Queries) MarkGoalAchieved(ctx context.Context, arg MarkGoalAchievedParams) error {
	_, err := q.db.Exec(ctx, markGoalAchieved, arg.ID, arg.HouseholdID)
	return err
}

const sumGoalContributions = `-- name: SumGoalContributions :one
SELECT COALESCE(SUM(c.amount), 0)::numeric AS total
FROM goal_contributions c
JOIN goals g ON g.id = c.goal_id
WHERE c.goal_id = $1 AND g.household_id = $2
`

type SumGoalContributionsParams struct {
	GoalID      uuid.UUID `json:"goal_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) SumGoalContributions(ctx context.Context, arg SumGoalContributionsParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumGoalContributions, arg.GoalID, arg.HouseholdID)
	var total decimal.Decimal
	err := row.Scan(&total)
	return total, err
}

const sumGoalContributionsByPerson = `-- name: SumGoalContributionsByPerson :many
SELECT p.id AS person_id, p.display_name, SUM(c.amount)::numeric AS total
FROM goal_contributions c
JOIN goals g            ON g.id = c.goal_id
JOIN household_people p ON p.id = c.person_id
WHERE c.goal_id = $1 AND g.household_id = $2
GROUP BY p.id, p.display_name
ORDER BY SUM(c.amount) DESC
`

type SumGoalContributionsByPersonParams struct {
	GoalID      uuid.UUID `json:"goal_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type SumGoalContributionsByPersonRow struct {
	PersonID    uuid.UUID       `json:"person_id"`
	DisplayName string          `json:"display_name"`
	Total       decimal.Decimal `json:"total"`
}

// The "who funded what" breakdown. Ordered by size so the biggest contributor
// reads first.
func (q *Queries) SumGoalContributionsByPerson(ctx context.Context, arg SumGoalContributionsByPersonParams) ([]SumGoalContributionsByPersonRow, error) {
	rows, err := q.db.Query(ctx, sumGoalContributionsByPerson, arg.GoalID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumGoalContributionsByPersonRow{}
	for rows.Next() {
		var i SumGoalContributionsByPersonRow
		if err := rows.Scan(&i.PersonID, &i.DisplayName, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET name = $1,
    target_amount = $2,
    target_date = $3,
    account_id = $4,
    category_id = $5,
    -- NULL leaves it alone. The update body is otherwise the whole state, but
    -- a client that has never heard of college_years (every client written
    -- before doc 32) would otherwise silently reset a five-year programme to
    -- four every time somebody renamed the goal.
    college_years = COALESCE($6::smallint, college_years)
WHERE id = $7
  AND household_id = $8
  AND (
        scope = 'household'
     OR (scope = 'user'   AND user_id = $9)
     OR (scope = 'person' AND ($10::boolean
                               OR person_id = $11))
  )
RETURNING id, household_id, scope, user_id, kind, name, target_amount, target_date, account_id, category_id, created_at, achieved_at, archived_at, person_id, college_years
`

type UpdateGoalParams struct {
	Name           string          `json:"name"`
	TargetAmount   decimal.Decimal `json:"target_amount"`
	TargetDate     *stdtime.Time   `json:"target_date"`
	AccountID      *uuid.UUID      `json:"account_id"`
	CategoryID     *uuid.UUID      `json:"category_id"`
	CollegeYears   *int16          `json:"college_years"`
	ID             uuid.UUID       `json:"id"`
	HouseholdID    uuid.UUID       `json:"household_id"`
	UserID         *uuid.UUID      `json:"user_id"`
	AllPersonGoals bool            `json:"all_person_goals"`
	PersonID       *uuid.UUID      `json:"person_id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.Name,
		arg.TargetAmount,
		arg.TargetDate,
		arg.AccountID,
		arg.CategoryID,
		arg.CollegeYears,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
		arg.AllPersonGoals,
		arg.PersonID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Scope,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.TargetAmount,
		&i.TargetDate,
		&i.AccountID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.AchievedAt,
		&i.ArchivedAt,
		&i.PersonID,
		&i.CollegeYears,
	)
	return i, err
}
