// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: households.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	stdtime "time"
)

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at, filing_status, risk_drawdown_floor, magi, magi_tax_year, plan_reviewed_at
`

func (q *Queries) CreateHousehold(ctx context.Context, name string) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold, name)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FilingStatus,
		&i.RiskDrawdownFloor,
		&i.Magi,
		&i.MagiTaxYear,
		&i.PlanReviewedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO household_invites (
    household_id, email, token_hash, invited_by, expires_at, role, person_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, household_id, email, token_hash, invited_by, expires_at, accepted_at, created_at, role, person_id
`

type CreateInviteParams struct {
	HouseholdID uuid.UUID    `json:"household_id"`
	Email       string       `json:"email"`
	TokenHash   string       `json:"token_hash"`
	InvitedBy   *uuid.UUID   `json:"invited_by"`
	ExpiresAt   stdtime.Time `json:"expires_at"`
	Role        string       `json:"role"`
	PersonID    *uuid.UUID   `json:"person_id"`
}

// `role` is the permission level the invite grants; `person_id` attaches the
// new login to an EXISTING person rather than creating a second one. That is
// how "enable a login for Ellie" works — without it, accepting the invite would
// produce a duplicate Ellie with no 529 attached.
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.HouseholdID,
		arg.Email,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
		arg.Role,
		arg.PersonID,
	)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.Role,
		&i.PersonID,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM household_invites WHERE id = $1 AND household_id = $2
`

type DeleteInviteParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.Exec(ctx, deleteInvite, arg.ID, arg.HouseholdID)
	return err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, name, created_at, updated_at, filing_status, risk_drawdown_floor, magi, magi_tax_year, plan_reviewed_at FROM households WHERE id = $1
`

func (q *Queries) GetHousehold(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FilingStatus,
		&i.RiskDrawdownFloor,
		&i.Magi,
		&i.MagiTaxYear,
		&i.PlanReviewedAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, household_id, email, token_hash, invited_by, expires_at, accepted_at, created_at, role, person_id FROM household_invites
WHERE token_hash = $1
  AND accepted_at IS NULL
  AND expires_at > now()
`

// Only returns invites that are still usable, so callers cannot accidentally
// accept an expired or already-redeemed invitation.
func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.Role,
		&i.PersonID,
	)
	return i, err
}

const listHouseholdMembers = `-- name: ListHouseholdMembers :many
SELECT id, household_id, email, display_name, role, created_at
FROM users
WHERE household_id = $1
ORDER BY created_at
`

type ListHouseholdMembersRow struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	Email       string       `json:"email"`
	DisplayName string       `json:"display_name"`
	Role        string       `json:"role"`
	CreatedAt   stdtime.Time `json:"created_at"`
}

func (q *Queries) ListHouseholdMembers(ctx context.Context, householdID uuid.UUID) ([]ListHouseholdMembersRow, error) {
	rows, err := q.db.Query(ctx, listHouseholdMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHouseholdMembersRow{}
	for rows.Next() {
		var i ListHouseholdMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT i.id, i.household_id, i.email, i.invited_by, i.expires_at, i.created_at,
       i.role, i.person_id, p.display_name AS person_name
FROM household_invites i
LEFT JOIN household_people p ON p.id = i.person_id
WHERE i.household_id = $1 AND i.accepted_at IS NULL AND i.expires_at > now()
ORDER BY i.created_at DESC
`

type ListPendingInvitesRow struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	Email       string       `json:"email"`
	InvitedBy   *uuid.UUID   `json:"invited_by"`
	ExpiresAt   stdtime.Time `json:"expires_at"`
	CreatedAt   stdtime.Time `json:"created_at"`
	Role        string       `json:"role"`
	PersonID    *uuid.UUID   `json:"person_id"`
	PersonName  *string      `json:"person_name"`
}

func (q *Queries) ListPendingInvites(ctx context.Context, householdID uuid.UUID) ([]ListPendingInvitesRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvites, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitesRow{}
	for rows.Next() {
		var i ListPendingInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Email,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Role,
			&i.PersonID,
			&i.PersonName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE household_invites SET accepted_at = now() WHERE id = $1
`

func (q *Queries) MarkInviteAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, id)
	return err
}

const renameHousehold = `-- name: RenameHousehold :one
UPDATE households SET name = $2 WHERE id = $1 RETURNING id, name, created_at, updated_at, filing_status, risk_drawdown_floor, magi, magi_tax_year, plan_reviewed_at
`

type RenameHouseholdParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameHousehold(ctx context.Context, arg RenameHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, renameHousehold, arg.ID, arg.Name)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FilingStatus,
		&i.RiskDrawdownFloor,
		&i.Magi,
		&i.MagiTaxYear,
		&i.PlanReviewedAt,
	)
	return i, err
}
