// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manual_accounts.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

const addToManualAccountBalance = `-- name: AddToManualAccountBalance :one
UPDATE accounts
SET current_balance = COALESCE(current_balance, 0) + $1,
    updated_at      = now()
WHERE id = $2
  AND source = 'manual'
RETURNING current_balance
`

type AddToManualAccountBalanceParams struct {
	Delta decimal.NullDecimal `json:"delta"`
	ID    uuid.UUID           `json:"id"`
}

// Moves a manual account's balance by a delta and reports the result, so the
// caller can write the matching account_balance_history row with the exact
// figure the account now holds rather than recomputing it and risking a
// disagreement.
//
// A delta, not an absolute value, because two contributions posted in the same
// batch must compose. COALESCE treats a never-set balance as zero, which is
// what "I have just made my first contribution" means.
//
// Manual accounts only. The whole point of the Plaid path is that the
// institution reports the balance; adding to it here would produce a figure the
// next sync silently overwrites.
func (q *Queries) AddToManualAccountBalance(ctx context.Context, arg AddToManualAccountBalanceParams) (decimal.NullDecimal, error) {
	row := q.db.QueryRow(ctx, addToManualAccountBalance, arg.Delta, arg.ID)
	var current_balance decimal.NullDecimal
	err := row.Scan(&current_balance)
	return current_balance, err
}

const createManualAccount = `-- name: CreateManualAccount :one


INSERT INTO accounts (
    source, user_id, household_id, is_shared,
    name, type, subtype, mask, currency, tax_treatment, current_balance
) VALUES (
    'manual',
    $1::uuid, $2::uuid, $3::boolean,
    $4, $5, $6, $7,
    $8, $9, $10
)
RETURNING id, plaid_item_id, plaid_account_id, name, official_name, mask, type, subtype, current_balance, available_balance, credit_limit, currency, is_active, created_at, updated_at, tax_treatment, is_managed, beneficiary_person_id, source, user_id, is_shared, household_id
`

type CreateManualAccountParams struct {
	UserID         uuid.UUID           `json:"user_id"`
	HouseholdID    uuid.UUID           `json:"household_id"`
	IsShared       bool                `json:"is_shared"`
	Name           string              `json:"name"`
	Type           string              `json:"type"`
	Subtype        *string             `json:"subtype"`
	Mask           *string             `json:"mask"`
	Currency       string              `json:"currency"`
	TaxTreatment   *string             `json:"tax_treatment"`
	CurrentBalance decimal.NullDecimal `json:"current_balance"`
}

// Manual accounts, manual securities and holdings, and the balance trail
// behind a manually-maintained balance (doc 30).
//
// Two rules hold throughout this file and are worth stating once:
//
//  1. Every mutation carries `source = 'manual'` in its WHERE clause. That is
//     what makes it impossible to reach a Plaid-linked account through these
//     endpoints even with a valid id — a Plaid account's name, balance and
//     lifecycle belong to the institution, and the only reason these queries
//     can write accounts.current_balance at all is that manual accounts have
//     no institution to disagree with.
//
//  2. Scoping goes through account_access (00053), never through plaid_items.
//     A manual account has no item; reaching for one returns nothing.
//
// --------------------------------------------------------------------------
// Accounts
// --------------------------------------------------------------------------
// The household and owner are taken from the authenticated caller, never from
// the request body, so there is no id here a caller could point at somebody
// else's household.
func (q *Queries) CreateManualAccount(ctx context.Context, arg CreateManualAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createManualAccount,
		arg.UserID,
		arg.HouseholdID,
		arg.IsShared,
		arg.Name,
		arg.Type,
		arg.Subtype,
		arg.Mask,
		arg.Currency,
		arg.TaxTreatment,
		arg.CurrentBalance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PlaidItemID,
		&i.PlaidAccountID,
		&i.Name,
		&i.OfficialName,
		&i.Mask,
		&i.Type,
		&i.Subtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.CreditLimit,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaxTreatment,
		&i.IsManaged,
		&i.BeneficiaryPersonID,
		&i.Source,
		&i.UserID,
		&i.IsShared,
		&i.HouseholdID,
	)
	return i, err
}

const createManualInvestmentTransaction = `-- name: CreateManualInvestmentTransaction :one

INSERT INTO investment_transactions (
    account_id, security_id, source, type, subtype,
    amount, quantity, price, fees, date, name, currency
)
SELECT
    a.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    a.currency
FROM accounts a
JOIN account_access v ON v.account_id = a.id
WHERE a.id = $11
  AND a.source = 'manual'
  AND v.household_id = $12
  AND (v.user_id = $13 OR v.is_shared)
RETURNING id, account_id, security_id, plaid_investment_transaction_id, type, subtype, amount, quantity, price, fees, date, name, currency, raw, created_at, updated_at, source
`

type CreateManualInvestmentTransactionParams struct {
	SecurityID  *uuid.UUID          `json:"security_id"`
	Source      string              `json:"source"`
	Type        string              `json:"type"`
	Subtype     *string             `json:"subtype"`
	Amount      decimal.Decimal     `json:"amount"`
	Quantity    decimal.NullDecimal `json:"quantity"`
	Price       decimal.NullDecimal `json:"price"`
	Fees        decimal.NullDecimal `json:"fees"`
	Date        stdtime.Time        `json:"date"`
	Name        *string             `json:"name"`
	AccountID   uuid.UUID           `json:"account_id"`
	HouseholdID uuid.UUID           `json:"household_id"`
	UserID      uuid.UUID           `json:"user_id"`
}

// --------------------------------------------------------------------------
// Investment transactions
// --------------------------------------------------------------------------
// type/subtype come from the same vocabulary Plaid uses, because
// reporting.IsExternalFlow classifies on them and a value outside that
// vocabulary would be silently excluded from every return figure rather than
// rejected. The handler validates against that list before calling this.
func (q *Queries) CreateManualInvestmentTransaction(ctx context.Context, arg CreateManualInvestmentTransactionParams) (InvestmentTransaction, error) {
	row := q.db.QueryRow(ctx, createManualInvestmentTransaction,
		arg.SecurityID,
		arg.Source,
		arg.Type,
		arg.Subtype,
		arg.Amount,
		arg.Quantity,
		arg.Price,
		arg.Fees,
		arg.Date,
		arg.Name,
		arg.AccountID,
		arg.HouseholdID,
		arg.UserID,
	)
	var i InvestmentTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SecurityID,
		&i.PlaidInvestmentTransactionID,
		&i.Type,
		&i.Subtype,
		&i.Amount,
		&i.Quantity,
		&i.Price,
		&i.Fees,
		&i.Date,
		&i.Name,
		&i.Currency,
		&i.Raw,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
	)
	return i, err
}

const createManualInvestmentTransactionUnscoped = `-- name: CreateManualInvestmentTransactionUnscoped :one
INSERT INTO investment_transactions (
    account_id, security_id, source, type, subtype,
    amount, quantity, price, fees, date, name, currency
)
SELECT
    a.id, $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10,
    a.currency
FROM accounts a
WHERE a.id = $11
  AND a.source = 'manual'
RETURNING id, account_id, security_id, plaid_investment_transaction_id, type, subtype, amount, quantity, price, fees, date, name, currency, raw, created_at, updated_at, source
`

type CreateManualInvestmentTransactionUnscopedParams struct {
	SecurityID *uuid.UUID          `json:"security_id"`
	Source     string              `json:"source"`
	Type       string              `json:"type"`
	Subtype    *string             `json:"subtype"`
	Amount     decimal.Decimal     `json:"amount"`
	Quantity   decimal.NullDecimal `json:"quantity"`
	Price      decimal.NullDecimal `json:"price"`
	Fees       decimal.NullDecimal `json:"fees"`
	Date       stdtime.Time        `json:"date"`
	Name       *string             `json:"name"`
	AccountID  uuid.UUID           `json:"account_id"`
}

// The scheduled-posting worker's variant. It carries no user identity — it is a
// background sweep across every household, like the snapshot jobs — so it has
// no caller to scope against. Safe because the account id does not come from a
// request: it is read from the obligation the worker is already processing,
// which was itself household-scoped when the user set it.
//
// Kept deliberately separate from the scoped version rather than made
// optionally-scoped, so that no request-handling path can ever reach an
// unscoped insert by passing a NULL user.
func (q *Queries) CreateManualInvestmentTransactionUnscoped(ctx context.Context, arg CreateManualInvestmentTransactionUnscopedParams) (InvestmentTransaction, error) {
	row := q.db.QueryRow(ctx, createManualInvestmentTransactionUnscoped,
		arg.SecurityID,
		arg.Source,
		arg.Type,
		arg.Subtype,
		arg.Amount,
		arg.Quantity,
		arg.Price,
		arg.Fees,
		arg.Date,
		arg.Name,
		arg.AccountID,
	)
	var i InvestmentTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SecurityID,
		&i.PlaidInvestmentTransactionID,
		&i.Type,
		&i.Subtype,
		&i.Amount,
		&i.Quantity,
		&i.Price,
		&i.Fees,
		&i.Date,
		&i.Name,
		&i.Currency,
		&i.Raw,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
	)
	return i, err
}

const createManualSecurity = `-- name: CreateManualSecurity :one
INSERT INTO securities (
    source, ticker_key, ticker, name, type, cusip, isin,
    close_price, close_price_as_of, currency, is_cash_equivalent
) VALUES (
    'manual', lower($1::text), $1::text, $2,
    $3, $4, $5,
    $6, $7,
    $8, $9
)
ON CONFLICT (ticker_key) WHERE source = 'manual' DO UPDATE SET
    name              = EXCLUDED.name,
    type              = EXCLUDED.type,
    cusip             = EXCLUDED.cusip,
    isin              = EXCLUDED.isin,
    close_price       = EXCLUDED.close_price,
    close_price_as_of = EXCLUDED.close_price_as_of,
    currency          = EXCLUDED.currency,
    updated_at        = now()
RETURNING id, plaid_security_id, name, ticker, type, cusip, isin, close_price, close_price_as_of, currency, is_cash_equivalent, created_at, updated_at, source, ticker_key
`

type CreateManualSecurityParams struct {
	Ticker           string              `json:"ticker"`
	Name             *string             `json:"name"`
	Type             *string             `json:"type"`
	Cusip            *string             `json:"cusip"`
	Isin             *string             `json:"isin"`
	ClosePrice       decimal.NullDecimal `json:"close_price"`
	ClosePriceAsOf   *stdtime.Time       `json:"close_price_as_of"`
	Currency         string              `json:"currency"`
	IsCashEquivalent bool                `json:"is_cash_equivalent"`
}

// ticker_key is the lowercased ticker and the manual identity key. The partial
// unique index on it means a second attempt at the same ticker conflicts rather
// than creating a duplicate; DO UPDATE refreshes the descriptive fields, which
// is what a user re-entering "VTI" with a better name means.
func (q *Queries) CreateManualSecurity(ctx context.Context, arg CreateManualSecurityParams) (Security, error) {
	row := q.db.QueryRow(ctx, createManualSecurity,
		arg.Ticker,
		arg.Name,
		arg.Type,
		arg.Cusip,
		arg.Isin,
		arg.ClosePrice,
		arg.ClosePriceAsOf,
		arg.Currency,
		arg.IsCashEquivalent,
	)
	var i Security
	err := row.Scan(
		&i.ID,
		&i.PlaidSecurityID,
		&i.Name,
		&i.Ticker,
		&i.Type,
		&i.Cusip,
		&i.Isin,
		&i.ClosePrice,
		&i.ClosePriceAsOf,
		&i.Currency,
		&i.IsCashEquivalent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.TickerKey,
	)
	return i, err
}

const deleteManualAccount = `-- name: DeleteManualAccount :execrows
DELETE FROM accounts a
USING account_access v
WHERE a.id = $1
  AND v.account_id = a.id
  AND a.source = 'manual'
  AND v.household_id = $2
  AND (v.user_id = $3 OR v.is_shared)
`

type DeleteManualAccountParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// Plaid accounts are removed by deleting their item, not here. Cascades take
// the holdings, investment transactions and balance history with it; the
// ordinary transactions posted to it go too, which is the honest outcome —
// they described money in an account that no longer exists.
func (q *Queries) DeleteManualAccount(ctx context.Context, arg DeleteManualAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManualAccount, arg.ID, arg.HouseholdID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteManualHolding = `-- name: DeleteManualHolding :execrows
DELETE FROM holdings h
USING accounts a, account_access v
WHERE h.id = $1
  AND a.id = h.account_id
  AND v.account_id = a.id
  AND a.source = 'manual'
  AND v.household_id = $2
  AND (v.user_id = $3 OR v.is_shared)
`

type DeleteManualHoldingParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// Only positions in a manual account. A Plaid holding deleted here would
// reappear on the next sync anyway, so refusing is the honest answer.
func (q *Queries) DeleteManualHolding(ctx context.Context, arg DeleteManualHoldingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManualHolding, arg.ID, arg.HouseholdID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteManualInvestmentTransaction = `-- name: DeleteManualInvestmentTransaction :execrows
DELETE FROM investment_transactions t
USING accounts a, account_access v
WHERE t.id = $1
  AND a.id = t.account_id
  AND v.account_id = a.id
  AND t.source <> 'plaid'
  AND v.household_id = $2
  AND (v.user_id = $3 OR v.is_shared)
`

type DeleteManualInvestmentTransactionParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// source <> 'plaid' rather than = 'manual': a scheduled contribution the worker
// posted is also the user's to remove, and the obligation that produced it is
// edited separately.
func (q *Queries) DeleteManualInvestmentTransaction(ctx context.Context, arg DeleteManualInvestmentTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManualInvestmentTransaction, arg.ID, arg.HouseholdID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVisibleAccount = `-- name: GetVisibleAccount :one
SELECT a.id, a.plaid_item_id, a.plaid_account_id, a.name, a.official_name, a.mask, a.type, a.subtype, a.current_balance, a.available_balance, a.credit_limit, a.currency, a.is_active, a.created_at, a.updated_at, a.tax_treatment, a.is_managed, a.beneficiary_person_id, a.source, a.user_id, a.is_shared, a.household_id, v.institution_name, v.user_id AS owner_id, v.is_shared AS shared
FROM accounts a
JOIN account_access v ON v.account_id = a.id
WHERE a.id = $1
  AND v.household_id = $2
  AND (v.user_id = $3 OR v.is_shared)
`

type GetVisibleAccountParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type GetVisibleAccountRow struct {
	ID                  uuid.UUID           `json:"id"`
	PlaidItemID         *uuid.UUID          `json:"plaid_item_id"`
	PlaidAccountID      *string             `json:"plaid_account_id"`
	Name                string              `json:"name"`
	OfficialName        *string             `json:"official_name"`
	Mask                *string             `json:"mask"`
	Type                string              `json:"type"`
	Subtype             *string             `json:"subtype"`
	CurrentBalance      decimal.NullDecimal `json:"current_balance"`
	AvailableBalance    decimal.NullDecimal `json:"available_balance"`
	CreditLimit         decimal.NullDecimal `json:"credit_limit"`
	Currency            string              `json:"currency"`
	IsActive            bool                `json:"is_active"`
	CreatedAt           stdtime.Time        `json:"created_at"`
	UpdatedAt           stdtime.Time        `json:"updated_at"`
	TaxTreatment        *string             `json:"tax_treatment"`
	IsManaged           *bool               `json:"is_managed"`
	BeneficiaryPersonID *uuid.UUID          `json:"beneficiary_person_id"`
	Source              string              `json:"source"`
	UserID              *uuid.UUID          `json:"user_id"`
	IsShared            *bool               `json:"is_shared"`
	HouseholdID         *uuid.UUID          `json:"household_id"`
	InstitutionName     *string             `json:"institution_name"`
	OwnerID             uuid.UUID           `json:"owner_id"`
	Shared              bool                `json:"shared"`
}

// One account of either source, resolved through the same predicate as the
// list. Handlers use it to check an id before acting on it.
func (q *Queries) GetVisibleAccount(ctx context.Context, arg GetVisibleAccountParams) (GetVisibleAccountRow, error) {
	row := q.db.QueryRow(ctx, getVisibleAccount, arg.ID, arg.HouseholdID, arg.UserID)
	var i GetVisibleAccountRow
	err := row.Scan(
		&i.ID,
		&i.PlaidItemID,
		&i.PlaidAccountID,
		&i.Name,
		&i.OfficialName,
		&i.Mask,
		&i.Type,
		&i.Subtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.CreditLimit,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaxTreatment,
		&i.IsManaged,
		&i.BeneficiaryPersonID,
		&i.Source,
		&i.UserID,
		&i.IsShared,
		&i.HouseholdID,
		&i.InstitutionName,
		&i.OwnerID,
		&i.Shared,
	)
	return i, err
}

const insertAccountBalanceHistory = `-- name: InsertAccountBalanceHistory :one
INSERT INTO account_balance_history (account_id, as_of, balance, reason, note)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, as_of) DO UPDATE SET
    balance = EXCLUDED.balance,
    reason  = EXCLUDED.reason,
    note    = EXCLUDED.note
RETURNING id, account_id, as_of, balance, reason, note, created_at
`

type InsertAccountBalanceHistoryParams struct {
	AccountID uuid.UUID       `json:"account_id"`
	AsOf      stdtime.Time    `json:"as_of"`
	Balance   decimal.Decimal `json:"balance"`
	Reason    string          `json:"reason"`
	Note      *string         `json:"note"`
}

// The other half. One row per account per day; a second write for the same day
// replaces it rather than failing, so re-running the scheduled worker and a
// user correcting a figure they entered an hour ago behave the same way.
func (q *Queries) InsertAccountBalanceHistory(ctx context.Context, arg InsertAccountBalanceHistoryParams) (AccountBalanceHistory, error) {
	row := q.db.QueryRow(ctx, insertAccountBalanceHistory,
		arg.AccountID,
		arg.AsOf,
		arg.Balance,
		arg.Reason,
		arg.Note,
	)
	var i AccountBalanceHistory
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AsOf,
		&i.Balance,
		&i.Reason,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountBalanceHistory = `-- name: ListAccountBalanceHistory :many
SELECT h.id, h.account_id, h.as_of, h.balance, h.reason, h.note, h.created_at
FROM account_balance_history h
JOIN account_access v ON v.account_id = h.account_id
WHERE h.account_id = $1
  AND v.household_id = $2
  AND (v.user_id = $3 OR v.is_shared)
ORDER BY h.as_of
`

type ListAccountBalanceHistoryParams struct {
	AccountID   uuid.UUID `json:"account_id"`
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// The trend behind one account's current balance. Ascending, because it is
// drawn as a line.
func (q *Queries) ListAccountBalanceHistory(ctx context.Context, arg ListAccountBalanceHistoryParams) ([]AccountBalanceHistory, error) {
	rows, err := q.db.Query(ctx, listAccountBalanceHistory, arg.AccountID, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountBalanceHistory{}
	for rows.Next() {
		var i AccountBalanceHistory
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AsOf,
			&i.Balance,
			&i.Reason,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentTransactionsForAccount = `-- name: ListInvestmentTransactionsForAccount :many
SELECT t.id, t.account_id, t.security_id, t.source, t.type, t.subtype,
       t.amount, t.quantity, t.price, t.fees, t.date, t.name, t.currency,
       s.ticker, s.name AS security_name
FROM investment_transactions t
JOIN accounts a       ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
LEFT JOIN securities s ON s.id = t.security_id
WHERE t.account_id = $1
  AND v.household_id = $2
  AND (v.user_id = $3 OR v.is_shared)
ORDER BY t.date DESC, t.id
`

type ListInvestmentTransactionsForAccountParams struct {
	AccountID   uuid.UUID `json:"account_id"`
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type ListInvestmentTransactionsForAccountRow struct {
	ID           uuid.UUID           `json:"id"`
	AccountID    uuid.UUID           `json:"account_id"`
	SecurityID   *uuid.UUID          `json:"security_id"`
	Source       string              `json:"source"`
	Type         string              `json:"type"`
	Subtype      *string             `json:"subtype"`
	Amount       decimal.Decimal     `json:"amount"`
	Quantity     decimal.NullDecimal `json:"quantity"`
	Price        decimal.NullDecimal `json:"price"`
	Fees         decimal.NullDecimal `json:"fees"`
	Date         stdtime.Time        `json:"date"`
	Name         *string             `json:"name"`
	Currency     string              `json:"currency"`
	Ticker       *string             `json:"ticker"`
	SecurityName *string             `json:"security_name"`
}

// The editor's list view: what has been recorded against one account.
func (q *Queries) ListInvestmentTransactionsForAccount(ctx context.Context, arg ListInvestmentTransactionsForAccountParams) ([]ListInvestmentTransactionsForAccountRow, error) {
	rows, err := q.db.Query(ctx, listInvestmentTransactionsForAccount, arg.AccountID, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvestmentTransactionsForAccountRow{}
	for rows.Next() {
		var i ListInvestmentTransactionsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.SecurityID,
			&i.Source,
			&i.Type,
			&i.Subtype,
			&i.Amount,
			&i.Quantity,
			&i.Price,
			&i.Fees,
			&i.Date,
			&i.Name,
			&i.Currency,
			&i.Ticker,
			&i.SecurityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecurities = `-- name: ListSecurities :many

SELECT id, plaid_security_id, name, ticker, type, cusip, isin,
       close_price, close_price_as_of, currency, is_cash_equivalent, source
FROM securities
WHERE $1::text IS NULL
   OR ticker ILIKE '%' || $1 || '%'
   OR name   ILIKE '%' || $1 || '%'
ORDER BY (ticker IS NULL), ticker, name
LIMIT $2
`

type ListSecuritiesParams struct {
	Search *string `json:"search"`
	Limit  int32   `json:"limit"`
}

type ListSecuritiesRow struct {
	ID               uuid.UUID           `json:"id"`
	PlaidSecurityID  *string             `json:"plaid_security_id"`
	Name             *string             `json:"name"`
	Ticker           *string             `json:"ticker"`
	Type             *string             `json:"type"`
	Cusip            *string             `json:"cusip"`
	Isin             *string             `json:"isin"`
	ClosePrice       decimal.NullDecimal `json:"close_price"`
	ClosePriceAsOf   *stdtime.Time       `json:"close_price_as_of"`
	Currency         string              `json:"currency"`
	IsCashEquivalent bool                `json:"is_cash_equivalent"`
	Source           string              `json:"source"`
}

// --------------------------------------------------------------------------
// Securities
// --------------------------------------------------------------------------
// The security picker's source. Deliberately NOT household-scoped: securities
// are reference data, not household data — a row says "VTI is an ETF called
// Vanguard Total Stock Market", which is true for everyone and reveals nothing
// about who holds it. Holdings are what carry ownership, and those are scoped.
func (q *Queries) ListSecurities(ctx context.Context, arg ListSecuritiesParams) ([]ListSecuritiesRow, error) {
	rows, err := q.db.Query(ctx, listSecurities, arg.Search, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecuritiesRow{}
	for rows.Next() {
		var i ListSecuritiesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlaidSecurityID,
			&i.Name,
			&i.Ticker,
			&i.Type,
			&i.Cusip,
			&i.Isin,
			&i.ClosePrice,
			&i.ClosePriceAsOf,
			&i.Currency,
			&i.IsCashEquivalent,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setManualAccountBalance = `-- name: SetManualAccountBalance :one
UPDATE accounts a
SET current_balance = $1,
    updated_at      = now()
FROM account_access v
WHERE a.id = $2
  AND v.account_id = a.id
  AND a.source = 'manual'
  AND v.household_id = $3
  AND (v.user_id = $4 OR v.is_shared)
RETURNING a.id, a.plaid_item_id, a.plaid_account_id, a.name, a.official_name, a.mask, a.type, a.subtype, a.current_balance, a.available_balance, a.credit_limit, a.currency, a.is_active, a.created_at, a.updated_at, a.tax_treatment, a.is_managed, a.beneficiary_person_id, a.source, a.user_id, a.is_shared, a.household_id
`

type SetManualAccountBalanceParams struct {
	Balance     decimal.NullDecimal `json:"balance"`
	ID          uuid.UUID           `json:"id"`
	HouseholdID uuid.UUID           `json:"household_id"`
	UserID      uuid.UUID           `json:"user_id"`
}

// Half of a balance write. The caller MUST run this in the same transaction as
// InsertAccountBalanceHistory: a failure has to leave neither, or the balance
// every net-worth query reads and the history that is supposed to explain it
// disagree. Same rule as SetManualAssetValue/InsertAssetValuation (00051).
func (q *Queries) SetManualAccountBalance(ctx context.Context, arg SetManualAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, setManualAccountBalance,
		arg.Balance,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PlaidItemID,
		&i.PlaidAccountID,
		&i.Name,
		&i.OfficialName,
		&i.Mask,
		&i.Type,
		&i.Subtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.CreditLimit,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaxTreatment,
		&i.IsManaged,
		&i.BeneficiaryPersonID,
		&i.Source,
		&i.UserID,
		&i.IsShared,
		&i.HouseholdID,
	)
	return i, err
}

const updateManualAccount = `-- name: UpdateManualAccount :one
UPDATE accounts a
SET name          = $1,
    type          = $2,
    subtype       = $3,
    mask          = $4,
    currency      = $5,
    tax_treatment = $6,
    is_shared     = $7::boolean,
    updated_at    = now()
FROM account_access v
WHERE a.id = $8
  AND v.account_id = a.id
  AND a.source = 'manual'
  AND v.household_id = $9
  AND (v.user_id = $10 OR v.is_shared)
RETURNING a.id, a.plaid_item_id, a.plaid_account_id, a.name, a.official_name, a.mask, a.type, a.subtype, a.current_balance, a.available_balance, a.credit_limit, a.currency, a.is_active, a.created_at, a.updated_at, a.tax_treatment, a.is_managed, a.beneficiary_person_id, a.source, a.user_id, a.is_shared, a.household_id
`

type UpdateManualAccountParams struct {
	Name         string    `json:"name"`
	Type         string    `json:"type"`
	Subtype      *string   `json:"subtype"`
	Mask         *string   `json:"mask"`
	Currency     string    `json:"currency"`
	TaxTreatment *string   `json:"tax_treatment"`
	IsShared     bool      `json:"is_shared"`
	ID           uuid.UUID `json:"id"`
	HouseholdID  uuid.UUID `json:"household_id"`
	UserID       uuid.UUID `json:"user_id"`
}

// Balance is deliberately absent: it moves only through SetManualAccountBalance,
// which also writes the history row explaining the move.
func (q *Queries) UpdateManualAccount(ctx context.Context, arg UpdateManualAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateManualAccount,
		arg.Name,
		arg.Type,
		arg.Subtype,
		arg.Mask,
		arg.Currency,
		arg.TaxTreatment,
		arg.IsShared,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PlaidItemID,
		&i.PlaidAccountID,
		&i.Name,
		&i.OfficialName,
		&i.Mask,
		&i.Type,
		&i.Subtype,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.CreditLimit,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaxTreatment,
		&i.IsManaged,
		&i.BeneficiaryPersonID,
		&i.Source,
		&i.UserID,
		&i.IsShared,
		&i.HouseholdID,
	)
	return i, err
}

const upsertManualHolding = `-- name: UpsertManualHolding :one

INSERT INTO holdings (
    account_id, security_id, quantity, cost_basis,
    institution_price, institution_value, currency, as_of
)
SELECT
    a.id,
    $1,
    $2,
    $3,
    $4,
    $2 * COALESCE(
        $4::numeric,
        (SELECT s.close_price FROM securities s WHERE s.id = $1),
        0
    ),
    a.currency,
    $5
FROM accounts a
JOIN account_access v ON v.account_id = a.id
WHERE a.id = $6
  AND a.source = 'manual'
  AND v.household_id = $7
  AND (v.user_id = $8 OR v.is_shared)
ON CONFLICT (account_id, security_id) DO UPDATE SET
    quantity          = EXCLUDED.quantity,
    cost_basis        = EXCLUDED.cost_basis,
    institution_price = EXCLUDED.institution_price,
    institution_value = EXCLUDED.institution_value,
    as_of             = EXCLUDED.as_of,
    updated_at        = now()
RETURNING id, account_id, security_id, quantity, cost_basis, institution_price, institution_value, currency, as_of, created_at, updated_at
`

type UpsertManualHoldingParams struct {
	SecurityID       uuid.UUID           `json:"security_id"`
	Quantity         decimal.Decimal     `json:"quantity"`
	CostBasis        decimal.NullDecimal `json:"cost_basis"`
	InstitutionPrice decimal.NullDecimal `json:"institution_price"`
	AsOf             *stdtime.Time       `json:"as_of"`
	AccountID        uuid.UUID           `json:"account_id"`
	HouseholdID      uuid.UUID           `json:"household_id"`
	UserID           uuid.UUID           `json:"user_id"`
}

// --------------------------------------------------------------------------
// Holdings
// --------------------------------------------------------------------------
// Reuses holdings' existing UNIQUE (account_id, security_id), so entering a
// position twice corrects it rather than double-counting it — the same
// behaviour a re-sync has for a Plaid holding.
//
// institution_value is computed here rather than accepted from the caller:
// quantity × price is arithmetic, and a caller-supplied total that disagreed
// with its own factors would be a silent error in every allocation figure.
func (q *Queries) UpsertManualHolding(ctx context.Context, arg UpsertManualHoldingParams) (Holding, error) {
	row := q.db.QueryRow(ctx, upsertManualHolding,
		arg.SecurityID,
		arg.Quantity,
		arg.CostBasis,
		arg.InstitutionPrice,
		arg.AsOf,
		arg.AccountID,
		arg.HouseholdID,
		arg.UserID,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SecurityID,
		&i.Quantity,
		&i.CostBasis,
		&i.InstitutionPrice,
		&i.InstitutionValue,
		&i.Currency,
		&i.AsOf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
