// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant_logos.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const deleteMerchantLogos = `-- name: DeleteMerchantLogos :exec
DELETE FROM merchant_logos WHERE household_id = $1
`

// Forget everything fetched for a household. Used when the household switches
// the feature off: the cache is derived data about where they shop, and keeping
// it after they said no would be keeping the part they objected to.
func (q *Queries) DeleteMerchantLogos(ctx context.Context, householdID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMerchantLogos, householdID)
	return err
}

const getMerchantLogo = `-- name: GetMerchantLogo :one
SELECT content_type, image
FROM merchant_logos
WHERE household_id = $1 AND merchant_key = $2 AND state = 'found'
`

type GetMerchantLogoParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	MerchantKey string    `json:"merchant_key"`
}

type GetMerchantLogoRow struct {
	ContentType *string `json:"content_type"`
	Image       []byte  `json:"image"`
}

// The bytes for one merchant. Household-scoped in the query rather than in the
// handler: a merchant key is a guessable string, so it must never be on its own
// sufficient to read a row.
func (q *Queries) GetMerchantLogo(ctx context.Context, arg GetMerchantLogoParams) (GetMerchantLogoRow, error) {
	row := q.db.QueryRow(ctx, getMerchantLogo, arg.HouseholdID, arg.MerchantKey)
	var i GetMerchantLogoRow
	err := row.Scan(&i.ContentType, &i.Image)
	return i, err
}

const listMerchantsNeedingLogos = `-- name: ListMerchantsNeedingLogos :many

SELECT
    COALESCE(ma.entity_id::text, t.merchant_key)::text                      AS merchant_key,
    (array_agg(COALESCE(me.canonical_name, t.merchant_name, t.name) ORDER BY t.date DESC))[1]::text AS merchant_name,
    COUNT(*)::bigint                                                        AS transaction_count
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN plaid_items i ON i.id = a.plaid_item_id
JOIN users u       ON u.id = i.user_id
LEFT JOIN merchant_aliases ma
       ON ma.household_id = $1
      AND ma.merchant_key = t.merchant_key
      AND ma.source <> 'suggested'
LEFT JOIN merchant_entities me ON me.id = ma.entity_id
WHERE u.household_id = $1
  AND (i.user_id = $2 OR i.is_shared)
  AND a.is_active
  AND NOT t.pending
  AND t.merchant_key IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM merchant_logos ml
      WHERE ml.household_id = $1
        AND ml.merchant_key = COALESCE(ma.entity_id::text, t.merchant_key)
  )
GROUP BY COALESCE(ma.entity_id::text, t.merchant_key)
ORDER BY COUNT(*) DESC
LIMIT $3
`

type ListMerchantsNeedingLogosParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
	RowLimit    int32     `json:"row_limit"`
}

type ListMerchantsNeedingLogosRow struct {
	MerchantKey      string `json:"merchant_key"`
	MerchantName     string `json:"merchant_name"`
	TransactionCount int64  `json:"transaction_count"`
}

// Merchant logo cache (00050). Read by the api to serve an avatar, written by
// the fetch job. Every key here is a RESOLVED merchant key, per the resolution
// rule documented at the top of merchants.sql.
// Merchants the fetcher has never considered, busiest first.
//
// "Never considered" rather than "has no logo": a row with state 'none' is a
// decision, not a gap, so it must exclude the merchant from this list exactly
// as a 'found' row does. Ordering by transaction count means a household whose
// ledger outruns the per-pass limit gets logos where it will notice them.
//
// Visibility follows the same rule as every other household-wide job query: the
// caller passes uuid.Nil as user_id so only shared items are considered, and a
// private institution's merchants are never resolved on the household's behalf.
func (q *Queries) ListMerchantsNeedingLogos(ctx context.Context, arg ListMerchantsNeedingLogosParams) ([]ListMerchantsNeedingLogosRow, error) {
	rows, err := q.db.Query(ctx, listMerchantsNeedingLogos, arg.HouseholdID, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantsNeedingLogosRow{}
	for rows.Next() {
		var i ListMerchantsNeedingLogosRow
		if err := rows.Scan(&i.MerchantKey, &i.MerchantName, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMerchantLogo = `-- name: UpsertMerchantLogo :exec
INSERT INTO merchant_logos (
    household_id, merchant_key, merchant_name, domain, content_type, image, state, checked_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now()
)
ON CONFLICT (household_id, merchant_key) DO UPDATE SET
    merchant_name = EXCLUDED.merchant_name,
    domain        = EXCLUDED.domain,
    content_type  = EXCLUDED.content_type,
    image         = EXCLUDED.image,
    state         = EXCLUDED.state,
    checked_at    = EXCLUDED.checked_at
`

type UpsertMerchantLogoParams struct {
	HouseholdID  uuid.UUID `json:"household_id"`
	MerchantKey  string    `json:"merchant_key"`
	MerchantName string    `json:"merchant_name"`
	Domain       *string   `json:"domain"`
	ContentType  *string   `json:"content_type"`
	Image        []byte    `json:"image"`
	State        string    `json:"state"`
}

// Record one outcome, found or not. Re-running a pass overwrites rather than
// conflicting, so a future "rescan" only has to delete rows to make them
// eligible again.
func (q *Queries) UpsertMerchantLogo(ctx context.Context, arg UpsertMerchantLogoParams) error {
	_, err := q.db.Exec(ctx, upsertMerchantLogo,
		arg.HouseholdID,
		arg.MerchantKey,
		arg.MerchantName,
		arg.Domain,
		arg.ContentType,
		arg.Image,
		arg.State,
	)
	return err
}
