// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

const createMerchantEntity = `-- name: CreateMerchantEntity :one
INSERT INTO merchant_entities (household_id, canonical_name, default_category_id, color)
VALUES ($1, $2, $3, $4)
RETURNING id, household_id, canonical_name, default_category_id, color, created_at, updated_at
`

type CreateMerchantEntityParams struct {
	HouseholdID       uuid.UUID  `json:"household_id"`
	CanonicalName     string     `json:"canonical_name"`
	DefaultCategoryID *uuid.UUID `json:"default_category_id"`
	Color             *string    `json:"color"`
}

func (q *Queries) CreateMerchantEntity(ctx context.Context, arg CreateMerchantEntityParams) (MerchantEntity, error) {
	row := q.db.QueryRow(ctx, createMerchantEntity,
		arg.HouseholdID,
		arg.CanonicalName,
		arg.DefaultCategoryID,
		arg.Color,
	)
	var i MerchantEntity
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CanonicalName,
		&i.DefaultCategoryID,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmptyMerchantEntities = `-- name: DeleteEmptyMerchantEntities :exec
DELETE FROM merchant_entities e
WHERE e.household_id = $1
  AND NOT EXISTS (SELECT 1 FROM merchant_aliases ma WHERE ma.entity_id = e.id)
`

// An entity with no aliases canonicalises nothing and is retired.
//
// This used to retire entities with fewer than TWO aliases, on the reasoning that
// a single-alias entity is just the raw key wearing a hat. That stopped being
// true once the import path started normalising descriptors through
// plaid.MerchantKey: a business whose every descriptor collapses to one key --
// twenty-odd AMAZON MKTPL*<order id> rows becoming a single "amazon mktpl" --
// legitimately has one alias and a name the user chose. Deleting it would drop
// that name and send every report back through COALESCE to the raw descriptor,
// so "Amazon Marketplace" would redisplay as "AMAZON MKTPL*3842D24Q3".
//
// A one-alias entity is therefore a rename, which is real user intent, and only a
// zero-alias one is genuinely empty.
func (q *Queries) DeleteEmptyMerchantEntities(ctx context.Context, householdID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmptyMerchantEntities, householdID)
	return err
}

const deleteMerchantAlias = `-- name: DeleteMerchantAlias :exec
DELETE FROM merchant_aliases WHERE household_id = $1 AND merchant_key = $2
`

type DeleteMerchantAliasParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	MerchantKey string    `json:"merchant_key"`
}

func (q *Queries) DeleteMerchantAlias(ctx context.Context, arg DeleteMerchantAliasParams) error {
	_, err := q.db.Exec(ctx, deleteMerchantAlias, arg.HouseholdID, arg.MerchantKey)
	return err
}

const deleteMerchantEntity = `-- name: DeleteMerchantEntity :exec
DELETE FROM merchant_entities WHERE id = $1 AND household_id = $2
`

type DeleteMerchantEntityParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) DeleteMerchantEntity(ctx context.Context, arg DeleteMerchantEntityParams) error {
	_, err := q.db.Exec(ctx, deleteMerchantEntity, arg.ID, arg.HouseholdID)
	return err
}

const deleteSuggestedAliases = `-- name: DeleteSuggestedAliases :exec
DELETE FROM merchant_aliases
WHERE household_id = $1 AND source = 'suggested'
`

// Clears a household's whole pending queue, so a suggestion pass rebuilds it from
// scratch rather than adding to it.
//
// Without this, a pass could only ever ADD, and a proposal made by an older
// version of the matching rules would outlive the rules that produced it: the
// fixes that stopped HOMEGOODS being read as THE HOME DEPOT would never reach the
// proposal already sitting in the queue saying it was. Suggestions are inert by
// construction — no report counts them until a person confirms one — so throwing
// them away and re-deriving costs nothing but the pass itself.
//
// Confirmed aliases are untouched: source <> 'suggested' is the line between a
// guess and a decision, and only guesses are disposable.
func (q *Queries) DeleteSuggestedAliases(ctx context.Context, householdID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSuggestedAliases, householdID)
	return err
}

const deleteSuggestedAliasesForEntity = `-- name: DeleteSuggestedAliasesForEntity :exec
DELETE FROM merchant_aliases
WHERE household_id = $1 AND entity_id = $2 AND source = 'suggested'
`

type DeleteSuggestedAliasesForEntityParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	EntityID    uuid.UUID `json:"entity_id"`
}

func (q *Queries) DeleteSuggestedAliasesForEntity(ctx context.Context, arg DeleteSuggestedAliasesForEntityParams) error {
	_, err := q.db.Exec(ctx, deleteSuggestedAliasesForEntity, arg.HouseholdID, arg.EntityID)
	return err
}

const findMerchantEntityByName = `-- name: FindMerchantEntityByName :one
SELECT id, household_id, canonical_name, default_category_id, color, created_at, updated_at FROM merchant_entities
WHERE household_id = $1 AND lower(canonical_name) = lower($2::text)
`

type FindMerchantEntityByNameParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Name        string    `json:"name"`
}

func (q *Queries) FindMerchantEntityByName(ctx context.Context, arg FindMerchantEntityByNameParams) (MerchantEntity, error) {
	row := q.db.QueryRow(ctx, findMerchantEntityByName, arg.HouseholdID, arg.Name)
	var i MerchantEntity
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CanonicalName,
		&i.DefaultCategoryID,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantAliasByKey = `-- name: GetMerchantAliasByKey :one
SELECT ma.merchant_key, ma.entity_id, ma.source, e.canonical_name
FROM merchant_aliases ma
JOIN merchant_entities e ON e.id = ma.entity_id
WHERE ma.household_id = $1 AND ma.merchant_key = $2
`

type GetMerchantAliasByKeyParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	MerchantKey string    `json:"merchant_key"`
}

type GetMerchantAliasByKeyRow struct {
	MerchantKey   string    `json:"merchant_key"`
	EntityID      uuid.UUID `json:"entity_id"`
	Source        string    `json:"source"`
	CanonicalName string    `json:"canonical_name"`
}

// One alias by descriptor. Used by the split path, which has a key and needs the
// merchant it currently belongs to.
func (q *Queries) GetMerchantAliasByKey(ctx context.Context, arg GetMerchantAliasByKeyParams) (GetMerchantAliasByKeyRow, error) {
	row := q.db.QueryRow(ctx, getMerchantAliasByKey, arg.HouseholdID, arg.MerchantKey)
	var i GetMerchantAliasByKeyRow
	err := row.Scan(
		&i.MerchantKey,
		&i.EntityID,
		&i.Source,
		&i.CanonicalName,
	)
	return i, err
}

const getMerchantEntity = `-- name: GetMerchantEntity :one
SELECT id, household_id, canonical_name, default_category_id, color, created_at, updated_at FROM merchant_entities WHERE id = $1 AND household_id = $2
`

type GetMerchantEntityParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetMerchantEntity(ctx context.Context, arg GetMerchantEntityParams) (MerchantEntity, error) {
	row := q.db.QueryRow(ctx, getMerchantEntity, arg.ID, arg.HouseholdID)
	var i MerchantEntity
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CanonicalName,
		&i.DefaultCategoryID,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMerchantAliasStats = `-- name: ListMerchantAliasStats :many
WITH stats AS (
    SELECT
        t.merchant_key,
        COUNT(*)::bigint                    AS transaction_count,
        COALESCE(SUM(t.amount), 0)::numeric AS total_amount,
        MIN(t.date)::date                   AS first_seen,
        MAX(t.date)::date                   AS last_seen,
        (array_agg(COALESCE(t.merchant_name, t.name) ORDER BY t.date DESC))[1] AS sample_name
    FROM transactions t
    JOIN accounts a    ON a.id = t.account_id
    JOIN account_access v ON v.account_id = a.id
    WHERE v.household_id = $1
      AND (v.user_id = $2 OR v.is_shared)
      AND a.is_active
      AND NOT t.pending
      AND t.merchant_key IS NOT NULL
    GROUP BY t.merchant_key
)
SELECT
    e.id                                          AS entity_id,
    e.canonical_name,
    e.default_category_id,
    e.color,
    ma.merchant_key,
    ma.source,
    ma.confidence,
    COALESCE(s.transaction_count, 0)::bigint      AS transaction_count,
    COALESCE(s.total_amount, 0)::numeric          AS total_amount,
    s.first_seen,
    s.last_seen,
    COALESCE(s.sample_name, ma.merchant_key)::text AS sample_name
FROM merchant_aliases ma
JOIN merchant_entities e ON e.id = ma.entity_id
LEFT JOIN stats s ON s.merchant_key = ma.merchant_key
WHERE ma.household_id = $1
ORDER BY e.canonical_name, e.id, ma.source, ma.merchant_key
`

type ListMerchantAliasStatsParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type ListMerchantAliasStatsRow struct {
	EntityID          uuid.UUID           `json:"entity_id"`
	CanonicalName     string              `json:"canonical_name"`
	DefaultCategoryID *uuid.UUID          `json:"default_category_id"`
	Color             *string             `json:"color"`
	MerchantKey       string              `json:"merchant_key"`
	Source            string              `json:"source"`
	Confidence        decimal.NullDecimal `json:"confidence"`
	TransactionCount  int64               `json:"transaction_count"`
	TotalAmount       decimal.Decimal     `json:"total_amount"`
	FirstSeen         *stdtime.Time       `json:"first_seen"`
	LastSeen          *stdtime.Time       `json:"last_seen"`
	SampleName        string              `json:"sample_name"`
}

// Every alias row in the household, joined to its entity and to the same
// evidence ListMerchantKeyStats reports. One query serves two surfaces: rows
// whose entity has any 'suggested' alias are the review queue; the rest are the
// confirmed merchant list. Grouping is done by the caller.
func (q *Queries) ListMerchantAliasStats(ctx context.Context, arg ListMerchantAliasStatsParams) ([]ListMerchantAliasStatsRow, error) {
	rows, err := q.db.Query(ctx, listMerchantAliasStats, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantAliasStatsRow{}
	for rows.Next() {
		var i ListMerchantAliasStatsRow
		if err := rows.Scan(
			&i.EntityID,
			&i.CanonicalName,
			&i.DefaultCategoryID,
			&i.Color,
			&i.MerchantKey,
			&i.Source,
			&i.Confidence,
			&i.TransactionCount,
			&i.TotalAmount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.SampleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantAliases = `-- name: ListMerchantAliases :many
SELECT merchant_key, source, confidence
FROM merchant_aliases
WHERE household_id = $1 AND entity_id = $2
ORDER BY source, merchant_key
`

type ListMerchantAliasesParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	EntityID    uuid.UUID `json:"entity_id"`
}

type ListMerchantAliasesRow struct {
	MerchantKey string              `json:"merchant_key"`
	Source      string              `json:"source"`
	Confidence  decimal.NullDecimal `json:"confidence"`
}

func (q *Queries) ListMerchantAliases(ctx context.Context, arg ListMerchantAliasesParams) ([]ListMerchantAliasesRow, error) {
	rows, err := q.db.Query(ctx, listMerchantAliases, arg.HouseholdID, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantAliasesRow{}
	for rows.Next() {
		var i ListMerchantAliasesRow
		if err := rows.Scan(&i.MerchantKey, &i.Source, &i.Confidence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantCategoryMappingsForKeys = `-- name: ListMerchantCategoryMappingsForKeys :many
SELECT merchant_key, category_id, source, updated_at
FROM merchant_category_map
WHERE household_id = $1 AND merchant_key = ANY($2::text[])
`

type ListMerchantCategoryMappingsForKeysParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Column2     []string  `json:"column_2"`
}

type ListMerchantCategoryMappingsForKeysRow struct {
	MerchantKey string       `json:"merchant_key"`
	CategoryID  uuid.UUID    `json:"category_id"`
	Source      string       `json:"source"`
	UpdatedAt   stdtime.Time `json:"updated_at"`
}

// The cached category decisions for a set of merchant_keys, so a merge can
// reconcile them. `source` is what decides the winner: a manual mapping outranks
// everything, per the app's "a manual category is sticky" rule.
func (q *Queries) ListMerchantCategoryMappingsForKeys(ctx context.Context, arg ListMerchantCategoryMappingsForKeysParams) ([]ListMerchantCategoryMappingsForKeysRow, error) {
	rows, err := q.db.Query(ctx, listMerchantCategoryMappingsForKeys, arg.HouseholdID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantCategoryMappingsForKeysRow{}
	for rows.Next() {
		var i ListMerchantCategoryMappingsForKeysRow
		if err := rows.Scan(
			&i.MerchantKey,
			&i.CategoryID,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantKeyStats = `-- name: ListMerchantKeyStats :many

SELECT
    t.merchant_key::text                                                   AS merchant_key,
    COUNT(*)::bigint                                                       AS transaction_count,
    COALESCE(SUM(t.amount), 0)::numeric                                    AS total_amount,
    MIN(t.date)::date                                                      AS first_seen,
    MAX(t.date)::date                                                      AS last_seen,
    (array_agg(COALESCE(t.merchant_name, t.name) ORDER BY t.date DESC))[1]::text AS sample_name,
    ma.entity_id,
    COALESCE(ma.source, '')::text                                          AS alias_source
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
LEFT JOIN merchant_aliases ma
       ON ma.household_id = $1
      AND ma.merchant_key = t.merchant_key
WHERE v.household_id = $1
  AND (v.user_id = $2 OR v.is_shared)
  AND a.is_active
  AND NOT t.pending
  AND t.merchant_key IS NOT NULL
GROUP BY t.merchant_key, ma.entity_id, ma.source
ORDER BY COUNT(*) DESC, t.merchant_key
`

type ListMerchantKeyStatsParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type ListMerchantKeyStatsRow struct {
	MerchantKey      string          `json:"merchant_key"`
	TransactionCount int64           `json:"transaction_count"`
	TotalAmount      decimal.Decimal `json:"total_amount"`
	FirstSeen        stdtime.Time    `json:"first_seen"`
	LastSeen         stdtime.Time    `json:"last_seen"`
	SampleName       string          `json:"sample_name"`
	EntityID         *uuid.UUID      `json:"entity_id"`
	AliasSource      string          `json:"alias_source"`
}

// Canonical merchants: entities, the aliases that map raw merchant_keys onto
// them, and the rejection memory that keeps the review queue from refilling
// with merges the user already said no to.
//
// THE RESOLUTION RULE, used verbatim by every report that groups by merchant:
//
//	LEFT JOIN merchant_aliases ma
//	       ON ma.household_id = <household>
//	      AND ma.merchant_key = t.merchant_key
//	      AND ma.source <> 'suggested'
//	LEFT JOIN merchant_entities me ON me.id = ma.entity_id
//
//	resolved key  = COALESCE(ma.entity_id::text, t.merchant_key)
//	display name  = COALESCE(me.canonical_name, t.merchant_name, t.name)
//
// Two properties make this safe to sprinkle across the reporting layer:
//
//  1. A household with no aliases resolves every key to itself and every name
//     the way it did before this feature existed. The feature is additive.
//  2. Resolution is idempotent. A merged merchant's resolved key is an entity
//     UUID rendered as text, and no alias is ever keyed by a UUID, so
//     resolve(resolve(k)) = resolve(k). That is what lets a stored
//     recurring_overrides row or a promoted obligation hold *either* a raw key
//     or a resolved one and still match — including rows written before a
//     merge happened.
//
// The `source <> 'suggested'` predicate is load-bearing: suggested aliases are
// pending review and must not move a single number in any report.
// Every distinct merchant_key the household can see, with the evidence a person
// needs to judge a merge (how often, how much, over what span, and what the
// descriptor actually looked like) and its current alias state. Feeds both the
// suggestion engine and the review UI.
//
// Deliberately unfiltered by category or excluded_from_reports: this is a view
// of the raw descriptor space, not a spending report. Pending rows are excluded
// because a pending descriptor is often rewritten when it posts.
func (q *Queries) ListMerchantKeyStats(ctx context.Context, arg ListMerchantKeyStatsParams) ([]ListMerchantKeyStatsRow, error) {
	rows, err := q.db.Query(ctx, listMerchantKeyStats, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantKeyStatsRow{}
	for rows.Next() {
		var i ListMerchantKeyStatsRow
		if err := rows.Scan(
			&i.MerchantKey,
			&i.TransactionCount,
			&i.TotalAmount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.SampleName,
			&i.EntityID,
			&i.AliasSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMergeRejections = `-- name: ListMergeRejections :many
SELECT key_a, key_b FROM merchant_merge_rejections WHERE household_id = $1
`

type ListMergeRejectionsRow struct {
	KeyA string `json:"key_a"`
	KeyB string `json:"key_b"`
}

func (q *Queries) ListMergeRejections(ctx context.Context, householdID uuid.UUID) ([]ListMergeRejectionsRow, error) {
	rows, err := q.db.Query(ctx, listMergeRejections, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMergeRejectionsRow{}
	for rows.Next() {
		var i ListMergeRejectionsRow
		if err := rows.Scan(&i.KeyA, &i.KeyB); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuggestedAliasKeys = `-- name: ListSuggestedAliasKeys :many
SELECT merchant_key FROM merchant_aliases
WHERE household_id = $1 AND source = 'suggested'
ORDER BY merchant_key
`

func (q *Queries) ListSuggestedAliasKeys(ctx context.Context, householdID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listSuggestedAliasKeys, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var merchant_key string
		if err := rows.Scan(&merchant_key); err != nil {
			return nil, err
		}
		items = append(items, merchant_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteSuggestedAlias = `-- name: PromoteSuggestedAlias :one
UPDATE merchant_aliases
SET source = 'manual', confidence = NULL
WHERE household_id = $1 AND merchant_key = $2 AND source = 'suggested'
RETURNING id, household_id, entity_id, merchant_key, source, confidence, created_at
`

type PromoteSuggestedAliasParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	MerchantKey string    `json:"merchant_key"`
}

// Confirming a suggestion. Scoped to source = 'suggested' so a confirm can never
// rewrite an alias the user already established by hand.
func (q *Queries) PromoteSuggestedAlias(ctx context.Context, arg PromoteSuggestedAliasParams) (MerchantAlias, error) {
	row := q.db.QueryRow(ctx, promoteSuggestedAlias, arg.HouseholdID, arg.MerchantKey)
	var i MerchantAlias
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.EntityID,
		&i.MerchantKey,
		&i.Source,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const recordMergeRejection = `-- name: RecordMergeRejection :exec
INSERT INTO merchant_merge_rejections (household_id, key_a, key_b)
VALUES ($1, $2, $3)
ON CONFLICT (household_id, key_a, key_b) DO NOTHING
`

type RecordMergeRejectionParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	KeyA        string    `json:"key_a"`
	KeyB        string    `json:"key_b"`
}

// Remembers that these two keys are NOT the same business. The engine consults
// this before proposing anything, so a rejected pair is proposed exactly once.
// Keys arrive pre-ordered (key_a < key_b) so a pair has one representation.
func (q *Queries) RecordMergeRejection(ctx context.Context, arg RecordMergeRejectionParams) error {
	_, err := q.db.Exec(ctx, recordMergeRejection, arg.HouseholdID, arg.KeyA, arg.KeyB)
	return err
}

const renameMerchantEntity = `-- name: RenameMerchantEntity :one
UPDATE merchant_entities
SET canonical_name = $3, updated_at = now()
WHERE id = $1 AND household_id = $2
RETURNING id, household_id, canonical_name, default_category_id, color, created_at, updated_at
`

type RenameMerchantEntityParams struct {
	ID            uuid.UUID `json:"id"`
	HouseholdID   uuid.UUID `json:"household_id"`
	CanonicalName string    `json:"canonical_name"`
}

func (q *Queries) RenameMerchantEntity(ctx context.Context, arg RenameMerchantEntityParams) (MerchantEntity, error) {
	row := q.db.QueryRow(ctx, renameMerchantEntity, arg.ID, arg.HouseholdID, arg.CanonicalName)
	var i MerchantEntity
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CanonicalName,
		&i.DefaultCategoryID,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setMerchantEntityDefaultCategory = `-- name: SetMerchantEntityDefaultCategory :exec
UPDATE merchant_entities
SET default_category_id = $3, updated_at = now()
WHERE id = $1 AND household_id = $2
`

type SetMerchantEntityDefaultCategoryParams struct {
	ID                uuid.UUID  `json:"id"`
	HouseholdID       uuid.UUID  `json:"household_id"`
	DefaultCategoryID *uuid.UUID `json:"default_category_id"`
}

func (q *Queries) SetMerchantEntityDefaultCategory(ctx context.Context, arg SetMerchantEntityDefaultCategoryParams) error {
	_, err := q.db.Exec(ctx, setMerchantEntityDefaultCategory, arg.ID, arg.HouseholdID, arg.DefaultCategoryID)
	return err
}

const upsertMerchantAlias = `-- name: UpsertMerchantAlias :one
INSERT INTO merchant_aliases (household_id, entity_id, merchant_key, source, confidence)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (household_id, merchant_key) DO UPDATE SET
    entity_id  = EXCLUDED.entity_id,
    source     = EXCLUDED.source,
    confidence = EXCLUDED.confidence
RETURNING id, household_id, entity_id, merchant_key, source, confidence, created_at
`

type UpsertMerchantAliasParams struct {
	HouseholdID uuid.UUID           `json:"household_id"`
	EntityID    uuid.UUID           `json:"entity_id"`
	MerchantKey string              `json:"merchant_key"`
	Source      string              `json:"source"`
	Confidence  decimal.NullDecimal `json:"confidence"`
}

// Claims a merchant_key for an entity. The unique constraint on
// (household_id, merchant_key) is what stops a key belonging to two entities;
// this re-points it instead of failing, which is how confirming a suggestion
// and moving a key between entities both work.
func (q *Queries) UpsertMerchantAlias(ctx context.Context, arg UpsertMerchantAliasParams) (MerchantAlias, error) {
	row := q.db.QueryRow(ctx, upsertMerchantAlias,
		arg.HouseholdID,
		arg.EntityID,
		arg.MerchantKey,
		arg.Source,
		arg.Confidence,
	)
	var i MerchantAlias
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.EntityID,
		&i.MerchantKey,
		&i.Source,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}
