// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

type Account struct {
	ID                  uuid.UUID           `json:"id"`
	PlaidItemID         *uuid.UUID          `json:"plaid_item_id"`
	PlaidAccountID      *string             `json:"plaid_account_id"`
	Name                string              `json:"name"`
	OfficialName        *string             `json:"official_name"`
	Mask                *string             `json:"mask"`
	Type                string              `json:"type"`
	Subtype             *string             `json:"subtype"`
	CurrentBalance      decimal.NullDecimal `json:"current_balance"`
	AvailableBalance    decimal.NullDecimal `json:"available_balance"`
	CreditLimit         decimal.NullDecimal `json:"credit_limit"`
	Currency            string              `json:"currency"`
	IsActive            bool                `json:"is_active"`
	CreatedAt           stdtime.Time        `json:"created_at"`
	UpdatedAt           stdtime.Time        `json:"updated_at"`
	TaxTreatment        *string             `json:"tax_treatment"`
	IsManaged           *bool               `json:"is_managed"`
	BeneficiaryPersonID *uuid.UUID          `json:"beneficiary_person_id"`
	// plaid — identity and balance owned by the institution. manual — owned by the user; balance writes go through account_balance_history.
	Source      string     `json:"source"`
	UserID      *uuid.UUID `json:"user_id"`
	IsShared    *bool      `json:"is_shared"`
	HouseholdID *uuid.UUID `json:"household_id"`
	// User-entered deposit yield as a PERCENT (4.50 = 4.50%). NULL = unknown, never zero.
	DepositApy decimal.NullDecimal `json:"deposit_apy"`
}

// Visibility resolution for accounts of either source. Join this rather than reaching through plaid_items; a manual account has no item.
type AccountAccess struct {
	AccountID       uuid.UUID `json:"account_id"`
	HouseholdID     uuid.UUID `json:"household_id"`
	UserID          uuid.UUID `json:"user_id"`
	IsShared        bool      `json:"is_shared"`
	InstitutionName *string   `json:"institution_name"`
}

type AccountBalanceHistory struct {
	ID        uuid.UUID       `json:"id"`
	AccountID uuid.UUID       `json:"account_id"`
	AsOf      stdtime.Time    `json:"as_of"`
	Balance   decimal.Decimal `json:"balance"`
	Reason    string          `json:"reason"`
	Note      *string         `json:"note"`
	CreatedAt stdtime.Time    `json:"created_at"`
}

type AccountContribution struct {
	ID                  uuid.UUID           `json:"id"`
	AccountID           uuid.UUID           `json:"account_id"`
	MonthlyContribution decimal.Decimal     `json:"monthly_contribution"`
	EmployerMatchPct    decimal.NullDecimal `json:"employer_match_pct"`
	AnnualSalary        decimal.NullDecimal `json:"annual_salary"`
	EmployerMatchLimit  decimal.NullDecimal `json:"employer_match_limit"`
	// DEPRECATED: prefer accounts.beneficiary_person_id -> birthdate.
	BeneficiaryCurrentAge *int32       `json:"beneficiary_current_age"`
	BeneficiaryTargetAge  *int32       `json:"beneficiary_target_age"`
	UpdatedAt             stdtime.Time `json:"updated_at"`
	// This account's assumed REAL annual return as a fraction (0.06 = 6%), used by the retirement and college projections in place of the household real_return_rate. NULL means use the household rate. Stored REAL (inflation-adjusted) to match every other rate in the app — the drawdown and projection both work in today's dollars.
	AssumedRealReturn decimal.NullDecimal `json:"assumed_real_return"`
}

type AccountTerm struct {
	AccountID           uuid.UUID           `json:"account_id"`
	Apr                 decimal.NullDecimal `json:"apr"`
	MinimumPayment      decimal.NullDecimal `json:"minimum_payment"`
	PaymentObligationID *uuid.UUID          `json:"payment_obligation_id"`
	UpdatedBy           *uuid.UUID          `json:"updated_by"`
	CreatedAt           stdtime.Time        `json:"created_at"`
	UpdatedAt           stdtime.Time        `json:"updated_at"`
}

type AdvisorActionItem struct {
	ID          uuid.UUID     `json:"id"`
	HouseholdID uuid.UUID     `json:"household_id"`
	Title       string        `json:"title"`
	Detail      *string       `json:"detail"`
	Source      string        `json:"source"`
	Status      string        `json:"status"`
	DueDate     *stdtime.Time `json:"due_date"`
	CreatedAt   stdtime.Time  `json:"created_at"`
	CompletedAt *stdtime.Time `json:"completed_at"`
}

type AdvisorMessage struct {
	ID        uuid.UUID    `json:"id"`
	ThreadID  uuid.UUID    `json:"thread_id"`
	Role      string       `json:"role"`
	Content   []byte       `json:"content"`
	ToolTrace []byte       `json:"tool_trace"`
	CreatedAt stdtime.Time `json:"created_at"`
}

type AdvisorThread struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	UserID      *uuid.UUID   `json:"user_id"`
	Title       string       `json:"title"`
	IsShared    bool         `json:"is_shared"`
	CreatedAt   stdtime.Time `json:"created_at"`
	UpdatedAt   stdtime.Time `json:"updated_at"`
}

type Alert struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	Type        string       `json:"type"`
	Config      []byte       `json:"config"`
	Enabled     bool         `json:"enabled"`
	CreatedAt   stdtime.Time `json:"created_at"`
	UpdatedAt   stdtime.Time `json:"updated_at"`
	Push        bool         `json:"push"`
}

type AlertEvent struct {
	ID            uuid.UUID     `json:"id"`
	AlertID       uuid.UUID     `json:"alert_id"`
	TransactionID *uuid.UUID    `json:"transaction_id"`
	TriggeredAt   stdtime.Time  `json:"triggered_at"`
	Payload       []byte        `json:"payload"`
	ReadAt        *stdtime.Time `json:"read_at"`
	NotifiedAt    *stdtime.Time `json:"notified_at"`
}

type AllocationPlan struct {
	ID           uuid.UUID    `json:"id"`
	HouseholdID  uuid.UUID    `json:"household_id"`
	CreatedBy    *uuid.UUID   `json:"created_by"`
	Name         string       `json:"name"`
	Inputs       []byte       `json:"inputs"`
	InputVersion int32        `json:"input_version"`
	Assumptions  []byte       `json:"assumptions"`
	CreatedAt    stdtime.Time `json:"created_at"`
	UpdatedAt    stdtime.Time `json:"updated_at"`
}

type Allowance struct {
	ID            uuid.UUID           `json:"id"`
	PersonID      uuid.UUID           `json:"person_id"`
	Amount        decimal.NullDecimal `json:"amount"`
	Cadence       *string             `json:"cadence"`
	MonthlyLimit  decimal.NullDecimal `json:"monthly_limit"`
	AutoPost      bool                `json:"auto_post"`
	LastPostedFor *stdtime.Time       `json:"last_posted_for"`
	CreatedAt     stdtime.Time        `json:"created_at"`
	UpdatedAt     stdtime.Time        `json:"updated_at"`
}

type AllowanceEntry struct {
	ID         uuid.UUID       `json:"id"`
	PersonID   uuid.UUID       `json:"person_id"`
	Kind       string          `json:"kind"`
	Amount     decimal.Decimal `json:"amount"`
	OccurredOn stdtime.Time    `json:"occurred_on"`
	Note       *string         `json:"note"`
	CreatedBy  *uuid.UUID      `json:"created_by"`
	CreatedAt  stdtime.Time    `json:"created_at"`
}

type AnomalyOverride struct {
	ID            uuid.UUID    `json:"id"`
	HouseholdID   uuid.UUID    `json:"household_id"`
	MerchantKey   string       `json:"merchant_key"`
	MerchantLabel string       `json:"merchant_label"`
	Scope         string       `json:"scope"`
	CreatedAt     stdtime.Time `json:"created_at"`
}

type ApiToken struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	Name       string        `json:"name"`
	TokenHash  string        `json:"token_hash"`
	Scopes     []string      `json:"scopes"`
	LastUsedAt *stdtime.Time `json:"last_used_at"`
	ExpiresAt  *stdtime.Time `json:"expires_at"`
	CreatedAt  stdtime.Time  `json:"created_at"`
}

type AssetDetail struct {
	ID            uuid.UUID           `json:"id"`
	ManualAssetID uuid.UUID           `json:"manual_asset_id"`
	Address       *string             `json:"address"`
	Beds          decimal.NullDecimal `json:"beds"`
	Baths         decimal.NullDecimal `json:"baths"`
	Sqft          *int32              `json:"sqft"`
	LotSqft       *int32              `json:"lot_sqft"`
	Year          *int32              `json:"year"`
	Make          *string             `json:"make"`
	Model         *string             `json:"model"`
	Trim          *string             `json:"trim"`
	Mileage       *int32              `json:"mileage"`
	AnnualMileage *int32              `json:"annual_mileage"`
	BondSeries    *string             `json:"bond_series"`
	IssueDate     *stdtime.Time       `json:"issue_date"`
	PurchasePrice decimal.NullDecimal `json:"purchase_price"`
	FaceValue     decimal.NullDecimal `json:"face_value"`
	CouponRate    decimal.NullDecimal `json:"coupon_rate"`
	MaturityDate  *stdtime.Time       `json:"maturity_date"`
	TaxExempt     *bool               `json:"tax_exempt"`
	Condition     *string             `json:"condition"`
	CreatedAt     stdtime.Time        `json:"created_at"`
	UpdatedAt     stdtime.Time        `json:"updated_at"`
}

type AssetPrice struct {
	ID        uuid.UUID       `json:"id"`
	Ticker    string          `json:"ticker"`
	AsOf      stdtime.Time    `json:"as_of"`
	Close     decimal.Decimal `json:"close"`
	CreatedAt stdtime.Time    `json:"created_at"`
}

type AssetValuation struct {
	ID            uuid.UUID       `json:"id"`
	ManualAssetID uuid.UUID       `json:"manual_asset_id"`
	Value         decimal.Decimal `json:"value"`
	AsOf          stdtime.Time    `json:"as_of"`
	Source        string          `json:"source"`
	Note          *string         `json:"note"`
	CreatedAt     stdtime.Time    `json:"created_at"`
}

type AuthEvent struct {
	ID             uuid.UUID    `json:"id"`
	UserID         *uuid.UUID   `json:"user_id"`
	EmailAttempted *string      `json:"email_attempted"`
	EventType      string       `json:"event_type"`
	ClientIp       *string      `json:"client_ip"`
	UserAgent      *string      `json:"user_agent"`
	Metadata       []byte       `json:"metadata"`
	CreatedAt      stdtime.Time `json:"created_at"`
}

type BackupRun struct {
	ID           uuid.UUID    `json:"id"`
	Kind         string       `json:"kind"`
	Status       string       `json:"status"`
	StartedAt    stdtime.Time `json:"started_at"`
	FinishedAt   stdtime.Time `json:"finished_at"`
	SizeBytes    *int64       `json:"size_bytes"`
	Destination  *string      `json:"destination"`
	ArtifactPath *string      `json:"artifact_path"`
	Detail       *string      `json:"detail"`
	CreatedAt    stdtime.Time `json:"created_at"`
}

type Budget struct {
	ID            uuid.UUID       `json:"id"`
	HouseholdID   uuid.UUID       `json:"household_id"`
	CategoryID    uuid.UUID       `json:"category_id"`
	OwnerScope    string          `json:"owner_scope"`
	UserID        *uuid.UUID      `json:"user_id"`
	Period        string          `json:"period"`
	Amount        decimal.Decimal `json:"amount"`
	EffectiveFrom *stdtime.Time   `json:"effective_from"`
	CreatedAt     stdtime.Time    `json:"created_at"`
	UpdatedAt     stdtime.Time    `json:"updated_at"`
	Rollover      bool            `json:"rollover"`
}

type Category struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID *uuid.UUID   `json:"household_id"`
	ParentID    *uuid.UUID   `json:"parent_id"`
	Name        string       `json:"name"`
	Slug        string       `json:"slug"`
	Icon        *string      `json:"icon"`
	Color       *string      `json:"color"`
	IsFixed     bool         `json:"is_fixed"`
	IsIncome    bool         `json:"is_income"`
	IsTransfer  bool         `json:"is_transfer"`
	SortOrder   int32        `json:"sort_order"`
	CreatedAt   stdtime.Time `json:"created_at"`
	UpdatedAt   stdtime.Time `json:"updated_at"`
}

type CategoryRule struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	MatchType   string       `json:"match_type"`
	Pattern     string       `json:"pattern"`
	CategoryID  uuid.UUID    `json:"category_id"`
	Priority    int32        `json:"priority"`
	Enabled     bool         `json:"enabled"`
	CreatedAt   stdtime.Time `json:"created_at"`
	UpdatedAt   stdtime.Time `json:"updated_at"`
}

// CPI-U, U.S. city average, all items, NSA (BLS CUUR0000SA0). 1982-84 = 100.
type CpiSeries struct {
	ID         uuid.UUID       `json:"id"`
	Period     stdtime.Time    `json:"period"`
	IndexValue decimal.Decimal `json:"index_value"`
	CreatedAt  stdtime.Time    `json:"created_at"`
}

type DigestDelivery struct {
	UserID    uuid.UUID    `json:"user_id"`
	PeriodKey string       `json:"period_key"`
	SentAt    stdtime.Time `json:"sent_at"`
}

type DigestEntry struct {
	ID          uuid.UUID     `json:"id"`
	HouseholdID uuid.UUID     `json:"household_id"`
	UserID      uuid.UUID     `json:"user_id"`
	Cadence     string        `json:"cadence"`
	PeriodKey   string        `json:"period_key"`
	PeriodStart stdtime.Time  `json:"period_start"`
	PeriodEnd   stdtime.Time  `json:"period_end"`
	Label       string        `json:"label"`
	Payload     []byte        `json:"payload"`
	Narrative   *string       `json:"narrative"`
	ReadAt      *stdtime.Time `json:"read_at"`
	CreatedAt   stdtime.Time  `json:"created_at"`
}

type Document struct {
	ID                  uuid.UUID           `json:"id"`
	HouseholdID         uuid.UUID           `json:"household_id"`
	UploadedBy          *uuid.UUID          `json:"uploaded_by"`
	IsShared            bool                `json:"is_shared"`
	Title               string              `json:"title"`
	DocType             string              `json:"doc_type"`
	Filename            string              `json:"filename"`
	MimeType            string              `json:"mime_type"`
	SizeBytes           int64               `json:"size_bytes"`
	StorageKey          string              `json:"storage_key"`
	ContentHash         string              `json:"content_hash"`
	DocumentDate        *stdtime.Time       `json:"document_date"`
	ExpiresAt           *stdtime.Time       `json:"expires_at"`
	RetainUntil         *stdtime.Time       `json:"retain_until"`
	Notes               *string             `json:"notes"`
	CreatedAt           stdtime.Time        `json:"created_at"`
	UpdatedAt           stdtime.Time        `json:"updated_at"`
	ExtractedAt         *stdtime.Time       `json:"extracted_at"`
	ExtractedMerchant   *string             `json:"extracted_merchant"`
	ExtractedAmount     decimal.NullDecimal `json:"extracted_amount"`
	ExtractedDate       *stdtime.Time       `json:"extracted_date"`
	ExtractedConfidence decimal.NullDecimal `json:"extracted_confidence"`
	ExtractedNotes      *string             `json:"extracted_notes"`
}

type DocumentLink struct {
	ID            uuid.UUID    `json:"id"`
	DocumentID    uuid.UUID    `json:"document_id"`
	TransactionID *uuid.UUID   `json:"transaction_id"`
	ManualAssetID *uuid.UUID   `json:"manual_asset_id"`
	AccountID     *uuid.UUID   `json:"account_id"`
	GoalID        *uuid.UUID   `json:"goal_id"`
	CreatedAt     stdtime.Time `json:"created_at"`
}

type Employer struct {
	ID           uuid.UUID    `json:"id"`
	HouseholdID  uuid.UUID    `json:"household_id"`
	Name         string       `json:"name"`
	EinEncrypted []byte       `json:"ein_encrypted"`
	Address      *string      `json:"address"`
	PayFrequency string       `json:"pay_frequency"`
	CreatedAt    stdtime.Time `json:"created_at"`
	UpdatedAt    stdtime.Time `json:"updated_at"`
}

type Goal struct {
	ID           uuid.UUID       `json:"id"`
	HouseholdID  uuid.UUID       `json:"household_id"`
	Scope        string          `json:"scope"`
	UserID       *uuid.UUID      `json:"user_id"`
	Kind         string          `json:"kind"`
	Name         string          `json:"name"`
	TargetAmount decimal.Decimal `json:"target_amount"`
	TargetDate   *stdtime.Time   `json:"target_date"`
	AccountID    *uuid.UUID      `json:"account_id"`
	CategoryID   *uuid.UUID      `json:"category_id"`
	CreatedAt    stdtime.Time    `json:"created_at"`
	AchievedAt   *stdtime.Time   `json:"achieved_at"`
	ArchivedAt   *stdtime.Time   `json:"archived_at"`
	PersonID     *uuid.UUID      `json:"person_id"`
	// Years of study a college goal funds. target_amount is ONE year in today's dollars.
	CollegeYears int16 `json:"college_years"`
	Remind       bool  `json:"remind"`
}

type GoalContribution struct {
	ID         uuid.UUID       `json:"id"`
	GoalID     uuid.UUID       `json:"goal_id"`
	PersonID   uuid.UUID       `json:"person_id"`
	Amount     decimal.Decimal `json:"amount"`
	OccurredOn stdtime.Time    `json:"occurred_on"`
	Note       *string         `json:"note"`
	CreatedAt  stdtime.Time    `json:"created_at"`
}

type Holding struct {
	ID               uuid.UUID           `json:"id"`
	AccountID        uuid.UUID           `json:"account_id"`
	SecurityID       uuid.UUID           `json:"security_id"`
	Quantity         decimal.Decimal     `json:"quantity"`
	CostBasis        decimal.NullDecimal `json:"cost_basis"`
	InstitutionPrice decimal.NullDecimal `json:"institution_price"`
	InstitutionValue decimal.NullDecimal `json:"institution_value"`
	Currency         string              `json:"currency"`
	AsOf             *stdtime.Time       `json:"as_of"`
	CreatedAt        stdtime.Time        `json:"created_at"`
	UpdatedAt        stdtime.Time        `json:"updated_at"`
}

type Household struct {
	ID                uuid.UUID           `json:"id"`
	Name              string              `json:"name"`
	CreatedAt         stdtime.Time        `json:"created_at"`
	UpdatedAt         stdtime.Time        `json:"updated_at"`
	FilingStatus      *string             `json:"filing_status"`
	RiskDrawdownFloor decimal.NullDecimal `json:"risk_drawdown_floor"`
	// User-entered modified AGI for magi_tax_year. NULL, or a stale year, = unknown (never "eligible").
	Magi        decimal.NullDecimal `json:"magi"`
	MagiTaxYear *int32              `json:"magi_tax_year"`
}

type HouseholdInvite struct {
	ID          uuid.UUID     `json:"id"`
	HouseholdID uuid.UUID     `json:"household_id"`
	Email       string        `json:"email"`
	TokenHash   string        `json:"token_hash"`
	InvitedBy   *uuid.UUID    `json:"invited_by"`
	ExpiresAt   stdtime.Time  `json:"expires_at"`
	AcceptedAt  *stdtime.Time `json:"accepted_at"`
	CreatedAt   stdtime.Time  `json:"created_at"`
	Role        string        `json:"role"`
	PersonID    *uuid.UUID    `json:"person_id"`
}

type HouseholdPerson struct {
	ID          uuid.UUID     `json:"id"`
	HouseholdID uuid.UUID     `json:"household_id"`
	UserID      *uuid.UUID    `json:"user_id"`
	DisplayName string        `json:"display_name"`
	Birthdate   *stdtime.Time `json:"birthdate"`
	IsDependent bool          `json:"is_dependent"`
	CreatedAt   stdtime.Time  `json:"created_at"`
	UpdatedAt   stdtime.Time  `json:"updated_at"`
}

type Insight struct {
	ID          uuid.UUID     `json:"id"`
	HouseholdID uuid.UUID     `json:"household_id"`
	Kind        string        `json:"kind"`
	Priority    int16         `json:"priority"`
	Title       string        `json:"title"`
	Body        string        `json:"body"`
	Data        []byte        `json:"data"`
	Period      *stdtime.Time `json:"period"`
	DedupeKey   string        `json:"dedupe_key"`
	CreatedAt   stdtime.Time  `json:"created_at"`
	ReadAt      *stdtime.Time `json:"read_at"`
	DismissedAt *stdtime.Time `json:"dismissed_at"`
}

type InvestmentSnapshot struct {
	ID          uuid.UUID           `json:"id"`
	AccountID   uuid.UUID           `json:"account_id"`
	AsOf        stdtime.Time        `json:"as_of"`
	MarketValue decimal.Decimal     `json:"market_value"`
	CostBasis   decimal.NullDecimal `json:"cost_basis"`
	CreatedAt   stdtime.Time        `json:"created_at"`
}

type InvestmentTransaction struct {
	ID                           uuid.UUID           `json:"id"`
	AccountID                    uuid.UUID           `json:"account_id"`
	SecurityID                   *uuid.UUID          `json:"security_id"`
	PlaidInvestmentTransactionID *string             `json:"plaid_investment_transaction_id"`
	Type                         string              `json:"type"`
	Subtype                      *string             `json:"subtype"`
	Amount                       decimal.Decimal     `json:"amount"`
	Quantity                     decimal.NullDecimal `json:"quantity"`
	Price                        decimal.NullDecimal `json:"price"`
	Fees                         decimal.NullDecimal `json:"fees"`
	Date                         stdtime.Time        `json:"date"`
	Name                         *string             `json:"name"`
	Currency                     string              `json:"currency"`
	Raw                          []byte              `json:"raw"`
	CreatedAt                    stdtime.Time        `json:"created_at"`
	UpdatedAt                    stdtime.Time        `json:"updated_at"`
	Source                       string              `json:"source"`
}

type Liability struct {
	ID                     uuid.UUID           `json:"id"`
	AccountID              uuid.UUID           `json:"account_id"`
	Kind                   string              `json:"kind"`
	Apr                    decimal.NullDecimal `json:"apr"`
	AprType                *string             `json:"apr_type"`
	Balance                decimal.NullDecimal `json:"balance"`
	MinimumPayment         decimal.NullDecimal `json:"minimum_payment"`
	LastPaymentAmount      decimal.NullDecimal `json:"last_payment_amount"`
	LastPaymentDate        *stdtime.Time       `json:"last_payment_date"`
	NextPaymentDueDate     *stdtime.Time       `json:"next_payment_due_date"`
	OriginationDate        *stdtime.Time       `json:"origination_date"`
	OriginationPrincipal   decimal.NullDecimal `json:"origination_principal"`
	InterestRatePercentage decimal.NullDecimal `json:"interest_rate_percentage"`
	IsOverdue              *bool               `json:"is_overdue"`
	Raw                    []byte              `json:"raw"`
	CreatedAt              stdtime.Time        `json:"created_at"`
	UpdatedAt              stdtime.Time        `json:"updated_at"`
}

type ManualAsset struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	Name        string     `json:"name"`
	// home | vehicle | cash | collectible | bond | other | debt
	Kind          string          `json:"kind"`
	Value         decimal.Decimal `json:"value"`
	IsLiability   bool            `json:"is_liability"`
	AsOf          stdtime.Time    `json:"as_of"`
	Notes         *string         `json:"notes"`
	CreatedAt     stdtime.Time    `json:"created_at"`
	UpdatedAt     stdtime.Time    `json:"updated_at"`
	PersonID      *uuid.UUID      `json:"person_id"`
	LoanAccountID *uuid.UUID      `json:"loan_account_id"`
}

type MerchantAlias struct {
	ID          uuid.UUID           `json:"id"`
	HouseholdID uuid.UUID           `json:"household_id"`
	EntityID    uuid.UUID           `json:"entity_id"`
	MerchantKey string              `json:"merchant_key"`
	Source      string              `json:"source"`
	Confidence  decimal.NullDecimal `json:"confidence"`
	CreatedAt   stdtime.Time        `json:"created_at"`
}

type MerchantCategoryMap struct {
	ID          uuid.UUID           `json:"id"`
	HouseholdID uuid.UUID           `json:"household_id"`
	MerchantKey string              `json:"merchant_key"`
	CategoryID  uuid.UUID           `json:"category_id"`
	Source      string              `json:"source"`
	Confidence  decimal.NullDecimal `json:"confidence"`
	CreatedAt   stdtime.Time        `json:"created_at"`
	UpdatedAt   stdtime.Time        `json:"updated_at"`
}

type MerchantEntity struct {
	ID                uuid.UUID    `json:"id"`
	HouseholdID       uuid.UUID    `json:"household_id"`
	CanonicalName     string       `json:"canonical_name"`
	DefaultCategoryID *uuid.UUID   `json:"default_category_id"`
	Color             *string      `json:"color"`
	CreatedAt         stdtime.Time `json:"created_at"`
	UpdatedAt         stdtime.Time `json:"updated_at"`
}

type MerchantLogo struct {
	HouseholdID  uuid.UUID    `json:"household_id"`
	MerchantKey  string       `json:"merchant_key"`
	MerchantName string       `json:"merchant_name"`
	Domain       *string      `json:"domain"`
	ContentType  *string      `json:"content_type"`
	Image        []byte       `json:"image"`
	State        string       `json:"state"`
	CheckedAt    stdtime.Time `json:"checked_at"`
}

type MerchantMergeRejection struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	KeyA        string       `json:"key_a"`
	KeyB        string       `json:"key_b"`
	CreatedAt   stdtime.Time `json:"created_at"`
}

type MfaChallenge struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	Attempts  int32        `json:"attempts"`
	UserAgent *string      `json:"user_agent"`
	ClientIp  *string      `json:"client_ip"`
	ExpiresAt stdtime.Time `json:"expires_at"`
	CreatedAt stdtime.Time `json:"created_at"`
}

type MonthlySummary struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	Month       stdtime.Time `json:"month"`
	Summary     string       `json:"summary"`
	Model       string       `json:"model"`
	CreatedAt   stdtime.Time `json:"created_at"`
}

type NetWorthSnapshot struct {
	ID               uuid.UUID       `json:"id"`
	HouseholdID      uuid.UUID       `json:"household_id"`
	AsOf             stdtime.Time    `json:"as_of"`
	AssetsTotal      decimal.Decimal `json:"assets_total"`
	LiabilitiesTotal decimal.Decimal `json:"liabilities_total"`
	NetWorth         decimal.Decimal `json:"net_worth"`
	Breakdown        []byte          `json:"breakdown"`
	CreatedAt        stdtime.Time    `json:"created_at"`
}

type ObjectChange struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	ObjectKind  string       `json:"object_kind"`
	ObjectID    uuid.UUID    `json:"object_id"`
	ActorUserID *uuid.UUID   `json:"actor_user_id"`
	Field       string       `json:"field"`
	OldValue    []byte       `json:"old_value"`
	NewValue    []byte       `json:"new_value"`
	CreatedAt   stdtime.Time `json:"created_at"`
}

// One paid instance of a recurring obligation. The overdue-reminder producer treats a row here as "this occurrence is dealt with" and stops raising it; a member can add a manual row to confirm a match or record a payment the matcher missed.
type ObligationSatisfaction struct {
	ObligationID uuid.UUID    `json:"obligation_id"`
	DueDate      stdtime.Time `json:"due_date"`
	SatisfiedAt  stdtime.Time `json:"satisfied_at"`
	Source       string       `json:"source"`
	MatchedTxnID *uuid.UUID   `json:"matched_txn_id"`
	UserID       *uuid.UUID   `json:"user_id"`
	CreatedAt    stdtime.Time `json:"created_at"`
}

type Paystub struct {
	ID            uuid.UUID           `json:"id"`
	UserID        uuid.UUID           `json:"user_id"`
	EmployerID    uuid.UUID           `json:"employer_id"`
	PeriodStart   stdtime.Time        `json:"period_start"`
	PeriodEnd     stdtime.Time        `json:"period_end"`
	PayDate       stdtime.Time        `json:"pay_date"`
	Gross         decimal.Decimal     `json:"gross"`
	Net           decimal.Decimal     `json:"net"`
	YtdGross      decimal.NullDecimal `json:"ytd_gross"`
	YtdNet        decimal.NullDecimal `json:"ytd_net"`
	Source        string              `json:"source"`
	ConfirmedAt   *stdtime.Time       `json:"confirmed_at"`
	IsShared      bool                `json:"is_shared"`
	TransactionID *uuid.UUID          `json:"transaction_id"`
	DocumentID    *uuid.UUID          `json:"document_id"`
	CreatedAt     stdtime.Time        `json:"created_at"`
	UpdatedAt     stdtime.Time        `json:"updated_at"`
}

type PaystubLine struct {
	ID         uuid.UUID           `json:"id"`
	PaystubID  uuid.UUID           `json:"paystub_id"`
	Category   string              `json:"category"`
	Label      string              `json:"label"`
	Amount     decimal.Decimal     `json:"amount"`
	YtdAmount  decimal.NullDecimal `json:"ytd_amount"`
	PreTax     bool                `json:"pre_tax"`
	IsEmployer bool                `json:"is_employer"`
	CreatedAt  stdtime.Time        `json:"created_at"`
}

type PfcCategoryMap struct {
	ID           uuid.UUID `json:"id"`
	PfcPrimary   string    `json:"pfc_primary"`
	PfcDetailed  *string   `json:"pfc_detailed"`
	CategorySlug string    `json:"category_slug"`
}

type PiggyBank struct {
	ID           uuid.UUID           `json:"id"`
	HouseholdID  uuid.UUID           `json:"household_id"`
	AccountID    uuid.UUID           `json:"account_id"`
	Name         string              `json:"name"`
	TargetAmount decimal.NullDecimal `json:"target_amount"`
	CreatedAt    stdtime.Time        `json:"created_at"`
}

type PiggyBankEvent struct {
	ID            uuid.UUID       `json:"id"`
	PiggyBankID   uuid.UUID       `json:"piggy_bank_id"`
	Type          string          `json:"type"`
	Amount        decimal.Decimal `json:"amount"`
	TransactionID *uuid.UUID      `json:"transaction_id"`
	CreatedAt     stdtime.Time    `json:"created_at"`
}

type PlaidItem struct {
	ID                   uuid.UUID     `json:"id"`
	UserID               uuid.UUID     `json:"user_id"`
	PlaidItemID          string        `json:"plaid_item_id"`
	AccessTokenEncrypted []byte        `json:"access_token_encrypted"`
	InstitutionID        *string       `json:"institution_id"`
	InstitutionName      *string       `json:"institution_name"`
	Products             []string      `json:"products"`
	Status               string        `json:"status"`
	SyncCursor           *string       `json:"sync_cursor"`
	LastSyncedAt         *stdtime.Time `json:"last_synced_at"`
	BackfillComplete     bool          `json:"backfill_complete"`
	ErrorCode            *string       `json:"error_code"`
	IsShared             bool          `json:"is_shared"`
	CreatedAt            stdtime.Time  `json:"created_at"`
	UpdatedAt            stdtime.Time  `json:"updated_at"`
	LastRefreshAt        *stdtime.Time `json:"last_refresh_at"`
}

type PlanTracking struct {
	ID            uuid.UUID       `json:"id"`
	PlanID        uuid.UUID       `json:"plan_id"`
	AsOf          stdtime.Time    `json:"as_of"`
	ExpectedLump  decimal.Decimal `json:"expected_lump"`
	ExpectedTotal decimal.Decimal `json:"expected_total"`
	// Baseline captured at as_of. Every money field is a decimal STRING, never a JSON number.
	SnapshotInputs []byte       `json:"snapshot_inputs"`
	CreatedAt      stdtime.Time `json:"created_at"`
}

type Preference struct {
	ID          uuid.UUID    `json:"id"`
	Scope       string       `json:"scope"`
	UserID      *uuid.UUID   `json:"user_id"`
	HouseholdID *uuid.UUID   `json:"household_id"`
	Key         string       `json:"key"`
	Value       []byte       `json:"value"`
	UpdatedAt   stdtime.Time `json:"updated_at"`
}

type ProjectionAssumption struct {
	ID                  uuid.UUID       `json:"id"`
	HouseholdID         uuid.UUID       `json:"household_id"`
	RealReturnRate      decimal.Decimal `json:"real_return_rate"`
	InflationRate       decimal.Decimal `json:"inflation_rate"`
	WithdrawalRate      decimal.Decimal `json:"withdrawal_rate"`
	TargetRetirementAge *int32          `json:"target_retirement_age"`
	// DEPRECATED: prefer household_people.birthdate. A stored age decays.
	CurrentAge           *int32              `json:"current_age"`
	AnnualSsIncome       decimal.NullDecimal `json:"annual_ss_income"`
	SsStartAge           *int32              `json:"ss_start_age"`
	TargetAnnualSpending decimal.NullDecimal `json:"target_annual_spending"`
	UpdatedAt            stdtime.Time        `json:"updated_at"`
	CollegeInflationRate decimal.Decimal     `json:"college_inflation_rate"`
}

type RecurringObligation struct {
	ID               uuid.UUID       `json:"id"`
	HouseholdID      uuid.UUID       `json:"household_id"`
	UserID           *uuid.UUID      `json:"user_id"`
	IsShared         bool            `json:"is_shared"`
	Label            string          `json:"label"`
	Amount           decimal.Decimal `json:"amount"`
	CategoryID       *uuid.UUID      `json:"category_id"`
	AccountID        *uuid.UUID      `json:"account_id"`
	IntervalCount    int32           `json:"interval_count"`
	IntervalUnit     string          `json:"interval_unit"`
	AnchorDate       stdtime.Time    `json:"anchor_date"`
	EndDate          *stdtime.Time   `json:"end_date"`
	Source           string          `json:"source"`
	MerchantKey      *string         `json:"merchant_key"`
	UserEdited       bool            `json:"user_edited"`
	IsActive         bool            `json:"is_active"`
	CreatedAt        stdtime.Time    `json:"created_at"`
	UpdatedAt        stdtime.Time    `json:"updated_at"`
	AutoPost         bool            `json:"auto_post"`
	LastPostedDate   *stdtime.Time   `json:"last_posted_date"`
	PostingAccountID *uuid.UUID      `json:"posting_account_id"`
	Remind           bool            `json:"remind"`
}

type RecurringOverride struct {
	ID            uuid.UUID    `json:"id"`
	HouseholdID   uuid.UUID    `json:"household_id"`
	MerchantKey   string       `json:"merchant_key"`
	MerchantLabel string       `json:"merchant_label"`
	CreatedAt     stdtime.Time `json:"created_at"`
}

type SavingsBondRate struct {
	ID            uuid.UUID           `json:"id"`
	Series        string              `json:"series"`
	PeriodStart   stdtime.Time        `json:"period_start"`
	FixedRate     decimal.Decimal     `json:"fixed_rate"`
	InflationRate decimal.NullDecimal `json:"inflation_rate"`
	SourceUrl     string              `json:"source_url"`
	CreatedAt     stdtime.Time        `json:"created_at"`
}

type Security struct {
	ID               uuid.UUID           `json:"id"`
	PlaidSecurityID  *string             `json:"plaid_security_id"`
	Name             *string             `json:"name"`
	Ticker           *string             `json:"ticker"`
	Type             *string             `json:"type"`
	Cusip            *string             `json:"cusip"`
	Isin             *string             `json:"isin"`
	ClosePrice       decimal.NullDecimal `json:"close_price"`
	ClosePriceAsOf   *stdtime.Time       `json:"close_price_as_of"`
	Currency         string              `json:"currency"`
	IsCashEquivalent bool                `json:"is_cash_equivalent"`
	CreatedAt        stdtime.Time        `json:"created_at"`
	UpdatedAt        stdtime.Time        `json:"updated_at"`
	Source           string              `json:"source"`
	TickerKey        *string             `json:"ticker_key"`
}

type Session struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	TokenHash  string       `json:"token_hash"`
	UserAgent  *string      `json:"user_agent"`
	ExpiresAt  stdtime.Time `json:"expires_at"`
	CreatedAt  stdtime.Time `json:"created_at"`
	LastUsedAt stdtime.Time `json:"last_used_at"`
	ClientIp   *string      `json:"client_ip"`
}

type Tag struct {
	ID             uuid.UUID           `json:"id"`
	HouseholdID    uuid.UUID           `json:"household_id"`
	Name           string              `json:"name"`
	Description    *string             `json:"description"`
	ExpectedAmount decimal.NullDecimal `json:"expected_amount"`
	CreatedAt      stdtime.Time        `json:"created_at"`
	UpdatedAt      stdtime.Time        `json:"updated_at"`
}

type Transaction struct {
	ID                   uuid.UUID       `json:"id"`
	AccountID            uuid.UUID       `json:"account_id"`
	PlaidTransactionID   *string         `json:"plaid_transaction_id"`
	Amount               decimal.Decimal `json:"amount"`
	Currency             string          `json:"currency"`
	Date                 stdtime.Time    `json:"date"`
	AuthorizedDate       *stdtime.Time   `json:"authorized_date"`
	Name                 string          `json:"name"`
	MerchantName         *string         `json:"merchant_name"`
	MerchantKey          *string         `json:"merchant_key"`
	Pending              bool            `json:"pending"`
	PendingTransactionID *string         `json:"pending_transaction_id"`
	PlaidPfcPrimary      *string         `json:"plaid_pfc_primary"`
	PlaidPfcDetailed     *string         `json:"plaid_pfc_detailed"`
	CategoryID           *uuid.UUID      `json:"category_id"`
	CategorySource       *string         `json:"category_source"`
	IsRecurring          bool            `json:"is_recurring"`
	ExcludedFromReports  bool            `json:"excluded_from_reports"`
	Notes                *string         `json:"notes"`
	Source               string          `json:"source"`
	Raw                  []byte          `json:"raw"`
	CreatedAt            stdtime.Time    `json:"created_at"`
	UpdatedAt            stdtime.Time    `json:"updated_at"`
	// User state: a real but non-repeating event (loan payoff, tax bill, car purchase). Counted in the month it fell; skipped by trailing-average and recurring-detection queries that pass exclude_one_time. Preserved across Plaid sync, like excluded_from_reports and notes.
	IsOneTime    bool       `json:"is_one_time"`
	ObligationID *uuid.UUID `json:"obligation_id"`
}

// Two legs of one internal transfer (a debit on one of the household's accounts matched to an equal credit on another). Structural: matched by amount and date, not by payee name, so it catches transfers the name heuristics and Plaid miss. Each transaction is in at most one pair.
type TransactionPair struct {
	ID          uuid.UUID       `json:"id"`
	HouseholdID uuid.UUID       `json:"household_id"`
	OutTxnID    uuid.UUID       `json:"out_txn_id"`
	InTxnID     uuid.UUID       `json:"in_txn_id"`
	Amount      decimal.Decimal `json:"amount"`
	CreatedAt   stdtime.Time    `json:"created_at"`
}

type TransactionSplit struct {
	ID            uuid.UUID       `json:"id"`
	TransactionID uuid.UUID       `json:"transaction_id"`
	PersonID      uuid.UUID       `json:"person_id"`
	Amount        decimal.Decimal `json:"amount"`
	SettledAt     *stdtime.Time   `json:"settled_at"`
	CreatedAt     stdtime.Time    `json:"created_at"`
}

type TransactionTag struct {
	TransactionID uuid.UUID    `json:"transaction_id"`
	TagID         uuid.UUID    `json:"tag_id"`
	CreatedAt     stdtime.Time `json:"created_at"`
}

type User struct {
	ID                  uuid.UUID     `json:"id"`
	HouseholdID         uuid.UUID     `json:"household_id"`
	Email               string        `json:"email"`
	PasswordHash        string        `json:"password_hash"`
	DisplayName         string        `json:"display_name"`
	CreatedAt           stdtime.Time  `json:"created_at"`
	UpdatedAt           stdtime.Time  `json:"updated_at"`
	TotpSecretEncrypted []byte        `json:"totp_secret_encrypted"`
	TotpEnabled         bool          `json:"totp_enabled"`
	TotpConfirmedAt     *stdtime.Time `json:"totp_confirmed_at"`
	TotpLastStep        *int64        `json:"totp_last_step"`
	FailedLoginCount    int32         `json:"failed_login_count"`
	LockedUntil         *stdtime.Time `json:"locked_until"`
	Role                string        `json:"role"`
}

type UserRecoveryCode struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	CodeHash  string        `json:"code_hash"`
	UsedAt    *stdtime.Time `json:"used_at"`
	CreatedAt stdtime.Time  `json:"created_at"`
}

type Webhook struct {
	ID              uuid.UUID    `json:"id"`
	HouseholdID     uuid.UUID    `json:"household_id"`
	UserID          uuid.UUID    `json:"user_id"`
	Name            string       `json:"name"`
	Url             string       `json:"url"`
	SecretEncrypted []byte       `json:"secret_encrypted"`
	Active          bool         `json:"active"`
	Triggers        []string     `json:"triggers"`
	CreatedAt       stdtime.Time `json:"created_at"`
	UpdatedAt       stdtime.Time `json:"updated_at"`
}

type WebhookAttempt struct {
	ID              uuid.UUID    `json:"id"`
	MessageID       uuid.UUID    `json:"message_id"`
	Attempt         int32        `json:"attempt"`
	RequestHeaders  []byte       `json:"request_headers"`
	RequestBody     string       `json:"request_body"`
	ResponseStatus  *int32       `json:"response_status"`
	ResponseHeaders []byte       `json:"response_headers"`
	ResponseBody    *string      `json:"response_body"`
	Error           *string      `json:"error"`
	DurationMs      int32        `json:"duration_ms"`
	CreatedAt       stdtime.Time `json:"created_at"`
}

type WebhookMessage struct {
	ID          uuid.UUID     `json:"id"`
	WebhookID   uuid.UUID     `json:"webhook_id"`
	TriggerType string        `json:"trigger_type"`
	Payload     []byte        `json:"payload"`
	Status      string        `json:"status"`
	Attempts    int32         `json:"attempts"`
	DeliveredAt *stdtime.Time `json:"delivered_at"`
	LastError   *string       `json:"last_error"`
	DedupeKey   string        `json:"dedupe_key"`
	CreatedAt   stdtime.Time  `json:"created_at"`
}
