// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

type Account struct {
	ID               uuid.UUID           `json:"id"`
	PlaidItemID      uuid.UUID           `json:"plaid_item_id"`
	PlaidAccountID   string              `json:"plaid_account_id"`
	Name             string              `json:"name"`
	OfficialName     *string             `json:"official_name"`
	Mask             *string             `json:"mask"`
	Type             string              `json:"type"`
	Subtype          *string             `json:"subtype"`
	CurrentBalance   decimal.NullDecimal `json:"current_balance"`
	AvailableBalance decimal.NullDecimal `json:"available_balance"`
	CreditLimit      decimal.NullDecimal `json:"credit_limit"`
	Currency         string              `json:"currency"`
	IsActive         bool                `json:"is_active"`
	CreatedAt        stdtime.Time        `json:"created_at"`
	UpdatedAt        stdtime.Time        `json:"updated_at"`
}

type Alert struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	Type        string       `json:"type"`
	Config      []byte       `json:"config"`
	Enabled     bool         `json:"enabled"`
	CreatedAt   stdtime.Time `json:"created_at"`
	UpdatedAt   stdtime.Time `json:"updated_at"`
}

type AlertEvent struct {
	ID            uuid.UUID     `json:"id"`
	AlertID       uuid.UUID     `json:"alert_id"`
	TransactionID *uuid.UUID    `json:"transaction_id"`
	TriggeredAt   stdtime.Time  `json:"triggered_at"`
	Payload       []byte        `json:"payload"`
	ReadAt        *stdtime.Time `json:"read_at"`
	NotifiedAt    *stdtime.Time `json:"notified_at"`
}

type AuthEvent struct {
	ID             uuid.UUID    `json:"id"`
	UserID         *uuid.UUID   `json:"user_id"`
	EmailAttempted *string      `json:"email_attempted"`
	EventType      string       `json:"event_type"`
	ClientIp       *string      `json:"client_ip"`
	UserAgent      *string      `json:"user_agent"`
	Metadata       []byte       `json:"metadata"`
	CreatedAt      stdtime.Time `json:"created_at"`
}

type Budget struct {
	ID            uuid.UUID       `json:"id"`
	HouseholdID   uuid.UUID       `json:"household_id"`
	CategoryID    uuid.UUID       `json:"category_id"`
	OwnerScope    string          `json:"owner_scope"`
	UserID        *uuid.UUID      `json:"user_id"`
	Period        string          `json:"period"`
	Amount        decimal.Decimal `json:"amount"`
	EffectiveFrom *stdtime.Time   `json:"effective_from"`
	CreatedAt     stdtime.Time    `json:"created_at"`
	UpdatedAt     stdtime.Time    `json:"updated_at"`
}

type Category struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID *uuid.UUID   `json:"household_id"`
	ParentID    *uuid.UUID   `json:"parent_id"`
	Name        string       `json:"name"`
	Slug        string       `json:"slug"`
	Icon        *string      `json:"icon"`
	Color       *string      `json:"color"`
	IsFixed     bool         `json:"is_fixed"`
	IsIncome    bool         `json:"is_income"`
	IsTransfer  bool         `json:"is_transfer"`
	SortOrder   int32        `json:"sort_order"`
	CreatedAt   stdtime.Time `json:"created_at"`
	UpdatedAt   stdtime.Time `json:"updated_at"`
}

type CategoryRule struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	MatchType   string       `json:"match_type"`
	Pattern     string       `json:"pattern"`
	CategoryID  uuid.UUID    `json:"category_id"`
	Priority    int32        `json:"priority"`
	Enabled     bool         `json:"enabled"`
	CreatedAt   stdtime.Time `json:"created_at"`
	UpdatedAt   stdtime.Time `json:"updated_at"`
}

type Holding struct {
	ID               uuid.UUID           `json:"id"`
	AccountID        uuid.UUID           `json:"account_id"`
	SecurityID       uuid.UUID           `json:"security_id"`
	Quantity         decimal.Decimal     `json:"quantity"`
	CostBasis        decimal.NullDecimal `json:"cost_basis"`
	InstitutionPrice decimal.NullDecimal `json:"institution_price"`
	InstitutionValue decimal.NullDecimal `json:"institution_value"`
	Currency         string              `json:"currency"`
	AsOf             *stdtime.Time       `json:"as_of"`
	CreatedAt        stdtime.Time        `json:"created_at"`
	UpdatedAt        stdtime.Time        `json:"updated_at"`
}

type Household struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt stdtime.Time `json:"created_at"`
	UpdatedAt stdtime.Time `json:"updated_at"`
}

type HouseholdInvite struct {
	ID          uuid.UUID     `json:"id"`
	HouseholdID uuid.UUID     `json:"household_id"`
	Email       string        `json:"email"`
	TokenHash   string        `json:"token_hash"`
	InvitedBy   *uuid.UUID    `json:"invited_by"`
	ExpiresAt   stdtime.Time  `json:"expires_at"`
	AcceptedAt  *stdtime.Time `json:"accepted_at"`
	CreatedAt   stdtime.Time  `json:"created_at"`
}

type Insight struct {
	ID          uuid.UUID     `json:"id"`
	HouseholdID uuid.UUID     `json:"household_id"`
	Kind        string        `json:"kind"`
	Priority    int16         `json:"priority"`
	Title       string        `json:"title"`
	Body        string        `json:"body"`
	Data        []byte        `json:"data"`
	Period      *stdtime.Time `json:"period"`
	DedupeKey   string        `json:"dedupe_key"`
	CreatedAt   stdtime.Time  `json:"created_at"`
	ReadAt      *stdtime.Time `json:"read_at"`
	DismissedAt *stdtime.Time `json:"dismissed_at"`
}

type InvestmentTransaction struct {
	ID                           uuid.UUID           `json:"id"`
	AccountID                    uuid.UUID           `json:"account_id"`
	SecurityID                   *uuid.UUID          `json:"security_id"`
	PlaidInvestmentTransactionID string              `json:"plaid_investment_transaction_id"`
	Type                         string              `json:"type"`
	Subtype                      *string             `json:"subtype"`
	Amount                       decimal.Decimal     `json:"amount"`
	Quantity                     decimal.NullDecimal `json:"quantity"`
	Price                        decimal.NullDecimal `json:"price"`
	Fees                         decimal.NullDecimal `json:"fees"`
	Date                         stdtime.Time        `json:"date"`
	Name                         *string             `json:"name"`
	Currency                     string              `json:"currency"`
	Raw                          []byte              `json:"raw"`
	CreatedAt                    stdtime.Time        `json:"created_at"`
	UpdatedAt                    stdtime.Time        `json:"updated_at"`
}

type Liability struct {
	ID                     uuid.UUID           `json:"id"`
	AccountID              uuid.UUID           `json:"account_id"`
	Kind                   string              `json:"kind"`
	Apr                    decimal.NullDecimal `json:"apr"`
	AprType                *string             `json:"apr_type"`
	Balance                decimal.NullDecimal `json:"balance"`
	MinimumPayment         decimal.NullDecimal `json:"minimum_payment"`
	LastPaymentAmount      decimal.NullDecimal `json:"last_payment_amount"`
	LastPaymentDate        *stdtime.Time       `json:"last_payment_date"`
	NextPaymentDueDate     *stdtime.Time       `json:"next_payment_due_date"`
	OriginationDate        *stdtime.Time       `json:"origination_date"`
	OriginationPrincipal   decimal.NullDecimal `json:"origination_principal"`
	InterestRatePercentage decimal.NullDecimal `json:"interest_rate_percentage"`
	IsOverdue              *bool               `json:"is_overdue"`
	Raw                    []byte              `json:"raw"`
	CreatedAt              stdtime.Time        `json:"created_at"`
	UpdatedAt              stdtime.Time        `json:"updated_at"`
}

type ManualAsset struct {
	ID          uuid.UUID       `json:"id"`
	HouseholdID uuid.UUID       `json:"household_id"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	Name        string          `json:"name"`
	Kind        string          `json:"kind"`
	Value       decimal.Decimal `json:"value"`
	IsLiability bool            `json:"is_liability"`
	AsOf        stdtime.Time    `json:"as_of"`
	Notes       *string         `json:"notes"`
	CreatedAt   stdtime.Time    `json:"created_at"`
	UpdatedAt   stdtime.Time    `json:"updated_at"`
}

type MerchantCategoryMap struct {
	ID          uuid.UUID           `json:"id"`
	HouseholdID uuid.UUID           `json:"household_id"`
	MerchantKey string              `json:"merchant_key"`
	CategoryID  uuid.UUID           `json:"category_id"`
	Source      string              `json:"source"`
	Confidence  decimal.NullDecimal `json:"confidence"`
	CreatedAt   stdtime.Time        `json:"created_at"`
	UpdatedAt   stdtime.Time        `json:"updated_at"`
}

type MfaChallenge struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	Attempts  int32        `json:"attempts"`
	UserAgent *string      `json:"user_agent"`
	ClientIp  *string      `json:"client_ip"`
	ExpiresAt stdtime.Time `json:"expires_at"`
	CreatedAt stdtime.Time `json:"created_at"`
}

type MonthlySummary struct {
	ID          uuid.UUID    `json:"id"`
	HouseholdID uuid.UUID    `json:"household_id"`
	Month       stdtime.Time `json:"month"`
	Summary     string       `json:"summary"`
	Model       string       `json:"model"`
	CreatedAt   stdtime.Time `json:"created_at"`
}

type NetWorthSnapshot struct {
	ID               uuid.UUID       `json:"id"`
	HouseholdID      uuid.UUID       `json:"household_id"`
	AsOf             stdtime.Time    `json:"as_of"`
	AssetsTotal      decimal.Decimal `json:"assets_total"`
	LiabilitiesTotal decimal.Decimal `json:"liabilities_total"`
	NetWorth         decimal.Decimal `json:"net_worth"`
	Breakdown        []byte          `json:"breakdown"`
	CreatedAt        stdtime.Time    `json:"created_at"`
}

type PfcCategoryMap struct {
	ID           uuid.UUID `json:"id"`
	PfcPrimary   string    `json:"pfc_primary"`
	PfcDetailed  *string   `json:"pfc_detailed"`
	CategorySlug string    `json:"category_slug"`
}

type PlaidItem struct {
	ID                   uuid.UUID     `json:"id"`
	UserID               uuid.UUID     `json:"user_id"`
	PlaidItemID          string        `json:"plaid_item_id"`
	AccessTokenEncrypted []byte        `json:"access_token_encrypted"`
	InstitutionID        *string       `json:"institution_id"`
	InstitutionName      *string       `json:"institution_name"`
	Products             []string      `json:"products"`
	Status               string        `json:"status"`
	SyncCursor           *string       `json:"sync_cursor"`
	LastSyncedAt         *stdtime.Time `json:"last_synced_at"`
	BackfillComplete     bool          `json:"backfill_complete"`
	ErrorCode            *string       `json:"error_code"`
	IsShared             bool          `json:"is_shared"`
	CreatedAt            stdtime.Time  `json:"created_at"`
	UpdatedAt            stdtime.Time  `json:"updated_at"`
	LastRefreshAt        *stdtime.Time `json:"last_refresh_at"`
}

type Preference struct {
	ID          uuid.UUID    `json:"id"`
	Scope       string       `json:"scope"`
	UserID      *uuid.UUID   `json:"user_id"`
	HouseholdID *uuid.UUID   `json:"household_id"`
	Key         string       `json:"key"`
	Value       []byte       `json:"value"`
	UpdatedAt   stdtime.Time `json:"updated_at"`
}

type Security struct {
	ID               uuid.UUID           `json:"id"`
	PlaidSecurityID  string              `json:"plaid_security_id"`
	Name             *string             `json:"name"`
	Ticker           *string             `json:"ticker"`
	Type             *string             `json:"type"`
	Cusip            *string             `json:"cusip"`
	Isin             *string             `json:"isin"`
	ClosePrice       decimal.NullDecimal `json:"close_price"`
	ClosePriceAsOf   *stdtime.Time       `json:"close_price_as_of"`
	Currency         string              `json:"currency"`
	IsCashEquivalent bool                `json:"is_cash_equivalent"`
	CreatedAt        stdtime.Time        `json:"created_at"`
	UpdatedAt        stdtime.Time        `json:"updated_at"`
}

type Session struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	TokenHash  string       `json:"token_hash"`
	UserAgent  *string      `json:"user_agent"`
	ExpiresAt  stdtime.Time `json:"expires_at"`
	CreatedAt  stdtime.Time `json:"created_at"`
	LastUsedAt stdtime.Time `json:"last_used_at"`
	ClientIp   *string      `json:"client_ip"`
}

type Transaction struct {
	ID                   uuid.UUID       `json:"id"`
	AccountID            uuid.UUID       `json:"account_id"`
	PlaidTransactionID   *string         `json:"plaid_transaction_id"`
	Amount               decimal.Decimal `json:"amount"`
	Currency             string          `json:"currency"`
	Date                 stdtime.Time    `json:"date"`
	AuthorizedDate       *stdtime.Time   `json:"authorized_date"`
	Name                 string          `json:"name"`
	MerchantName         *string         `json:"merchant_name"`
	MerchantKey          *string         `json:"merchant_key"`
	Pending              bool            `json:"pending"`
	PendingTransactionID *string         `json:"pending_transaction_id"`
	PlaidPfcPrimary      *string         `json:"plaid_pfc_primary"`
	PlaidPfcDetailed     *string         `json:"plaid_pfc_detailed"`
	CategoryID           *uuid.UUID      `json:"category_id"`
	CategorySource       *string         `json:"category_source"`
	IsRecurring          bool            `json:"is_recurring"`
	ExcludedFromReports  bool            `json:"excluded_from_reports"`
	Notes                *string         `json:"notes"`
	Source               string          `json:"source"`
	Raw                  []byte          `json:"raw"`
	CreatedAt            stdtime.Time    `json:"created_at"`
	UpdatedAt            stdtime.Time    `json:"updated_at"`
}

type User struct {
	ID                  uuid.UUID     `json:"id"`
	HouseholdID         uuid.UUID     `json:"household_id"`
	Email               string        `json:"email"`
	PasswordHash        string        `json:"password_hash"`
	DisplayName         string        `json:"display_name"`
	CreatedAt           stdtime.Time  `json:"created_at"`
	UpdatedAt           stdtime.Time  `json:"updated_at"`
	TotpSecretEncrypted []byte        `json:"totp_secret_encrypted"`
	TotpEnabled         bool          `json:"totp_enabled"`
	TotpConfirmedAt     *stdtime.Time `json:"totp_confirmed_at"`
	TotpLastStep        *int64        `json:"totp_last_step"`
	FailedLoginCount    int32         `json:"failed_login_count"`
	LockedUntil         *stdtime.Time `json:"locked_until"`
}

type UserRecoveryCode struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	CodeHash  string        `json:"code_hash"`
	UsedAt    *stdtime.Time `json:"used_at"`
	CreatedAt stdtime.Time  `json:"created_at"`
}
