// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: object_changes.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	stdtime "time"
)

const insertObjectChange = `-- name: InsertObjectChange :exec

INSERT INTO object_changes (
    household_id, object_kind, object_id, actor_user_id, field, old_value, new_value
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertObjectChangeParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	ObjectKind  string     `json:"object_kind"`
	ObjectID    uuid.UUID  `json:"object_id"`
	ActorUserID *uuid.UUID `json:"actor_user_id"`
	Field       string     `json:"field"`
	OldValue    []byte     `json:"old_value"`
	NewValue    []byte     `json:"new_value"`
}

// Per-object change history. One row per changed field, written in the same
// transaction as the mutation it records. See migration 00062_object_changes.sql
// for the append-only contract and the visibility model.
// One field-level diff row. Called inside the caller's transaction (handlers
// pass a tx-backed *Queries), so a rolled-back mutation writes nothing — the
// load-bearing "same transaction" invariant. old/new are JSONB: NULL old means
// a field was set on create, NULL new means it was cleared.
func (q *Queries) InsertObjectChange(ctx context.Context, arg InsertObjectChangeParams) error {
	_, err := q.db.Exec(ctx, insertObjectChange,
		arg.HouseholdID,
		arg.ObjectKind,
		arg.ObjectID,
		arg.ActorUserID,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const listBudgetChanges = `-- name: ListBudgetChanges :many
SELECT oc.field, oc.old_value, oc.new_value, oc.actor_user_id,
       u.display_name AS actor_display_name, oc.created_at
FROM object_changes oc
JOIN budgets b   ON b.id = oc.object_id
LEFT JOIN users u ON u.id = oc.actor_user_id
WHERE oc.household_id = $1
  AND oc.object_kind = 'budget'
  AND oc.object_id = $2
  AND (b.owner_scope = 'household' OR b.user_id = $3::uuid)
ORDER BY oc.created_at DESC
LIMIT $4
`

type ListBudgetChangesParams struct {
	HouseholdID  uuid.UUID  `json:"household_id"`
	ObjectID     uuid.UUID  `json:"object_id"`
	ViewerUserID *uuid.UUID `json:"viewer_user_id"`
	LimitCount   int32      `json:"limit_count"`
}

type ListBudgetChangesRow struct {
	Field            string       `json:"field"`
	OldValue         []byte       `json:"old_value"`
	NewValue         []byte       `json:"new_value"`
	ActorUserID      *uuid.UUID   `json:"actor_user_id"`
	ActorDisplayName *string      `json:"actor_display_name"`
	CreatedAt        stdtime.Time `json:"created_at"`
}

// A household budget is visible to everyone; a personal budget to its owner.
func (q *Queries) ListBudgetChanges(ctx context.Context, arg ListBudgetChangesParams) ([]ListBudgetChangesRow, error) {
	rows, err := q.db.Query(ctx, listBudgetChanges,
		arg.HouseholdID,
		arg.ObjectID,
		arg.ViewerUserID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetChangesRow{}
	for rows.Next() {
		var i ListBudgetChangesRow
		if err := rows.Scan(
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.ActorUserID,
			&i.ActorDisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalChanges = `-- name: ListGoalChanges :many
SELECT oc.field, oc.old_value, oc.new_value, oc.actor_user_id,
       u.display_name AS actor_display_name, oc.created_at
FROM object_changes oc
JOIN goals g     ON g.id = oc.object_id
LEFT JOIN users u ON u.id = oc.actor_user_id
WHERE oc.household_id = $1
  AND oc.object_kind = 'goal'
  AND oc.object_id = $2
  AND (
        g.scope = 'household'
     OR (g.scope = 'user'   AND g.user_id = $3::uuid)
     OR (g.scope = 'person' AND ($4::boolean
                                 OR g.person_id = $5::uuid))
  )
ORDER BY oc.created_at DESC
LIMIT $6
`

type ListGoalChangesParams struct {
	HouseholdID    uuid.UUID  `json:"household_id"`
	ObjectID       uuid.UUID  `json:"object_id"`
	ViewerUserID   *uuid.UUID `json:"viewer_user_id"`
	AllPersonGoals bool       `json:"all_person_goals"`
	PersonID       *uuid.UUID `json:"person_id"`
	LimitCount     int32      `json:"limit_count"`
}

type ListGoalChangesRow struct {
	Field            string       `json:"field"`
	OldValue         []byte       `json:"old_value"`
	NewValue         []byte       `json:"new_value"`
	ActorUserID      *uuid.UUID   `json:"actor_user_id"`
	ActorDisplayName *string      `json:"actor_display_name"`
	CreatedAt        stdtime.Time `json:"created_at"`
}

// Goal visibility is the three-way scope: household (everyone), user (owner),
// person (the person it belongs to, plus any adult). all_person_goals carries
// the adult/child decision into the SQL the way ListGoals does.
func (q *Queries) ListGoalChanges(ctx context.Context, arg ListGoalChangesParams) ([]ListGoalChangesRow, error) {
	rows, err := q.db.Query(ctx, listGoalChanges,
		arg.HouseholdID,
		arg.ObjectID,
		arg.ViewerUserID,
		arg.AllPersonGoals,
		arg.PersonID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalChangesRow{}
	for rows.Next() {
		var i ListGoalChangesRow
		if err := rows.Scan(
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.ActorUserID,
			&i.ActorDisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionChanges = `-- name: ListTransactionChanges :many

SELECT oc.field, oc.old_value, oc.new_value, oc.actor_user_id,
       u.display_name AS actor_display_name, oc.created_at
FROM object_changes oc
JOIN transactions t ON t.id = oc.object_id
JOIN accounts a     ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
LEFT JOIN users u   ON u.id = oc.actor_user_id
WHERE oc.household_id = $1
  AND oc.object_kind = 'transaction'
  AND oc.object_id = $2
  AND (v.user_id = $3::uuid OR v.is_shared)
ORDER BY oc.created_at DESC
LIMIT $4
`

type ListTransactionChangesParams struct {
	HouseholdID  uuid.UUID  `json:"household_id"`
	ObjectID     uuid.UUID  `json:"object_id"`
	ViewerUserID *uuid.UUID `json:"viewer_user_id"`
	LimitCount   int32      `json:"limit_count"`
}

type ListTransactionChangesRow struct {
	Field            string       `json:"field"`
	OldValue         []byte       `json:"old_value"`
	NewValue         []byte       `json:"new_value"`
	ActorUserID      *uuid.UUID   `json:"actor_user_id"`
	ActorDisplayName *string      `json:"actor_display_name"`
	CreatedAt        stdtime.Time `json:"created_at"`
}

// --------------------------------------------------------------------------
// Read paths. The History panel lists one object's changes newest-first, and
// each query re-resolves visibility by joining back to the source table — so a
// private account/transaction's history is invisible to the other member of the
// household, exactly as the object itself is. Mirrors the scoping each detail
// view already applies.
// --------------------------------------------------------------------------
// Transaction visibility is inherited from the account it posts to, resolved
// through account_access: own items ∪ household items where is_shared.
func (q *Queries) ListTransactionChanges(ctx context.Context, arg ListTransactionChangesParams) ([]ListTransactionChangesRow, error) {
	rows, err := q.db.Query(ctx, listTransactionChanges,
		arg.HouseholdID,
		arg.ObjectID,
		arg.ViewerUserID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionChangesRow{}
	for rows.Next() {
		var i ListTransactionChangesRow
		if err := rows.Scan(
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.ActorUserID,
			&i.ActorDisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
