// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: obligations.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

const createObligation = `-- name: CreateObligation :one

INSERT INTO recurring_obligations (
    household_id, user_id, is_shared, label, amount, category_id, account_id,
    interval_count, interval_unit, anchor_date, end_date, source, merchant_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'manual', NULL)
RETURNING id, household_id, user_id, is_shared, label, amount, category_id, account_id, interval_count, interval_unit, anchor_date, end_date, source, merchant_key, user_edited, is_active, created_at, updated_at, auto_post, last_posted_date, posting_account_id
`

type CreateObligationParams struct {
	HouseholdID   uuid.UUID       `json:"household_id"`
	UserID        *uuid.UUID      `json:"user_id"`
	IsShared      bool            `json:"is_shared"`
	Label         string          `json:"label"`
	Amount        decimal.Decimal `json:"amount"`
	CategoryID    *uuid.UUID      `json:"category_id"`
	AccountID     *uuid.UUID      `json:"account_id"`
	IntervalCount int32           `json:"interval_count"`
	IntervalUnit  string          `json:"interval_unit"`
	AnchorDate    stdtime.Time    `json:"anchor_date"`
	EndDate       *stdtime.Time   `json:"end_date"`
}

// Recurring obligations: the bill calendar's reads and writes.
//
// Two rules hold everywhere in this file:
//
//   - Occurrences are DERIVED, never stored. anchor_date plus the (count, unit)
//     cadence generates them on demand, so there is no next-due cache to go
//     stale. All of that arithmetic happens here, in Postgres, because Postgres
//     interval addition clamps month ends the way a person would read them
//     (2025-01-31 + interval '1 month' = 2025-02-28) and Go's time.AddDate does
//     not (it normalises to 2025-03-03). One place, one behaviour.
//   - Visibility is scoped like every other household read: household-owned
//     rows (user_id IS NULL — what the detector promotes), the caller's own
//     rows, and other members' rows only when shared.
func (q *Queries) CreateObligation(ctx context.Context, arg CreateObligationParams) (RecurringObligation, error) {
	row := q.db.QueryRow(ctx, createObligation,
		arg.HouseholdID,
		arg.UserID,
		arg.IsShared,
		arg.Label,
		arg.Amount,
		arg.CategoryID,
		arg.AccountID,
		arg.IntervalCount,
		arg.IntervalUnit,
		arg.AnchorDate,
		arg.EndDate,
	)
	var i RecurringObligation
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.IsShared,
		&i.Label,
		&i.Amount,
		&i.CategoryID,
		&i.AccountID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.AnchorDate,
		&i.EndDate,
		&i.Source,
		&i.MerchantKey,
		&i.UserEdited,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoPost,
		&i.LastPostedDate,
		&i.PostingAccountID,
	)
	return i, err
}

const deactivateSuppressedObligations = `-- name: DeactivateSuppressedObligations :execrows
UPDATE recurring_obligations o
SET is_active = FALSE, updated_at = now()
FROM recurring_overrides ro
WHERE o.household_id = $1
  AND o.source = 'detected'
  AND o.is_active
  AND ro.household_id = o.household_id
  AND COALESCE(
        (SELECT a1.entity_id::text FROM merchant_aliases a1
          WHERE a1.household_id = ro.household_id
            AND a1.merchant_key = ro.merchant_key
            AND a1.source <> 'suggested'),
        ro.merchant_key
      ) = COALESCE(
        (SELECT a2.entity_id::text FROM merchant_aliases a2
          WHERE a2.household_id = o.household_id
            AND a2.merchant_key = o.merchant_key
            AND a2.source <> 'suggested'),
        o.merchant_key
      )
`

// A merchant the household marked "not recurring" must never show up as a bill.
// GetRecurringMerchants already excludes suppressed merchants, so promotion will
// not re-create these; this retires rows promoted before the suppression.
//
// Both keys are resolved (merchants.sql) rather than compared literally, so an
// obligation promoted under a raw descriptor is still retired by a suppression
// recorded against the merged merchant, and vice versa.
func (q *Queries) DeactivateSuppressedObligations(ctx context.Context, householdID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateSuppressedObligations, householdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateUndetectedObligations = `-- name: DeactivateUndetectedObligations :execrows
UPDATE recurring_obligations
SET is_active = FALSE, updated_at = now()
WHERE household_id = $1
  AND source = 'detected'
  AND is_active
  AND NOT user_edited
  AND merchant_key <> ALL($2::text[])
`

type DeactivateUndetectedObligationsParams struct {
	HouseholdID  uuid.UUID `json:"household_id"`
	DetectedKeys []string  `json:"detected_keys"`
}

// Retire detected bills the detector no longer returns. Promotion is an upsert
// and nothing else ever cleared a row, so without this a detected obligation
// lives forever. Two ways that goes wrong, and the second is the expensive one:
//
//	A merchant that simply stops recurring leaves a tombstone — a bill on the
//	calendar predicting money that will never move.
//
//	Worse, merging descriptors into an entity CHANGES the resolved merchant key
//	the detector reports. Promotion then writes a brand new row under the entity
//	key while the row under the raw descriptor stays active, so one bill is
//	counted twice — on the calendar, in the balance projection, and in the
//	safe-to-spend split.
//
// @detected_keys is the resolved key of every merchant promoted this pass, so
// "no longer detected" covers both cases with one comparison. Passing an empty
// array is meaningful and must retire everything: `<> ALL` over zero rows is
// TRUE, which is the behaviour wanted (the detector found nothing, so nothing
// detected should be live).
//
// A user-edited row is left alone, matching UpsertDetectedObligation: once
// someone has corrected a bill by hand the detector no longer owns it, and
// silently deleting a correction is worse than carrying a stale one.
func (q *Queries) DeactivateUndetectedObligations(ctx context.Context, arg DeactivateUndetectedObligationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateUndetectedObligations, arg.HouseholdID, arg.DetectedKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteObligation = `-- name: DeleteObligation :exec
DELETE FROM recurring_obligations
WHERE id = $1 AND household_id = $2 AND source = 'manual'
  AND (user_id = $3 OR is_shared)
`

type DeleteObligationParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UserID      *uuid.UUID `json:"user_id"`
}

// Hard delete, for manual rows only. A detected row would be re-promoted, so the
// API routes those to SetObligationActive instead.
func (q *Queries) DeleteObligation(ctx context.Context, arg DeleteObligationParams) error {
	_, err := q.db.Exec(ctx, deleteObligation, arg.ID, arg.HouseholdID, arg.UserID)
	return err
}

const getMerchantDominantCategories = `-- name: GetMerchantDominantCategories :many
SELECT
    COALESCE(ma.entity_id::text, t.merchant_key)::text   AS merchant_key,
    (mode() WITHIN GROUP (ORDER BY t.category_id))::uuid AS category_id
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
LEFT JOIN merchant_aliases ma
       ON ma.household_id = $1
      AND ma.merchant_key = t.merchant_key
      AND ma.source <> 'suggested'
WHERE v.household_id = $1
  AND (v.user_id = $2 OR v.is_shared)
  AND a.is_active
  AND NOT t.excluded_from_reports
  AND NOT t.pending
  AND t.merchant_key IS NOT NULL
  AND t.category_id IS NOT NULL
  AND t.amount > 0
  AND t.date >= $3
GROUP BY COALESCE(ma.entity_id::text, t.merchant_key)
`

type GetMerchantDominantCategoriesParams struct {
	HouseholdID uuid.UUID    `json:"household_id"`
	UserID      uuid.UUID    `json:"user_id"`
	Date        stdtime.Time `json:"date"`
}

type GetMerchantDominantCategoriesRow struct {
	MerchantKey string    `json:"merchant_key"`
	CategoryID  uuid.UUID `json:"category_id"`
}

// The category each recurring merchant is usually filed under, so a promoted
// obligation lands in the right category. That matters beyond cosmetics: the
// safe-to-spend split uses an obligation's category to decide whether it
// REPLACES that category's trailing typical cost or is already inside a
// discretionary budget envelope. Without a category every promoted bill would
// have to be assumed uncovered, and fixed costs would be counted twice.
//
// Same spend definition, visibility scoping, and resolved merchant grouping as
// GetRecurringMerchants — the caller looks these rows up by the key that query
// returned, so the two must agree on the key space.
func (q *Queries) GetMerchantDominantCategories(ctx context.Context, arg GetMerchantDominantCategoriesParams) ([]GetMerchantDominantCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getMerchantDominantCategories, arg.HouseholdID, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMerchantDominantCategoriesRow{}
	for rows.Next() {
		var i GetMerchantDominantCategoriesRow
		if err := rows.Scan(&i.MerchantKey, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObligation = `-- name: GetObligation :one
SELECT id, household_id, user_id, is_shared, label, amount, category_id, account_id, interval_count, interval_unit, anchor_date, end_date, source, merchant_key, user_edited, is_active, created_at, updated_at, auto_post, last_posted_date, posting_account_id FROM recurring_obligations
WHERE id = $1 AND household_id = $2
  AND (user_id IS NULL OR user_id = $3 OR is_shared)
`

type GetObligationParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UserID      *uuid.UUID `json:"user_id"`
}

func (q *Queries) GetObligation(ctx context.Context, arg GetObligationParams) (RecurringObligation, error) {
	row := q.db.QueryRow(ctx, getObligation, arg.ID, arg.HouseholdID, arg.UserID)
	var i RecurringObligation
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.IsShared,
		&i.Label,
		&i.Amount,
		&i.CategoryID,
		&i.AccountID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.AnchorDate,
		&i.EndDate,
		&i.Source,
		&i.MerchantKey,
		&i.UserEdited,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoPost,
		&i.LastPostedDate,
		&i.PostingAccountID,
	)
	return i, err
}

const insertScheduledTransaction = `-- name: InsertScheduledTransaction :one
INSERT INTO transactions (
    account_id, amount, currency, date, name, merchant_key,
    category_id, category_source, source, pending, obligation_id
)
SELECT
    a.id, $1, a.currency, $2, $3,
    $4, $5,
    CASE WHEN $5::uuid IS NULL THEN NULL ELSE 'manual' END,
    'scheduled', false, $6
FROM accounts a
WHERE a.id = $7
ON CONFLICT (obligation_id, date) WHERE obligation_id IS NOT NULL DO NOTHING
RETURNING id, account_id, plaid_transaction_id, amount, currency, date, authorized_date, name, merchant_name, merchant_key, pending, pending_transaction_id, plaid_pfc_primary, plaid_pfc_detailed, category_id, category_source, is_recurring, excluded_from_reports, notes, source, raw, created_at, updated_at, is_one_time, obligation_id
`

type InsertScheduledTransactionParams struct {
	Amount       decimal.Decimal `json:"amount"`
	Date         stdtime.Time    `json:"date"`
	Name         string          `json:"name"`
	MerchantKey  *string         `json:"merchant_key"`
	CategoryID   *uuid.UUID      `json:"category_id"`
	ObligationID *uuid.UUID      `json:"obligation_id"`
	AccountID    uuid.UUID       `json:"account_id"`
}

// The materialised row. obligation_id ties it back to the template, and the
// partial unique index on (obligation_id, date) makes a duplicate posting
// impossible rather than merely unlikely — ON CONFLICT DO NOTHING turns a
// replay into zero rows instead of a second charge.
func (q *Queries) InsertScheduledTransaction(ctx context.Context, arg InsertScheduledTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertScheduledTransaction,
		arg.Amount,
		arg.Date,
		arg.Name,
		arg.MerchantKey,
		arg.CategoryID,
		arg.ObligationID,
		arg.AccountID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PlaidTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.AuthorizedDate,
		&i.Name,
		&i.MerchantName,
		&i.MerchantKey,
		&i.Pending,
		&i.PendingTransactionID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.CategoryID,
		&i.CategorySource,
		&i.IsRecurring,
		&i.ExcludedFromReports,
		&i.Notes,
		&i.Source,
		&i.Raw,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsOneTime,
		&i.ObligationID,
	)
	return i, err
}

const listObligations = `-- name: ListObligations :many
SELECT id, household_id, user_id, is_shared, label, amount, category_id, account_id, interval_count, interval_unit, anchor_date, end_date, source, merchant_key, user_edited, is_active, created_at, updated_at, auto_post, last_posted_date, posting_account_id FROM recurring_obligations
WHERE household_id = $1
  AND (user_id IS NULL OR user_id = $2 OR is_shared)
ORDER BY is_active DESC, label
`

type ListObligationsParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	UserID      *uuid.UUID `json:"user_id"`
}

// Every obligation the caller can see, active first. The occurrence expansion
// lives in ListUpcomingObligations; this is the row-level list the management UI
// edits.
//
// merchant_key needs no canonicalisation on the way out, unlike most reads of a
// stored key. A detected row's key comes from GetRecurringMerchants and is
// already resolved, and a later merge does not strand it: the merge changes the
// resolved key, so the next promotion pass writes a row under the new key and
// DeactivateUndetectedObligations retires the old one. The key a live detected
// row carries is therefore always current, and addresses the merchant detail
// view directly.
func (q *Queries) ListObligations(ctx context.Context, arg ListObligationsParams) ([]RecurringObligation, error) {
	rows, err := q.db.Query(ctx, listObligations, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringObligation{}
	for rows.Next() {
		var i RecurringObligation
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.UserID,
			&i.IsShared,
			&i.Label,
			&i.Amount,
			&i.CategoryID,
			&i.AccountID,
			&i.IntervalCount,
			&i.IntervalUnit,
			&i.AnchorDate,
			&i.EndDate,
			&i.Source,
			&i.MerchantKey,
			&i.UserEdited,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoPost,
			&i.LastPostedDate,
			&i.PostingAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObligationsDueForPosting = `-- name: ListObligationsDueForPosting :many
WITH due AS (
    SELECT id, household_id, user_id, is_shared, label, amount, category_id, account_id, interval_count, interval_unit, anchor_date, end_date, source, merchant_key, user_edited, is_active, created_at, updated_at, auto_post, last_posted_date, posting_account_id
    FROM recurring_obligations
    WHERE auto_post
      AND is_active
      AND (end_date IS NULL OR end_date >= anchor_date)
      AND (account_id IS NOT NULL OR posting_account_id IS NOT NULL)
),
bounded AS (
    SELECT
        due.id, due.household_id, due.user_id, due.is_shared, due.label, due.amount, due.category_id, due.account_id, due.interval_count, due.interval_unit, due.anchor_date, due.end_date, due.source, due.merchant_key, due.user_edited, due.is_active, due.created_at, due.updated_at, due.auto_post, due.last_posted_date, due.posting_account_id,
        CASE interval_unit
            WHEN 'day'   THEN ($1::date - anchor_date) / interval_count
            WHEN 'week'  THEN ($1::date - anchor_date) / (7 * interval_count)
            WHEN 'month' THEN (12 * (EXTRACT(YEAR  FROM $1::date)::int - EXTRACT(YEAR  FROM anchor_date)::int)
                                  + (EXTRACT(MONTH FROM $1::date)::int - EXTRACT(MONTH FROM anchor_date)::int))
                              / interval_count
            WHEN 'year'  THEN (EXTRACT(YEAR FROM $1::date)::int - EXTRACT(YEAR FROM anchor_date)::int)
                              / interval_count
        END AS n_max
    FROM due
)
SELECT
    b.id                                      AS obligation_id,
    b.household_id,
    b.label,
    b.amount,
    b.category_id,
    COALESCE(b.posting_account_id, b.account_id)::uuid AS target_account_id,
    b.account_id                              AS source_account_id,
    -- The target's shape decides how much of the posting happens. A manual
    -- investment account gets the full treatment (transaction + investment
    -- transaction + balance move); anything else gets the transaction only,
    -- because an institution owns that balance and reports the movement itself.
    ta.type                                   AS target_type,
    ta.source                                 AS target_source,
    d.due_date::date                          AS due_date
FROM bounded b
JOIN accounts ta ON ta.id = COALESCE(b.posting_account_id, b.account_id)
                AND ta.is_active
CROSS JOIN LATERAL generate_series(0, GREATEST(b.n_max, 0)) AS g(n)
CROSS JOIN LATERAL (
    SELECT b.anchor_date + make_interval(
        days   => CASE b.interval_unit
                      WHEN 'day'  THEN g.n * b.interval_count
                      WHEN 'week' THEN g.n * b.interval_count * 7
                      ELSE 0 END,
        months => CASE b.interval_unit WHEN 'month' THEN g.n * b.interval_count ELSE 0 END,
        years  => CASE b.interval_unit WHEN 'year'  THEN g.n * b.interval_count ELSE 0 END
    ) AS due_date
) d
WHERE d.due_date <= $1::date
  AND (b.last_posted_date IS NULL OR d.due_date > b.last_posted_date)
  AND (b.end_date IS NULL OR d.due_date <= b.end_date)
  -- Bounds how far back a newly-enabled obligation reaches. Without it, turning
  -- auto-post on for a bill anchored in 2019 posts six years of transactions in
  -- one batch.
  AND d.due_date >= $2::date
ORDER BY b.id, d.due_date
`

type ListObligationsDueForPostingParams struct {
	Today    stdtime.Time `json:"today"`
	Earliest stdtime.Time `json:"earliest"`
}

type ListObligationsDueForPostingRow struct {
	ObligationID    uuid.UUID       `json:"obligation_id"`
	HouseholdID     uuid.UUID       `json:"household_id"`
	Label           string          `json:"label"`
	Amount          decimal.Decimal `json:"amount"`
	CategoryID      *uuid.UUID      `json:"category_id"`
	TargetAccountID uuid.UUID       `json:"target_account_id"`
	SourceAccountID *uuid.UUID      `json:"source_account_id"`
	TargetType      string          `json:"target_type"`
	TargetSource    string          `json:"target_source"`
	DueDate         stdtime.Time    `json:"due_date"`
}

// The worker's queue: every auto-posting obligation with at least one occurrence
// on or before today that has not been posted yet.
//
// Deliberately NOT household-scoped — this is a background sweep over every
// household, like the snapshot jobs. Nothing here is returned to a user;
// visibility is enforced when the resulting transactions are read.
//
// The occurrence expansion is the same arithmetic as ListUpcomingObligations,
// and for the same reason it lives in SQL: anchor_date + n whole periods
// clamps a month end (2025-01-31 + 1 month is 2025-02-28), where stepping from
// the previous occurrence would drift off the 31st permanently and Go's
// time.AddDate would roll forward into March.
func (q *Queries) ListObligationsDueForPosting(ctx context.Context, arg ListObligationsDueForPostingParams) ([]ListObligationsDueForPostingRow, error) {
	rows, err := q.db.Query(ctx, listObligationsDueForPosting, arg.Today, arg.Earliest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObligationsDueForPostingRow{}
	for rows.Next() {
		var i ListObligationsDueForPostingRow
		if err := rows.Scan(
			&i.ObligationID,
			&i.HouseholdID,
			&i.Label,
			&i.Amount,
			&i.CategoryID,
			&i.TargetAccountID,
			&i.SourceAccountID,
			&i.TargetType,
			&i.TargetSource,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionAccounts = `-- name: ListProjectionAccounts :many
SELECT
    a.id,
    a.name,
    a.mask,
    a.subtype,
    COALESCE(a.current_balance, 0)::numeric AS current_balance,
    v.institution_name
FROM accounts a
JOIN account_access v ON v.account_id = a.id
WHERE v.household_id = $1
  AND (v.user_id = $2 OR v.is_shared)
  AND a.is_active
  AND a.type = 'depository'
ORDER BY v.institution_name, a.name
`

type ListProjectionAccountsParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type ListProjectionAccountsRow struct {
	ID              uuid.UUID       `json:"id"`
	Name            string          `json:"name"`
	Mask            *string         `json:"mask"`
	Subtype         *string         `json:"subtype"`
	CurrentBalance  decimal.Decimal `json:"current_balance"`
	InstitutionName *string         `json:"institution_name"`
}

// The accounts a projected balance is meaningful for: depository only. Running
// the projection over a credit card would subtract that card's own bills from
// the balance those bills are *made of*, which is double-counting dressed as a
// forecast. Same visibility scoping as ListVisibleAccounts.
func (q *Queries) ListProjectionAccounts(ctx context.Context, arg ListProjectionAccountsParams) ([]ListProjectionAccountsRow, error) {
	rows, err := q.db.Query(ctx, listProjectionAccounts, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionAccountsRow{}
	for rows.Next() {
		var i ListProjectionAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mask,
			&i.Subtype,
			&i.CurrentBalance,
			&i.InstitutionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingObligations = `-- name: ListUpcomingObligations :many
WITH visible AS (
    SELECT id, household_id, user_id, is_shared, label, amount, category_id, account_id, interval_count, interval_unit, anchor_date, end_date, source, merchant_key, user_edited, is_active, created_at, updated_at, auto_post, last_posted_date, posting_account_id
    FROM recurring_obligations
    WHERE household_id = $1
      AND (user_id IS NULL OR user_id = $2 OR is_shared)
      AND is_active
),
bounded AS (
    SELECT
        visible.id, visible.household_id, visible.user_id, visible.is_shared, visible.label, visible.amount, visible.category_id, visible.account_id, visible.interval_count, visible.interval_unit, visible.anchor_date, visible.end_date, visible.source, visible.merchant_key, visible.user_edited, visible.is_active, visible.created_at, visible.updated_at, visible.auto_post, visible.last_posted_date, visible.posting_account_id,
        CASE interval_unit
            WHEN 'day'   THEN ($4::date - anchor_date) / interval_count
            WHEN 'week'  THEN ($4::date - anchor_date) / (7 * interval_count)
            WHEN 'month' THEN (12 * (EXTRACT(YEAR  FROM $4::date)::int - EXTRACT(YEAR  FROM anchor_date)::int)
                                  + (EXTRACT(MONTH FROM $4::date)::int - EXTRACT(MONTH FROM anchor_date)::int))
                              / interval_count
            WHEN 'year'  THEN (EXTRACT(YEAR FROM $4::date)::int - EXTRACT(YEAR FROM anchor_date)::int)
                              / interval_count
        END AS n_max
    FROM visible
)
SELECT
    b.id           AS obligation_id,
    b.label,
    b.amount,
    b.category_id,
    b.account_id,
    b.interval_count,
    b.interval_unit,
    b.source,
    b.merchant_key,
    d.due_date::date AS due_date
FROM bounded b
CROSS JOIN LATERAL generate_series(0, GREATEST(b.n_max, 0)) AS g(n)
CROSS JOIN LATERAL (
    SELECT b.anchor_date + make_interval(
        days   => CASE b.interval_unit
                      WHEN 'day'  THEN g.n * b.interval_count
                      WHEN 'week' THEN g.n * b.interval_count * 7
                      ELSE 0 END,
        months => CASE b.interval_unit WHEN 'month' THEN g.n * b.interval_count ELSE 0 END,
        years  => CASE b.interval_unit WHEN 'year'  THEN g.n * b.interval_count ELSE 0 END
    ) AS due_date
) d
WHERE d.due_date >= $3::date
  AND d.due_date <= $4::date
  AND (b.end_date IS NULL OR d.due_date <= b.end_date)
ORDER BY due_date, b.label
`

type ListUpcomingObligationsParams struct {
	HouseholdID uuid.UUID    `json:"household_id"`
	UserID      *uuid.UUID   `json:"user_id"`
	Column3     stdtime.Time `json:"column_3"`
	Column4     stdtime.Time `json:"column_4"`
}

type ListUpcomingObligationsRow struct {
	ObligationID  uuid.UUID       `json:"obligation_id"`
	Label         string          `json:"label"`
	Amount        decimal.Decimal `json:"amount"`
	CategoryID    *uuid.UUID      `json:"category_id"`
	AccountID     *uuid.UUID      `json:"account_id"`
	IntervalCount int32           `json:"interval_count"`
	IntervalUnit  string          `json:"interval_unit"`
	Source        string          `json:"source"`
	MerchantKey   *string         `json:"merchant_key"`
	DueDate       stdtime.Time    `json:"due_date"`
}

// One row per (obligation × occurrence) falling inside [$3, $4]. This single
// query backs the calendar, the list view, the balance projection, the
// safe-to-spend split and the upcoming-bill insight — there is deliberately no
// second variant to disagree with.
//
// How the expansion works, and why it is shaped this way:
//
//	n_max bounds how many steps could possibly land on or before $4, computed
//	per unit in whole units so it is exact and cheap. A window that ends before
//	anchor_date yields a negative bound, GREATEST clamps it to 0, and the WHERE
//	drops that single candidate — so a window entirely before the first
//	occurrence correctly returns nothing.
//
//	Each occurrence is anchor_date + n whole periods, NOT the previous
//	occurrence plus one period. That distinction is the whole month-end story:
//	generate_series over timestamps steps by repeated addition, so a monthly
//	obligation anchored on the 31st would walk 01-31, 02-28, 03-28, 04-28 and
//	drift permanently off the 31st. Multiplying the interval instead gives
//	01-31, 02-28, 03-31, 04-30 — clamped, never drifting.
func (q *Queries) ListUpcomingObligations(ctx context.Context, arg ListUpcomingObligationsParams) ([]ListUpcomingObligationsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingObligations,
		arg.HouseholdID,
		arg.UserID,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingObligationsRow{}
	for rows.Next() {
		var i ListUpcomingObligationsRow
		if err := rows.Scan(
			&i.ObligationID,
			&i.Label,
			&i.Amount,
			&i.CategoryID,
			&i.AccountID,
			&i.IntervalCount,
			&i.IntervalUnit,
			&i.Source,
			&i.MerchantKey,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markObligationPosted = `-- name: MarkObligationPosted :execrows
UPDATE recurring_obligations
SET last_posted_date = $1,
    updated_at       = now()
WHERE id = $2
  AND auto_post
  AND (last_posted_date IS NULL OR last_posted_date < $1)
`

type MarkObligationPostedParams struct {
	PostedThrough *stdtime.Time `json:"posted_through"`
	ID            uuid.UUID     `json:"id"`
}

// Advances the cursor. Runs in the same transaction as the rows it accounts
// for: a crash before the commit replays from the same cursor, and a crash
// after it has already written everything the cursor claims.
//
// The WHERE repeats the cursor predicate so two workers racing on one
// obligation produce exactly one winner, matching MarkAllowancePosted.
func (q *Queries) MarkObligationPosted(ctx context.Context, arg MarkObligationPostedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markObligationPosted, arg.PostedThrough, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setObligationActive = `-- name: SetObligationActive :one
UPDATE recurring_obligations
SET is_active = $4, user_edited = TRUE, updated_at = now()
WHERE id = $1 AND household_id = $2
  AND (user_id IS NULL OR user_id = $3 OR is_shared)
RETURNING id, household_id, user_id, is_shared, label, amount, category_id, account_id, interval_count, interval_unit, anchor_date, end_date, source, merchant_key, user_edited, is_active, created_at, updated_at, auto_post, last_posted_date, posting_account_id
`

type SetObligationActiveParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UserID      *uuid.UUID `json:"user_id"`
	IsActive    bool       `json:"is_active"`
}

// Deactivate rather than delete: a detected row that is hard-deleted comes
// straight back on the next promotion pass, and a deactivated one keeps the
// user's decision. user_edited is stamped for the same reason as UpdateObligation.
func (q *Queries) SetObligationActive(ctx context.Context, arg SetObligationActiveParams) (RecurringObligation, error) {
	row := q.db.QueryRow(ctx, setObligationActive,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
		arg.IsActive,
	)
	var i RecurringObligation
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.IsShared,
		&i.Label,
		&i.Amount,
		&i.CategoryID,
		&i.AccountID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.AnchorDate,
		&i.EndDate,
		&i.Source,
		&i.MerchantKey,
		&i.UserEdited,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoPost,
		&i.LastPostedDate,
		&i.PostingAccountID,
	)
	return i, err
}

const setObligationAutoPost = `-- name: SetObligationAutoPost :one

UPDATE recurring_obligations
SET auto_post          = $1,
    posting_account_id = $2,
    last_posted_date   = CASE WHEN $1 THEN last_posted_date ELSE NULL END,
    user_edited        = TRUE,
    updated_at         = now()
WHERE id = $3
  AND household_id = $4
  AND (user_id IS NULL OR user_id = $5 OR is_shared)
  -- An obligation cannot post without a target. The DB CHECK says the same
  -- thing; repeating it here turns a constraint violation into "no rows", which
  -- the handler reports as a 400 rather than a 500.
  AND (NOT $1
       OR $2::uuid IS NOT NULL
       OR account_id IS NOT NULL)
RETURNING id, household_id, user_id, is_shared, label, amount, category_id, account_id, interval_count, interval_unit, anchor_date, end_date, source, merchant_key, user_edited, is_active, created_at, updated_at, auto_post, last_posted_date, posting_account_id
`

type SetObligationAutoPostParams struct {
	AutoPost         bool       `json:"auto_post"`
	PostingAccountID *uuid.UUID `json:"posting_account_id"`
	ID               uuid.UUID  `json:"id"`
	HouseholdID      uuid.UUID  `json:"household_id"`
	UserID           *uuid.UUID `json:"user_id"`
}

// --------------------------------------------------------------------------
// Auto-posting (doc 30)
// --------------------------------------------------------------------------
// Turns materialisation on or off for one obligation, and names the account a
// posting credits. Separate from UpdateObligation because it is a different
// decision with a different blast radius: editing a label changes a forecast,
// turning this on starts writing transactions.
//
// last_posted_date is reset to NULL when auto_post is switched OFF, so
// re-enabling it later does not silently backfill every occurrence that fell in
// the gap. Re-enabling starts from the anchor's next due date, and the handler
// says so.
func (q *Queries) SetObligationAutoPost(ctx context.Context, arg SetObligationAutoPostParams) (RecurringObligation, error) {
	row := q.db.QueryRow(ctx, setObligationAutoPost,
		arg.AutoPost,
		arg.PostingAccountID,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
	)
	var i RecurringObligation
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.IsShared,
		&i.Label,
		&i.Amount,
		&i.CategoryID,
		&i.AccountID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.AnchorDate,
		&i.EndDate,
		&i.Source,
		&i.MerchantKey,
		&i.UserEdited,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoPost,
		&i.LastPostedDate,
		&i.PostingAccountID,
	)
	return i, err
}

const updateObligation = `-- name: UpdateObligation :one
UPDATE recurring_obligations
SET label          = $4,
    amount         = $5,
    category_id    = $6,
    account_id     = $7,
    interval_count = $8,
    interval_unit  = $9,
    anchor_date    = $10,
    end_date       = $11,
    is_shared      = $12,
    is_active      = $13,
    user_edited    = TRUE,
    updated_at     = now()
WHERE id = $1 AND household_id = $2
  AND (user_id IS NULL OR user_id = $3 OR is_shared)
RETURNING id, household_id, user_id, is_shared, label, amount, category_id, account_id, interval_count, interval_unit, anchor_date, end_date, source, merchant_key, user_edited, is_active, created_at, updated_at, auto_post, last_posted_date, posting_account_id
`

type UpdateObligationParams struct {
	ID            uuid.UUID       `json:"id"`
	HouseholdID   uuid.UUID       `json:"household_id"`
	UserID        *uuid.UUID      `json:"user_id"`
	Label         string          `json:"label"`
	Amount        decimal.Decimal `json:"amount"`
	CategoryID    *uuid.UUID      `json:"category_id"`
	AccountID     *uuid.UUID      `json:"account_id"`
	IntervalCount int32           `json:"interval_count"`
	IntervalUnit  string          `json:"interval_unit"`
	AnchorDate    stdtime.Time    `json:"anchor_date"`
	EndDate       *stdtime.Time   `json:"end_date"`
	IsShared      bool            `json:"is_shared"`
	IsActive      bool            `json:"is_active"`
}

// Edits from the UI. user_edited is stamped unconditionally: once a human has
// touched a row, the promotion pass must leave it alone forever, whether the
// edit changed a detected row's cadence or only its label.
func (q *Queries) UpdateObligation(ctx context.Context, arg UpdateObligationParams) (RecurringObligation, error) {
	row := q.db.QueryRow(ctx, updateObligation,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
		arg.Label,
		arg.Amount,
		arg.CategoryID,
		arg.AccountID,
		arg.IntervalCount,
		arg.IntervalUnit,
		arg.AnchorDate,
		arg.EndDate,
		arg.IsShared,
		arg.IsActive,
	)
	var i RecurringObligation
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.IsShared,
		&i.Label,
		&i.Amount,
		&i.CategoryID,
		&i.AccountID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.AnchorDate,
		&i.EndDate,
		&i.Source,
		&i.MerchantKey,
		&i.UserEdited,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoPost,
		&i.LastPostedDate,
		&i.PostingAccountID,
	)
	return i, err
}

const upsertDetectedObligation = `-- name: UpsertDetectedObligation :one
INSERT INTO recurring_obligations (
    household_id, user_id, is_shared, label, amount, category_id,
    interval_count, interval_unit, anchor_date, source, merchant_key
) VALUES ($1, NULL, TRUE, $2, $3, $4, $5, $6, $7, 'detected', $8)
ON CONFLICT (household_id, merchant_key) WHERE source = 'detected'
DO UPDATE SET
    label          = EXCLUDED.label,
    amount         = EXCLUDED.amount,
    category_id    = EXCLUDED.category_id,
    interval_count = EXCLUDED.interval_count,
    interval_unit  = EXCLUDED.interval_unit,
    anchor_date    = EXCLUDED.anchor_date,
    updated_at     = now()
WHERE NOT recurring_obligations.user_edited
RETURNING id, household_id, user_id, is_shared, label, amount, category_id, account_id, interval_count, interval_unit, anchor_date, end_date, source, merchant_key, user_edited, is_active, created_at, updated_at, auto_post, last_posted_date, posting_account_id
`

type UpsertDetectedObligationParams struct {
	HouseholdID   uuid.UUID       `json:"household_id"`
	Label         string          `json:"label"`
	Amount        decimal.Decimal `json:"amount"`
	CategoryID    *uuid.UUID      `json:"category_id"`
	IntervalCount int32           `json:"interval_count"`
	IntervalUnit  string          `json:"interval_unit"`
	AnchorDate    stdtime.Time    `json:"anchor_date"`
	MerchantKey   *string         `json:"merchant_key"`
}

// Promotion from the recurring detector. Idempotent by construction: the
// partial unique index on (household_id, merchant_key) WHERE source='detected'
// means a re-run updates the same row rather than adding a second one.
//
// The WHERE on the DO UPDATE is the load-bearing part. Without it the first pass
// after a user fixes a wrong cadence would silently put the wrong one back.
func (q *Queries) UpsertDetectedObligation(ctx context.Context, arg UpsertDetectedObligationParams) (RecurringObligation, error) {
	row := q.db.QueryRow(ctx, upsertDetectedObligation,
		arg.HouseholdID,
		arg.Label,
		arg.Amount,
		arg.CategoryID,
		arg.IntervalCount,
		arg.IntervalUnit,
		arg.AnchorDate,
		arg.MerchantKey,
	)
	var i RecurringObligation
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.IsShared,
		&i.Label,
		&i.Amount,
		&i.CategoryID,
		&i.AccountID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.AnchorDate,
		&i.EndDate,
		&i.Source,
		&i.MerchantKey,
		&i.UserEdited,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoPost,
		&i.LastPostedDate,
		&i.PostingAccountID,
	)
	return i, err
}
