// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: piggybanks.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

const createPiggyBank = `-- name: CreatePiggyBank :one

INSERT INTO piggy_banks (household_id, account_id, name, target_amount)
VALUES ($1, $2, $3, $4::numeric)
RETURNING id, household_id, account_id, name, target_amount, created_at
`

type CreatePiggyBankParams struct {
	HouseholdID  uuid.UUID           `json:"household_id"`
	AccountID    uuid.UUID           `json:"account_id"`
	Name         string              `json:"name"`
	TargetAmount decimal.NullDecimal `json:"target_amount"`
}

// Piggy banks: lightweight savings envelopes on an asset account.
//
// A piggy bank's current balance is DERIVED from its event log (deposits minus
// withdrawals), never stored — see 00061_piggy_banks.sql for why. Every read
// here sums the events in SQL, so a balance and the events behind it cannot
// disagree.
//
// Visibility is household-scoped, matching the spec: a piggy bank is a shared
// household object (there is no per-user or per-person scope the way goals
// have). The account it sits on is itself household-scoped through
// account_access, and every query here re-checks household_id on the piggy
// bank row so a caller can never read or move another household's jar.
func (q *Queries) CreatePiggyBank(ctx context.Context, arg CreatePiggyBankParams) (PiggyBank, error) {
	row := q.db.QueryRow(ctx, createPiggyBank,
		arg.HouseholdID,
		arg.AccountID,
		arg.Name,
		arg.TargetAmount,
	)
	var i PiggyBank
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.TargetAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createPiggyBankEvent = `-- name: CreatePiggyBankEvent :one
INSERT INTO piggy_bank_events (piggy_bank_id, type, amount, transaction_id)
VALUES ($1, $2, $3::numeric, $4)
RETURNING id, piggy_bank_id, type, amount, transaction_id, created_at
`

type CreatePiggyBankEventParams struct {
	PiggyBankID   uuid.UUID       `json:"piggy_bank_id"`
	Type          string          `json:"type"`
	Amount        decimal.Decimal `json:"amount"`
	TransactionID *uuid.UUID      `json:"transaction_id"`
}

// Append-only. type and amount come from the caller; ownership is checked in
// the handler via GetPiggyBank before this runs, and both run inside one
// transaction so a withdrawal's balance check and its event land together.
func (q *Queries) CreatePiggyBankEvent(ctx context.Context, arg CreatePiggyBankEventParams) (PiggyBankEvent, error) {
	row := q.db.QueryRow(ctx, createPiggyBankEvent,
		arg.PiggyBankID,
		arg.Type,
		arg.Amount,
		arg.TransactionID,
	)
	var i PiggyBankEvent
	err := row.Scan(
		&i.ID,
		&i.PiggyBankID,
		&i.Type,
		&i.Amount,
		&i.TransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const deletePiggyBank = `-- name: DeletePiggyBank :execrows
DELETE FROM piggy_banks WHERE id = $1 AND household_id = $2
`

type DeletePiggyBankParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

// Hard delete; the event log cascades away with it. A piggy bank is casual by
// design — closing one out (you bought the laptop) is deletion, not archiving,
// and the money is already in the account so there is nothing to reconcile.
func (q *Queries) DeletePiggyBank(ctx context.Context, arg DeletePiggyBankParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePiggyBank, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountAvailableForPiggy = `-- name: GetAccountAvailableForPiggy :one
SELECT
    (COALESCE(a.current_balance, 0)
     - COALESCE((
         SELECT (COALESCE(SUM(e.amount) FILTER (WHERE e.type = 'deposit'), 0)
               - COALESCE(SUM(e.amount) FILTER (WHERE e.type = 'withdraw'), 0))::numeric
         FROM piggy_bank_events e
         JOIN piggy_banks p ON p.id = e.piggy_bank_id
         WHERE p.account_id = a.id AND p.household_id = v.household_id
       ), 0))::numeric AS available,
    COALESCE(a.current_balance, 0)::numeric AS account_balance,
    COALESCE((
         SELECT (COALESCE(SUM(e.amount) FILTER (WHERE e.type = 'deposit'), 0)
               - COALESCE(SUM(e.amount) FILTER (WHERE e.type = 'withdraw'), 0))::numeric
         FROM piggy_bank_events e
         JOIN piggy_banks p ON p.id = e.piggy_bank_id
         WHERE p.account_id = a.id AND p.household_id = v.household_id
       ), 0)::numeric AS assigned
FROM accounts a
JOIN account_access v ON v.account_id = a.id
WHERE a.id = $1 AND v.household_id = $2
  AND a.type NOT IN ('credit', 'loan')
`

type GetAccountAvailableForPiggyParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetAccountAvailableForPiggyRow struct {
	Available      decimal.Decimal `json:"available"`
	AccountBalance decimal.Decimal `json:"account_balance"`
	Assigned       decimal.Decimal `json:"assigned"`
}

// The unused balance on an account: its current balance minus the sum of every
// piggy bank's derived balance drawing from it. Negative means the household
// has earmarked more than the account holds — the over-allocation case the UI
// must surface as a loud warning, never a silently clipped number.
//
// Restricted to asset accounts (type NOT IN credit/loan): a piggy bank is money
// held, not owed, and the create path rejects a debt account. The household
// join is through account_access, the same view every other account read uses.
func (q *Queries) GetAccountAvailableForPiggy(ctx context.Context, arg GetAccountAvailableForPiggyParams) (GetAccountAvailableForPiggyRow, error) {
	row := q.db.QueryRow(ctx, getAccountAvailableForPiggy, arg.ID, arg.HouseholdID)
	var i GetAccountAvailableForPiggyRow
	err := row.Scan(&i.Available, &i.AccountBalance, &i.Assigned)
	return i, err
}

const getPiggyBank = `-- name: GetPiggyBank :one
SELECT
    p.id, p.household_id, p.account_id, p.name, p.target_amount, p.created_at,
    (COALESCE((SELECT SUM(e.amount) FROM piggy_bank_events e
               WHERE e.piggy_bank_id = p.id AND e.type = 'deposit'), 0)
   - COALESCE((SELECT SUM(e.amount) FROM piggy_bank_events e
               WHERE e.piggy_bank_id = p.id AND e.type = 'withdraw'), 0))::numeric AS current_amount
FROM piggy_banks p
WHERE p.id = $1 AND p.household_id = $2
`

type GetPiggyBankParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetPiggyBankRow struct {
	ID            uuid.UUID           `json:"id"`
	HouseholdID   uuid.UUID           `json:"household_id"`
	AccountID     uuid.UUID           `json:"account_id"`
	Name          string              `json:"name"`
	TargetAmount  decimal.NullDecimal `json:"target_amount"`
	CreatedAt     stdtime.Time        `json:"created_at"`
	CurrentAmount decimal.Decimal     `json:"current_amount"`
}

// One piggy bank plus its DERIVED current balance, scoped to the household.
// The deposit/withdraw handlers read this to validate ownership and (for a
// withdrawal) to check the balance covers the amount.
func (q *Queries) GetPiggyBank(ctx context.Context, arg GetPiggyBankParams) (GetPiggyBankRow, error) {
	row := q.db.QueryRow(ctx, getPiggyBank, arg.ID, arg.HouseholdID)
	var i GetPiggyBankRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.TargetAmount,
		&i.CreatedAt,
		&i.CurrentAmount,
	)
	return i, err
}

const listPiggyBankEvents = `-- name: ListPiggyBankEvents :many
SELECT e.id, e.piggy_bank_id, e.type, e.amount, e.transaction_id, e.created_at
FROM piggy_bank_events e
JOIN piggy_banks p ON p.id = e.piggy_bank_id
WHERE e.piggy_bank_id = $1 AND p.household_id = $2
ORDER BY e.created_at DESC
`

type ListPiggyBankEventsParams struct {
	PiggyBankID uuid.UUID `json:"piggy_bank_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ListPiggyBankEvents(ctx context.Context, arg ListPiggyBankEventsParams) ([]PiggyBankEvent, error) {
	rows, err := q.db.Query(ctx, listPiggyBankEvents, arg.PiggyBankID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PiggyBankEvent{}
	for rows.Next() {
		var i PiggyBankEvent
		if err := rows.Scan(
			&i.ID,
			&i.PiggyBankID,
			&i.Type,
			&i.Amount,
			&i.TransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPiggyBanks = `-- name: ListPiggyBanks :many
SELECT
    p.id, p.household_id, p.account_id, p.name, p.target_amount, p.created_at,
    (COALESCE(SUM(e.amount) FILTER (WHERE e.type = 'deposit'), 0)
   - COALESCE(SUM(e.amount) FILTER (WHERE e.type = 'withdraw'), 0))::numeric AS current_amount
FROM piggy_banks p
LEFT JOIN piggy_bank_events e ON e.piggy_bank_id = p.id
WHERE p.household_id = $1
GROUP BY p.id
ORDER BY p.created_at DESC
`

type ListPiggyBanksRow struct {
	ID            uuid.UUID           `json:"id"`
	HouseholdID   uuid.UUID           `json:"household_id"`
	AccountID     uuid.UUID           `json:"account_id"`
	Name          string              `json:"name"`
	TargetAmount  decimal.NullDecimal `json:"target_amount"`
	CreatedAt     stdtime.Time        `json:"created_at"`
	CurrentAmount decimal.Decimal     `json:"current_amount"`
}

// Every piggy bank in the household with its DERIVED current balance. The
// balance is deposits minus withdrawals, summed here in SQL; the outer
// ::numeric cast is the one proven place for it (casting each COALESCE
// separately leaves sqlc unable to infer the result type).
func (q *Queries) ListPiggyBanks(ctx context.Context, householdID uuid.UUID) ([]ListPiggyBanksRow, error) {
	rows, err := q.db.Query(ctx, listPiggyBanks, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPiggyBanksRow{}
	for rows.Next() {
		var i ListPiggyBanksRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.AccountID,
			&i.Name,
			&i.TargetAmount,
			&i.CreatedAt,
			&i.CurrentAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPiggyBanksForAccount = `-- name: ListPiggyBanksForAccount :many
SELECT
    p.id, p.household_id, p.account_id, p.name, p.target_amount, p.created_at,
    (COALESCE(SUM(e.amount) FILTER (WHERE e.type = 'deposit'), 0)
   - COALESCE(SUM(e.amount) FILTER (WHERE e.type = 'withdraw'), 0))::numeric AS current_amount
FROM piggy_banks p
LEFT JOIN piggy_bank_events e ON e.piggy_bank_id = p.id
WHERE p.household_id = $1 AND p.account_id = $2
GROUP BY p.id
ORDER BY p.created_at DESC
`

type ListPiggyBanksForAccountParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	AccountID   uuid.UUID `json:"account_id"`
}

type ListPiggyBanksForAccountRow struct {
	ID            uuid.UUID           `json:"id"`
	HouseholdID   uuid.UUID           `json:"household_id"`
	AccountID     uuid.UUID           `json:"account_id"`
	Name          string              `json:"name"`
	TargetAmount  decimal.NullDecimal `json:"target_amount"`
	CreatedAt     stdtime.Time        `json:"created_at"`
	CurrentAmount decimal.Decimal     `json:"current_amount"`
}

// The piggy banks drawing from one account. household_id is on the piggy bank,
// so even an account_id from outside the household yields no rows — no separate
// account-visibility check is needed to keep this safe.
func (q *Queries) ListPiggyBanksForAccount(ctx context.Context, arg ListPiggyBanksForAccountParams) ([]ListPiggyBanksForAccountRow, error) {
	rows, err := q.db.Query(ctx, listPiggyBanksForAccount, arg.HouseholdID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPiggyBanksForAccountRow{}
	for rows.Next() {
		var i ListPiggyBanksForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.AccountID,
			&i.Name,
			&i.TargetAmount,
			&i.CreatedAt,
			&i.CurrentAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePiggyBank = `-- name: UpdatePiggyBank :one
UPDATE piggy_banks
SET name = $1,
    target_amount = $2::numeric
WHERE id = $3 AND household_id = $4
RETURNING id, household_id, account_id, name, target_amount, created_at
`

type UpdatePiggyBankParams struct {
	Name         string              `json:"name"`
	TargetAmount decimal.NullDecimal `json:"target_amount"`
	ID           uuid.UUID           `json:"id"`
	HouseholdID  uuid.UUID           `json:"household_id"`
}

// Name and target only. The account is fixed at create time: moving a jar
// between accounts would detach it from the events' funding account, and the
// available-for-piggy math is per-account.
func (q *Queries) UpdatePiggyBank(ctx context.Context, arg UpdatePiggyBankParams) (PiggyBank, error) {
	row := q.db.QueryRow(ctx, updatePiggyBank,
		arg.Name,
		arg.TargetAmount,
		arg.ID,
		arg.HouseholdID,
	)
	var i PiggyBank
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.AccountID,
		&i.Name,
		&i.TargetAmount,
		&i.CreatedAt,
	)
	return i, err
}
