// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: splits.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

const createTransactionSplit = `-- name: CreateTransactionSplit :one
INSERT INTO transaction_splits (transaction_id, person_id, amount)
SELECT t.id, p.id, $1::numeric
FROM transactions t
JOIN accounts a     ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
JOIN household_people p
  ON p.id = $2 AND p.household_id = v.household_id
WHERE t.id = $3
  AND v.household_id = $4
RETURNING id, transaction_id, person_id, amount, settled_at, created_at
`

type CreateTransactionSplitParams struct {
	Amount        decimal.Decimal `json:"amount"`
	PersonID      uuid.UUID       `json:"person_id"`
	TransactionID uuid.UUID       `json:"transaction_id"`
	HouseholdID   uuid.UUID       `json:"household_id"`
}

// Both the transaction and the person are re-resolved through the household
// guard rather than trusted from the request.
func (q *Queries) CreateTransactionSplit(ctx context.Context, arg CreateTransactionSplitParams) (TransactionSplit, error) {
	row := q.db.QueryRow(ctx, createTransactionSplit,
		arg.Amount,
		arg.PersonID,
		arg.TransactionID,
		arg.HouseholdID,
	)
	var i TransactionSplit
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.PersonID,
		&i.Amount,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionForSplit = `-- name: GetTransactionForSplit :one
SELECT t.id, t.amount, t.name, t.date, v.user_id AS payer_user_id
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
WHERE t.id = $1 AND v.household_id = $2
`

type GetTransactionForSplitParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetTransactionForSplitRow struct {
	ID          uuid.UUID       `json:"id"`
	Amount      decimal.Decimal `json:"amount"`
	Name        string          `json:"name"`
	Date        stdtime.Time    `json:"date"`
	PayerUserID uuid.UUID       `json:"payer_user_id"`
}

// The transaction a split is being written against, scoped to the household.
// The handler needs `amount` to assert the shares sum exactly.
func (q *Queries) GetTransactionForSplit(ctx context.Context, arg GetTransactionForSplitParams) (GetTransactionForSplitRow, error) {
	row := q.db.QueryRow(ctx, getTransactionForSplit, arg.ID, arg.HouseholdID)
	var i GetTransactionForSplitRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Name,
		&i.Date,
		&i.PayerUserID,
	)
	return i, err
}

const householdLedger = `-- name: HouseholdLedger :many
SELECT
    debtor.id            AS debtor_id,
    debtor.display_name  AS debtor_name,
    creditor.id          AS creditor_id,
    creditor.display_name AS creditor_name,
    SUM(s.amount)::numeric AS amount
FROM transaction_splits s
JOIN transactions t ON t.id = s.transaction_id
JOIN accounts a     ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
JOIN household_people debtor   ON debtor.id = s.person_id
JOIN household_people creditor ON creditor.user_id = v.user_id
WHERE v.household_id = $1
  AND s.settled_at IS NULL
  AND debtor.id <> creditor.id
GROUP BY debtor.id, debtor.display_name, creditor.id, creditor.display_name
HAVING SUM(s.amount) <> 0
ORDER BY debtor.display_name, creditor.display_name
`

type HouseholdLedgerRow struct {
	DebtorID     uuid.UUID       `json:"debtor_id"`
	DebtorName   string          `json:"debtor_name"`
	CreditorID   uuid.UUID       `json:"creditor_id"`
	CreditorName string          `json:"creditor_name"`
	Amount       decimal.Decimal `json:"amount"`
}

// Who owes whom. One row per (debtor, creditor) pair with an outstanding
// balance: the debtor is the person the share was assigned to, the creditor is
// the person whose account actually paid.
//
// A share assigned to the payer themselves is excluded — you do not owe
// yourself, and including it would inflate every balance by the payer's own
// portion. Settled shares drop out because settlement is what "this is done"
// means; the row is kept for history, not for the balance.
func (q *Queries) HouseholdLedger(ctx context.Context, householdID uuid.UUID) ([]HouseholdLedgerRow, error) {
	rows, err := q.db.Query(ctx, householdLedger, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdLedgerRow{}
	for rows.Next() {
		var i HouseholdLedgerRow
		if err := rows.Scan(
			&i.DebtorID,
			&i.DebtorName,
			&i.CreditorID,
			&i.CreditorName,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonSplits = `-- name: ListPersonSplits :many
SELECT
    s.id,
    s.amount,
    s.settled_at,
    t.id   AS transaction_id,
    t.name AS transaction_name,
    t.date,
    t.amount AS transaction_amount
FROM transaction_splits s
JOIN transactions t ON t.id = s.transaction_id
JOIN household_people p ON p.id = s.person_id
WHERE s.person_id = $1
  AND p.household_id = $2
ORDER BY t.date DESC
LIMIT $3
`

type ListPersonSplitsParams struct {
	PersonID    uuid.UUID `json:"person_id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Limit       int32     `json:"limit"`
}

type ListPersonSplitsRow struct {
	ID                uuid.UUID       `json:"id"`
	Amount            decimal.Decimal `json:"amount"`
	SettledAt         *stdtime.Time   `json:"settled_at"`
	TransactionID     uuid.UUID       `json:"transaction_id"`
	TransactionName   string          `json:"transaction_name"`
	Date              stdtime.Time    `json:"date"`
	TransactionAmount decimal.Decimal `json:"transaction_amount"`
}

// One person's share of shared expenses. This is the ONLY kind of query that
// may read splits for a spending figure, and it is explicitly per-person —
// never summed into a household total.
func (q *Queries) ListPersonSplits(ctx context.Context, arg ListPersonSplitsParams) ([]ListPersonSplitsRow, error) {
	rows, err := q.db.Query(ctx, listPersonSplits, arg.PersonID, arg.HouseholdID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonSplitsRow{}
	for rows.Next() {
		var i ListPersonSplitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.SettledAt,
			&i.TransactionID,
			&i.TransactionName,
			&i.Date,
			&i.TransactionAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSplitTransactions = `-- name: ListSplitTransactions :many
SELECT
    t.id,
    t.name,
    t.date,
    t.amount,
    v.user_id AS payer_user_id,
    payer.display_name AS payer_name,
    count(s.id)::bigint AS split_count,
    count(s.id) FILTER (WHERE s.settled_at IS NULL)::bigint AS unsettled_count
FROM transactions t
JOIN transaction_splits s ON s.transaction_id = t.id
JOIN accounts a    ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
LEFT JOIN household_people payer ON payer.user_id = v.user_id
WHERE v.household_id = $1
GROUP BY t.id, t.name, t.date, t.amount, v.user_id, payer.display_name
ORDER BY t.date DESC, t.id
LIMIT $2
`

type ListSplitTransactionsParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Limit       int32     `json:"limit"`
}

type ListSplitTransactionsRow struct {
	ID             uuid.UUID       `json:"id"`
	Name           string          `json:"name"`
	Date           stdtime.Time    `json:"date"`
	Amount         decimal.Decimal `json:"amount"`
	PayerUserID    uuid.UUID       `json:"payer_user_id"`
	PayerName      *string         `json:"payer_name"`
	SplitCount     int64           `json:"split_count"`
	UnsettledCount int64           `json:"unsettled_count"`
}

// Every transaction in the household that carries splits, newest first. Powers
// the "shared expenses" filter.
func (q *Queries) ListSplitTransactions(ctx context.Context, arg ListSplitTransactionsParams) ([]ListSplitTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listSplitTransactions, arg.HouseholdID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSplitTransactionsRow{}
	for rows.Next() {
		var i ListSplitTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Amount,
			&i.PayerUserID,
			&i.PayerName,
			&i.SplitCount,
			&i.UnsettledCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSplitsForTransaction = `-- name: ListSplitsForTransaction :many
SELECT s.id, s.transaction_id, s.person_id, s.amount, s.settled_at, s.created_at, p.display_name
FROM transaction_splits s
JOIN household_people p ON p.id = s.person_id
WHERE s.transaction_id = $1 AND p.household_id = $2
ORDER BY p.display_name
`

type ListSplitsForTransactionParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	HouseholdID   uuid.UUID `json:"household_id"`
}

type ListSplitsForTransactionRow struct {
	ID            uuid.UUID       `json:"id"`
	TransactionID uuid.UUID       `json:"transaction_id"`
	PersonID      uuid.UUID       `json:"person_id"`
	Amount        decimal.Decimal `json:"amount"`
	SettledAt     *stdtime.Time   `json:"settled_at"`
	CreatedAt     stdtime.Time    `json:"created_at"`
	DisplayName   string          `json:"display_name"`
}

func (q *Queries) ListSplitsForTransaction(ctx context.Context, arg ListSplitsForTransactionParams) ([]ListSplitsForTransactionRow, error) {
	rows, err := q.db.Query(ctx, listSplitsForTransaction, arg.TransactionID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSplitsForTransactionRow{}
	for rows.Next() {
		var i ListSplitsForTransactionRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.PersonID,
			&i.Amount,
			&i.SettledAt,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceTransactionSplits = `-- name: ReplaceTransactionSplits :exec

DELETE FROM transaction_splits WHERE transaction_id = $1
`

// Bill split and the household reimbursement ledger.
//
// A split is an ATTRIBUTION OVERLAY. The transaction happened once, on one
// account, and household spending totals must be unchanged by splitting it.
// Nothing in this file is joined into a spending aggregate, and nothing should
// be — only per-person views consult these rows. Anything else and the app
// starts inflating spend the same way un-typed transfers used to.
//
// Balances are DERIVED by summing unsettled shares. There is no stored balance.
// Splits are written as a set: the API resolves exact amounts, asserts they sum
// to the transaction, and replaces whatever was there. Editing a split in place
// would allow a partial write that no longer sums.
func (q *Queries) ReplaceTransactionSplits(ctx context.Context, transactionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceTransactionSplits, transactionID)
	return err
}

const settleSplit = `-- name: SettleSplit :execrows
UPDATE transaction_splits s
SET settled_at = now()
FROM household_people p
WHERE s.id = $1
  AND p.id = s.person_id
  AND p.household_id = $2
  AND s.settled_at IS NULL
`

type SettleSplitParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) SettleSplit(ctx context.Context, arg SettleSplitParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleSplit, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unsettleSplit = `-- name: UnsettleSplit :execrows
UPDATE transaction_splits s
SET settled_at = NULL
FROM household_people p
WHERE s.id = $1
  AND p.id = s.person_id
  AND p.household_id = $2
`

type UnsettleSplitParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) UnsettleSplit(ctx context.Context, arg UnsettleSplitParams) (int64, error) {
	result, err := q.db.Exec(ctx, unsettleSplit, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
