// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

const addTransactionTag = `-- name: AddTransactionTag :execrows
INSERT INTO transaction_tags (transaction_id, tag_id)
SELECT tr.id, tg.id
FROM transactions tr
JOIN accounts a       ON a.id = tr.account_id
JOIN account_access v ON v.account_id = a.id
JOIN tags tg          ON tg.id = $1
WHERE tr.id = $2
  AND v.household_id = $3
  AND (v.user_id = $4 OR v.is_shared)
  AND tg.household_id = $3
ON CONFLICT DO NOTHING
`

type AddTransactionTagParams struct {
	TagID         uuid.UUID `json:"tag_id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	HouseholdID   uuid.UUID `json:"household_id"`
	UserID        uuid.UUID `json:"user_id"`
}

// Labels one transaction with one tag.
//
// Both scopes are enforced in the SELECT, so this cannot be used to reach across
// a boundary even with two valid-looking ids: the tag must belong to the
// caller's household, and the transaction must be visible to the caller. A miss
// on either inserts nothing and returns 0 rows.
//
// ON CONFLICT DO NOTHING makes re-applying a tag idempotent — the composite
// primary key already forbids the duplicate; this just means the caller does not
// have to care whether the label was already there.
func (q *Queries) AddTransactionTag(ctx context.Context, arg AddTransactionTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTransactionTag,
		arg.TagID,
		arg.TransactionID,
		arg.HouseholdID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyTagToMerchant = `-- name: ApplyTagToMerchant :execrows
INSERT INTO transaction_tags (transaction_id, tag_id)
SELECT tr.id, tg.id
FROM transactions tr
JOIN accounts a       ON a.id = tr.account_id
JOIN account_access v ON v.account_id = a.id
JOIN tags tg          ON tg.id = $1
WHERE tr.merchant_key = $2
  AND v.household_id = $3
  AND (v.user_id = $4 OR v.is_shared)
  AND tg.household_id = $3
ON CONFLICT DO NOTHING
`

type ApplyTagToMerchantParams struct {
	TagID       uuid.UUID `json:"tag_id"`
	MerchantKey *string   `json:"merchant_key"`
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// Adds one tag to every visible transaction sharing a merchant descriptor — the
// tag half of "apply to all from this merchant".
//
// It ADDS rather than replaces, which is the one place tags and categories
// differ on this action and the difference is deliberate. A category is
// single-valued, so applying one to a merchant necessarily overwrites. A tag is
// one of several, so replacing would silently strip labels somebody else put on
// those charges for unrelated reasons ("Reimbursable" wiped by "Groceries
// 2026"). Adding is the only version of this that cannot destroy work.
//
// Scoped both ways, exactly like AddTransactionTag: only the caller's own
// household's tag, only transactions the caller can see.
func (q *Queries) ApplyTagToMerchant(ctx context.Context, arg ApplyTagToMerchantParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyTagToMerchant,
		arg.TagID,
		arg.MerchantKey,
		arg.HouseholdID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearTransactionTags = `-- name: ClearTransactionTags :exec
DELETE FROM transaction_tags tt
USING transactions tr, accounts a, account_access v
WHERE tt.transaction_id = $1
  AND tr.id = tt.transaction_id
  AND a.id = tr.account_id
  AND v.account_id = a.id
  AND v.household_id = $2
  AND (v.user_id = $3 OR v.is_shared)
`

type ClearTransactionTagsParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	HouseholdID   uuid.UUID `json:"household_id"`
	UserID        uuid.UUID `json:"user_id"`
}

// Removes every tag from one transaction, as the first half of "set the tags to
// exactly this list". The transaction is re-checked against the caller's
// visibility here rather than trusted from an earlier read, so this statement is
// safe on its own: a transaction the caller cannot see matches nothing and the
// delete is a no-op.
func (q *Queries) ClearTransactionTags(ctx context.Context, arg ClearTransactionTagsParams) error {
	_, err := q.db.Exec(ctx, clearTransactionTags, arg.TransactionID, arg.HouseholdID, arg.UserID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (household_id, name, description, expected_amount)
VALUES ($1, $2, $3,
        $4)
RETURNING id
`

type CreateTagParams struct {
	HouseholdID    uuid.UUID           `json:"household_id"`
	Name           string              `json:"name"`
	Description    *string             `json:"description"`
	ExpectedAmount decimal.NullDecimal `json:"expected_amount"`
}

// Returns the id only: the response is then re-read through ListTags, so a newly
// created tag is rendered by the same code path (and the same aggregate
// definitions) as one that has existed for a year.
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.HouseholdID,
		arg.Name,
		arg.Description,
		arg.ExpectedAmount,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = $1 AND household_id = $2
`

type DeleteTagParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

// transaction_tags cascades, so deleting a tag unlabels its transactions and
// leaves the transactions themselves untouched. :execrows returns 0 for another
// household's id, which the handler maps to 404.
func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTagTransactions = `-- name: ListTagTransactions :many
SELECT
    tr.id,
    tr.date,
    tr.name,
    COALESCE(me.canonical_name, tr.merchant_name, tr.name) AS merchant,
    tr.amount,
    tr.currency,
    tr.category_id,
    a.name AS account_name
FROM transaction_tags tt
JOIN transactions tr  ON tr.id = tt.transaction_id
JOIN accounts a       ON a.id = tr.account_id
JOIN account_access v ON v.account_id = a.id
LEFT JOIN merchant_aliases ma
       ON ma.household_id = $1
      AND ma.merchant_key = tr.merchant_key
      AND ma.source <> 'suggested'
LEFT JOIN merchant_entities me ON me.id = ma.entity_id
WHERE tt.tag_id = $2
  AND v.household_id = $1
  AND (v.user_id = $3 OR v.is_shared)
  AND a.is_active
  AND NOT tr.excluded_from_reports
ORDER BY tr.date DESC, tr.created_at DESC
LIMIT $4
`

type ListTagTransactionsParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	TagID       uuid.UUID `json:"tag_id"`
	UserID      uuid.UUID `json:"user_id"`
	Lim         int32     `json:"lim"`
}

type ListTagTransactionsRow struct {
	ID          uuid.UUID       `json:"id"`
	Date        stdtime.Time    `json:"date"`
	Name        string          `json:"name"`
	Merchant    string          `json:"merchant"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	CategoryID  *uuid.UUID      `json:"category_id"`
	AccountName string          `json:"account_name"`
}

// Every visible transaction carrying one tag, newest first — the tag detail
// list, and the "show me the trip" drill-down.
//
// Unlike the reporting queries this does NOT drop income, transfers or pending
// rows: it is a ledger view, and a refund that was part of the trip belongs in
// the list of what the trip involved. Excluded rows stay hidden, matching the
// default ledger.
func (q *Queries) ListTagTransactions(ctx context.Context, arg ListTagTransactionsParams) ([]ListTagTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTagTransactions,
		arg.HouseholdID,
		arg.TagID,
		arg.UserID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagTransactionsRow{}
	for rows.Next() {
		var i ListTagTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Name,
			&i.Merchant,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many

SELECT
    t.id,
    t.name,
    t.description,
    t.expected_amount,
    t.created_at,
    (
        SELECT COUNT(*)::bigint
        FROM transaction_tags tt
        JOIN transactions tr    ON tr.id = tt.transaction_id
        JOIN accounts a         ON a.id = tr.account_id
        JOIN account_access v   ON v.account_id = a.id
        WHERE tt.tag_id = t.id
          AND v.household_id = $1
          AND (v.user_id = $2 OR v.is_shared)
          AND a.is_active
    ) AS transaction_count,
    (
        SELECT COALESCE(SUM(ABS(tr.amount)), 0)::numeric
        FROM transaction_tags tt
        JOIN transactions tr    ON tr.id = tt.transaction_id
        JOIN accounts a         ON a.id = tr.account_id
        JOIN account_access v   ON v.account_id = a.id
        LEFT JOIN categories c  ON c.id = tr.category_id
        WHERE tt.tag_id = t.id
          AND v.household_id = $1
          AND (v.user_id = $2 OR v.is_shared)
          AND a.is_active
          AND NOT tr.excluded_from_reports
          AND NOT tr.pending
          AND NOT COALESCE(c.is_income, FALSE)
          AND NOT COALESCE(c.is_transfer, FALSE)
          AND is_spend(tr.amount, a.type)
    ) AS total
FROM tags t
WHERE t.household_id = $1
  -- NULL means "every tag"; an id narrows to one. A tag id from another
  -- household is filtered out by the household guard above rather than by this
  -- clause, so it comes back as an empty result — indistinguishable from an id
  -- that never existed, which is what the handler turns into a 404.
  AND ($3::uuid IS NULL OR t.id = $3::uuid)
ORDER BY lower(t.name)
`

type ListTagsParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	UserID      uuid.UUID  `json:"user_id"`
	ID          *uuid.UUID `json:"id"`
}

type ListTagsRow struct {
	ID               uuid.UUID           `json:"id"`
	Name             string              `json:"name"`
	Description      *string             `json:"description"`
	ExpectedAmount   decimal.NullDecimal `json:"expected_amount"`
	CreatedAt        stdtime.Time        `json:"created_at"`
	TransactionCount int64               `json:"transaction_count"`
	Total            decimal.Decimal     `json:"total"`
}

// Tag queries.
//
// Two scoping rules run through every statement here, and they are different
// rules on purpose:
//
//   - A TAG is household-scoped. Every read and write is guarded by
//     household_id = $1, so a tag id from another household matches nothing.
//   - A TAGGED TRANSACTION is visibility-scoped, exactly like every other
//     transaction read: account_access with
//     (v.user_id = $2 OR v.is_shared). A tag is a label, not an escape hatch —
//     labelling a charge on a private account must not make that charge, or its
//     amount, readable by the other member.
//
// So both members see the tag "Summer Vacation"; each member's count and total
// for it are computed over the rows that member was already allowed to see.
// Every query below that touches transactions therefore takes the viewer's user
// id as well as the household id.
// Every tag in the household, with the two figures the management page and the
// tag picker need, both computed for THIS viewer.
//
// This also serves the single-tag read, via the optional `id` narg. There is no
// separate GetTag on purpose: a second statement would have to repeat the two
// aggregate subqueries below, and the day one of them was fixed and the other
// was not, a tag's total would depend on which endpoint you asked. One query,
// one definition of the numbers.
//
// The two numbers deliberately answer different questions:
//
//	transaction_count — how many visible transactions carry this tag. A fact
//	  about the LABEL, so it counts every tagged row: income, transfers and
//	  pending ones included. "You put this on 14 things" must not silently
//	  become 11 because three of them were refunds.
//
//	total — what this tag has COST, all-time. A fact about the MONEY, so it
//	  obeys the same rules as every other spending figure in the app: excluded
//	  rows dropped, pending dropped, income and transfer categories dropped,
//	  direction from is_spend so a loan payment counts as an outflow. This is
//	  the figure that reads against expected_amount, and it must reconcile with
//	  GetSpendingByTag over an unbounded window.
//
// The two aggregates are computed in separate scalar subqueries rather than one
// join, because joining both would multiply the rows and inflate whichever
// aggregate is not the one being filtered.
func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, arg.HouseholdID, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ExpectedAmount,
			&i.CreatedAt,
			&i.TransactionCount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTransactions = `-- name: ListTagsForTransactions :many
SELECT tt.transaction_id, t.id AS tag_id, t.name
FROM transaction_tags tt
JOIN tags t ON t.id = tt.tag_id
WHERE tt.transaction_id = ANY($1::uuid[])
  AND t.household_id = $2
ORDER BY lower(t.name)
`

type ListTagsForTransactionsParams struct {
	TransactionIds []uuid.UUID `json:"transaction_ids"`
	HouseholdID    uuid.UUID   `json:"household_id"`
}

type ListTagsForTransactionsRow struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	TagID         uuid.UUID `json:"tag_id"`
	Name          string    `json:"name"`
}

// Every (transaction, tag) pair for a page of transactions, in one round trip.
//
// This is what keeps tag chips off the N+1 path: the ledger renders fifty rows
// and asks for their labels once, rather than once per row. The transaction ids
// come from a list the caller has ALREADY read under the visibility predicate,
// and the household guard here means an id smuggled in from elsewhere returns
// nothing.
func (q *Queries) ListTagsForTransactions(ctx context.Context, arg ListTagsForTransactionsParams) ([]ListTagsForTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTagsForTransactions, arg.TransactionIds, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForTransactionsRow{}
	for rows.Next() {
		var i ListTagsForTransactionsRow
		if err := rows.Scan(&i.TransactionID, &i.TagID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name            = $1,
    description     = $2,
    expected_amount = $3,
    updated_at      = now()
WHERE id = $4 AND household_id = $5
RETURNING id
`

type UpdateTagParams struct {
	Name           string              `json:"name"`
	Description    *string             `json:"description"`
	ExpectedAmount decimal.NullDecimal `json:"expected_amount"`
	ID             uuid.UUID           `json:"id"`
	HouseholdID    uuid.UUID           `json:"household_id"`
}

// The household_id guard is the authorisation: an id from another household
// matches no rows, the handler reads pgx.ErrNoRows, and it returns 404 rather
// than editing it.
func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.Name,
		arg.Description,
		arg.ExpectedAmount,
		arg.ID,
		arg.HouseholdID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
