// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	stdtime "time"
)

const breakdownTransactions = `-- name: BreakdownTransactions :many
WITH base AS (
    SELECT
        (CASE $5::text
            WHEN 'category' THEN COALESCE(c.name, 'Uncategorised')
            WHEN 'merchant' THEN COALESCE(t.merchant_name, t.name)
            WHEN 'account'  THEN a.name
            WHEN 'month'    THEN to_char(date_trunc('month', t.date), 'YYYY-MM')
            WHEN 'day'      THEN to_char(t.date, 'YYYY-MM-DD')
            WHEN 'pfc'      THEN COALESCE(t.plaid_pfc_detailed, 'Unknown')
            ELSE COALESCE(c.name, 'Uncategorised')
        END) AS grp,
        t.amount
    FROM transactions t
    JOIN accounts a    ON a.id = t.account_id
    JOIN account_access v ON v.account_id = a.id
    LEFT JOIN categories c ON c.id = t.category_id
    WHERE v.household_id = $1
      AND (v.user_id = $2 OR v.is_shared)
      AND a.is_active
      AND NOT t.excluded_from_reports
      AND NOT t.pending
      AND t.date >= $3 AND t.date <= $4
      AND (
        $6::text = 'all'
        OR ($6::text = 'income'    AND COALESCE(c.is_income, false))
        OR ($6::text = 'transfers' AND COALESCE(c.is_transfer, false))
        OR ($6::text = 'spending'
              AND NOT COALESCE(c.is_income, false)
              AND NOT COALESCE(c.is_transfer, false)
              AND t.amount > 0)
      )
      AND ($7::text IS NULL
           OR c.slug = lower($7::text)
           OR c.name ILIKE '%' || $7::text || '%')
      AND ($8::text IS NULL
           OR COALESCE(t.merchant_name, t.name) ILIKE '%' || $8::text || '%')
      AND ($9::uuid[] IS NULL
           OR cardinality($9::uuid[]) = 0
           OR t.account_id = ANY($9::uuid[]))
      AND ($10::numeric IS NULL OR abs(t.amount) >= $10::numeric)
      AND ($11::numeric IS NULL OR abs(t.amount) <= $11::numeric)
      AND ($12::text IS NULL OR t.source = $12::text)
)
SELECT
    grp                                                          AS group_label,
    COUNT(*)::bigint                                             AS transaction_count,
    COALESCE(SUM(-amount) FILTER (WHERE amount < 0), 0)::numeric AS total_in,
    COALESCE(SUM(amount)  FILTER (WHERE amount > 0), 0)::numeric AS total_out
FROM base
GROUP BY grp
ORDER BY (COALESCE(SUM(-amount) FILTER (WHERE amount < 0), 0)
          + COALESCE(SUM(amount) FILTER (WHERE amount > 0), 0)) DESC
`

type BreakdownTransactionsParams struct {
	HouseholdID uuid.UUID           `json:"household_id"`
	UserID      uuid.UUID           `json:"user_id"`
	Date        stdtime.Time        `json:"date"`
	Date_2      stdtime.Time        `json:"date_2"`
	GroupBy     string              `json:"group_by"`
	Flow        string              `json:"flow"`
	Category    *string             `json:"category"`
	Merchant    *string             `json:"merchant"`
	AccountIds  []uuid.UUID         `json:"account_ids"`
	MinAmount   decimal.NullDecimal `json:"min_amount"`
	MaxAmount   decimal.NullDecimal `json:"max_amount"`
	Source      *string             `json:"source"`
}

type BreakdownTransactionsRow struct {
	GroupLabel       interface{}     `json:"group_label"`
	TransactionCount int64           `json:"transaction_count"`
	TotalIn          decimal.Decimal `json:"total_in"`
	TotalOut         decimal.Decimal `json:"total_out"`
}

// Group transactions along one dimension and return per-group split totals — the
// flexible aggregation tool. Generalises GetSpendingByCategory/GetTopMerchants/
// GetSpendingByDay to any flow and any of several group_by dimensions. The group
// label is chosen in SQL by sqlc.arg('group_by'); totals are split by direction
// and positive, exactly as in SumQueriedTransactions. Same filters and visibility
// scoping. Ordered by combined magnitude so the largest groups come first.
func (q *Queries) BreakdownTransactions(ctx context.Context, arg BreakdownTransactionsParams) ([]BreakdownTransactionsRow, error) {
	rows, err := q.db.Query(ctx, breakdownTransactions,
		arg.HouseholdID,
		arg.UserID,
		arg.Date,
		arg.Date_2,
		arg.GroupBy,
		arg.Flow,
		arg.Category,
		arg.Merchant,
		arg.AccountIds,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Source,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakdownTransactionsRow{}
	for rows.Next() {
		var i BreakdownTransactionsRow
		if err := rows.Scan(
			&i.GroupLabel,
			&i.TransactionCount,
			&i.TotalIn,
			&i.TotalOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTransactionsForItem = `-- name: CountTransactionsForItem :one
SELECT count(*)
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE a.plaid_item_id = $1
`

func (q *Queries) CountTransactionsForItem(ctx context.Context, plaidItemID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsForItem, plaidItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createManualTransaction = `-- name: CreateManualTransaction :one
INSERT INTO transactions (
    account_id, amount, currency, date, name, merchant_name, merchant_key,
    category_id, category_source, notes, source, pending
)
SELECT
    a.id,
    $1,
    a.currency,
    $2,
    $3,
    $4,
    $5,
    $6,
    CASE WHEN $6::uuid IS NULL THEN NULL ELSE 'manual' END,
    $7,
    'manual',
    false
FROM accounts a
JOIN account_access v ON v.account_id = a.id
WHERE a.id = $8
  AND v.household_id = $9
  AND (v.user_id = $10 OR v.is_shared)
  AND a.is_active
RETURNING id, account_id, plaid_transaction_id, amount, currency, date, authorized_date, name, merchant_name, merchant_key, pending, pending_transaction_id, plaid_pfc_primary, plaid_pfc_detailed, category_id, category_source, is_recurring, excluded_from_reports, notes, source, raw, created_at, updated_at, is_one_time, obligation_id
`

type CreateManualTransactionParams struct {
	Amount       decimal.Decimal `json:"amount"`
	Date         stdtime.Time    `json:"date"`
	Name         string          `json:"name"`
	MerchantName *string         `json:"merchant_name"`
	MerchantKey  *string         `json:"merchant_key"`
	CategoryID   *uuid.UUID      `json:"category_id"`
	Notes        *string         `json:"notes"`
	AccountID    uuid.UUID       `json:"account_id"`
	HouseholdID  uuid.UUID       `json:"household_id"`
	UserID       uuid.UUID       `json:"user_id"`
}

// Inserts a hand-entered transaction. Household scoping is enforced in the
// SELECT: the row is created only when the target account belongs to the
// caller's household and is visible to them (own or shared), so a foreign or
// invisible account_id inserts nothing and the handler reads pgx.ErrNoRows.
//
// source='manual' and a NULL plaid_transaction_id keep it clear of the Plaid
// sync upsert (which keys ON CONFLICT (plaid_transaction_id)) forever, and the
// balance is never touched — manual rows correct spending math only.
func (q *Queries) CreateManualTransaction(ctx context.Context, arg CreateManualTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createManualTransaction,
		arg.Amount,
		arg.Date,
		arg.Name,
		arg.MerchantName,
		arg.MerchantKey,
		arg.CategoryID,
		arg.Notes,
		arg.AccountID,
		arg.HouseholdID,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PlaidTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.AuthorizedDate,
		&i.Name,
		&i.MerchantName,
		&i.MerchantKey,
		&i.Pending,
		&i.PendingTransactionID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.CategoryID,
		&i.CategorySource,
		&i.IsRecurring,
		&i.ExcludedFromReports,
		&i.Notes,
		&i.Source,
		&i.Raw,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsOneTime,
		&i.ObligationID,
	)
	return i, err
}

const deleteManualTransaction = `-- name: DeleteManualTransaction :execrows
DELETE FROM transactions t
USING accounts a, account_access v
WHERE t.id = $1
  AND v.account_id = a.id
  AND t.source = 'manual'
  AND a.id = t.account_id
  AND v.household_id = $2
`

type DeleteManualTransactionParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

// Same source='manual' + household guard as the update. :execrows returns 0
// when nothing matched (wrong household, or a Plaid id), which the handler maps
// to 404.
func (q *Queries) DeleteManualTransaction(ctx context.Context, arg DeleteManualTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManualTransaction, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingSupersededBy = `-- name: DeletePendingSupersededBy :execrows
DELETE FROM transactions WHERE plaid_transaction_id = $1
`

// When a pending charge posts, Plaid issues a new transaction that names the
// pending one it replaces. Removing the superseded row keeps a single
// authoritative record and stops the amount being counted twice.
func (q *Queries) DeletePendingSupersededBy(ctx context.Context, plaidTransactionID *string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingSupersededBy, plaidTransactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTransactionByPlaidID = `-- name: DeleteTransactionByPlaidID :execrows
DELETE FROM transactions WHERE plaid_transaction_id = $1
`

func (q *Queries) DeleteTransactionByPlaidID(ctx context.Context, plaidTransactionID *string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransactionByPlaidID, plaidTransactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getImportAccount = `-- name: GetImportAccount :one
SELECT a.id, a.currency
FROM accounts a
JOIN account_access v ON v.account_id = a.id
WHERE a.id = $1
  AND v.household_id = $2
  AND (v.user_id = $3 OR v.is_shared)
  AND a.is_active
`

type GetImportAccountParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type GetImportAccountRow struct {
	ID       uuid.UUID `json:"id"`
	Currency string    `json:"currency"`
}

// Validates that an account belongs to the caller's household and is visible to
// them, returning its currency for imported rows. No row means "not yours".
func (q *Queries) GetImportAccount(ctx context.Context, arg GetImportAccountParams) (GetImportAccountRow, error) {
	row := q.db.QueryRow(ctx, getImportAccount, arg.ID, arg.HouseholdID, arg.UserID)
	var i GetImportAccountRow
	err := row.Scan(&i.ID, &i.Currency)
	return i, err
}

const getVisibleTransaction = `-- name: GetVisibleTransaction :one
SELECT t.id, t.account_id, t.plaid_transaction_id, t.amount, t.currency, t.date, t.authorized_date, t.name, t.merchant_name, t.merchant_key, t.pending, t.pending_transaction_id, t.plaid_pfc_primary, t.plaid_pfc_detailed, t.category_id, t.category_source, t.is_recurring, t.excluded_from_reports, t.notes, t.source, t.raw, t.created_at, t.updated_at, t.is_one_time, t.obligation_id
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
WHERE t.id = $1
  AND v.household_id = $2
  AND (v.user_id = $3::uuid OR v.is_shared)
`

type GetVisibleTransactionParams struct {
	ID           uuid.UUID  `json:"id"`
	HouseholdID  uuid.UUID  `json:"household_id"`
	ViewerUserID *uuid.UUID `json:"viewer_user_id"`
}

// A single transaction scoped exactly like the list: own items ∪ shared. Used
// inside the audit transaction to read a row's before-state before a mutation,
// so the field-level diff is computed against what the caller was allowed to
// see in the first place — a private account's transaction is unreadable, and
// therefore uneditable and un-auditable, by the other member.
func (q *Queries) GetVisibleTransaction(ctx context.Context, arg GetVisibleTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getVisibleTransaction, arg.ID, arg.HouseholdID, arg.ViewerUserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PlaidTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.AuthorizedDate,
		&i.Name,
		&i.MerchantName,
		&i.MerchantKey,
		&i.Pending,
		&i.PendingTransactionID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.CategoryID,
		&i.CategorySource,
		&i.IsRecurring,
		&i.ExcludedFromReports,
		&i.Notes,
		&i.Source,
		&i.Raw,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsOneTime,
		&i.ObligationID,
	)
	return i, err
}

const insertImportedTransactionIfNew = `-- name: InsertImportedTransactionIfNew :one
INSERT INTO transactions (
    account_id, amount, currency, date, name, merchant_name, merchant_key,
    category_id, category_source, source, pending
)
SELECT
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, 'csv', false
WHERE NOT EXISTS (
    SELECT 1 FROM transactions d
    WHERE d.account_id = $1
      AND d.amount = $2
      AND abs(d.date - $4) <= 4
)
RETURNING id
`

type InsertImportedTransactionIfNewParams struct {
	AccountID      uuid.UUID       `json:"account_id"`
	Amount         decimal.Decimal `json:"amount"`
	Currency       string          `json:"currency"`
	Date           stdtime.Time    `json:"date"`
	Name           string          `json:"name"`
	MerchantName   *string         `json:"merchant_name"`
	MerchantKey    *string         `json:"merchant_key"`
	CategoryID     *uuid.UUID      `json:"category_id"`
	CategorySource *string         `json:"category_source"`
}

// Inserts one CSV-imported row unless a transaction on the same account already
// matches its amount within a few days — the same window the ledger uses to
// flag possible duplicates — so re-importing, or overlapping Plaid's synced
// window, never double-counts. Returns the new id, or no rows when skipped as a
// duplicate.
func (q *Queries) InsertImportedTransactionIfNew(ctx context.Context, arg InsertImportedTransactionIfNewParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertImportedTransactionIfNew,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.Date,
		arg.Name,
		arg.MerchantName,
		arg.MerchantKey,
		arg.CategoryID,
		arg.CategorySource,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listFilteredTransactions = `-- name: ListFilteredTransactions :many
SELECT
    t.date,
    COALESCE(t.merchant_name, t.name) AS merchant,
    t.amount,
    c.name AS category_name
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
JOIN categories c  ON c.id = t.category_id
WHERE v.household_id = $1
  AND (v.user_id = $2 OR v.is_shared)
  AND a.is_active
  AND NOT t.excluded_from_reports
  AND NOT t.pending
  AND t.date >= $3 AND t.date <= $4
  AND NOT c.is_income
  AND NOT c.is_transfer
  AND t.amount > 0
  AND ($5::text IS NULL
       OR c.slug = lower($5::text)
       OR c.name ILIKE '%' || $5::text || '%')
  AND ($6::text IS NULL
       OR COALESCE(t.merchant_name, t.name) ILIKE '%' || $6::text || '%')
ORDER BY t.date DESC, t.amount DESC
LIMIT $7
`

type ListFilteredTransactionsParams struct {
	HouseholdID uuid.UUID    `json:"household_id"`
	UserID      uuid.UUID    `json:"user_id"`
	Date        stdtime.Time `json:"date"`
	Date_2      stdtime.Time `json:"date_2"`
	Category    *string      `json:"category"`
	Merchant    *string      `json:"merchant"`
	Lim         int32        `json:"lim"`
}

type ListFilteredTransactionsRow struct {
	Date         stdtime.Time    `json:"date"`
	Merchant     string          `json:"merchant"`
	Amount       decimal.Decimal `json:"amount"`
	CategoryName string          `json:"category_name"`
}

// The per-transaction breakdown behind the same tool. Same filters as
// SumFilteredTransactions; the list may be capped by the limit while the sum
// above stays exact over every match.
func (q *Queries) ListFilteredTransactions(ctx context.Context, arg ListFilteredTransactionsParams) ([]ListFilteredTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listFilteredTransactions,
		arg.HouseholdID,
		arg.UserID,
		arg.Date,
		arg.Date_2,
		arg.Category,
		arg.Merchant,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilteredTransactionsRow{}
	for rows.Next() {
		var i ListFilteredTransactionsRow
		if err := rows.Scan(
			&i.Date,
			&i.Merchant,
			&i.Amount,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueriedTransactions = `-- name: ListQueriedTransactions :many
SELECT
    t.date,
    COALESCE(t.merchant_name, t.name)                    AS merchant,
    abs(t.amount)::numeric                               AS amount,
    (CASE WHEN t.amount < 0 THEN 'in' ELSE 'out' END)    AS direction,
    COALESCE(c.name, 'Uncategorised')                    AS category_name,
    a.name                                               AS account_name,
    COALESCE(c.is_income, false)                         AS is_income,
    COALESCE(c.is_transfer, false)                       AS is_transfer,
    t.plaid_pfc_detailed,
    t.source
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
LEFT JOIN categories c ON c.id = t.category_id
WHERE v.household_id = $1
  AND (v.user_id = $2 OR v.is_shared)
  AND a.is_active
  AND NOT t.excluded_from_reports
  AND NOT t.pending
  AND t.date >= $3 AND t.date <= $4
  AND (
    $5::text = 'all'
    OR ($5::text = 'income'    AND COALESCE(c.is_income, false))
    OR ($5::text = 'transfers' AND COALESCE(c.is_transfer, false))
    OR ($5::text = 'spending'
          AND NOT COALESCE(c.is_income, false)
          AND NOT COALESCE(c.is_transfer, false)
          AND t.amount > 0)
  )
  AND ($6::text IS NULL
       OR c.slug = lower($6::text)
       OR c.name ILIKE '%' || $6::text || '%')
  AND ($7::text IS NULL
       OR COALESCE(t.merchant_name, t.name) ILIKE '%' || $7::text || '%')
  AND ($8::uuid[] IS NULL
       OR cardinality($8::uuid[]) = 0
       OR t.account_id = ANY($8::uuid[]))
  AND ($9::numeric IS NULL OR abs(t.amount) >= $9::numeric)
  AND ($10::numeric IS NULL OR abs(t.amount) <= $10::numeric)
  AND ($11::text IS NULL OR t.source = $11::text)
ORDER BY t.date DESC, abs(t.amount) DESC
LIMIT $12
`

type ListQueriedTransactionsParams struct {
	HouseholdID uuid.UUID           `json:"household_id"`
	UserID      uuid.UUID           `json:"user_id"`
	Date        stdtime.Time        `json:"date"`
	Date_2      stdtime.Time        `json:"date_2"`
	Flow        string              `json:"flow"`
	Category    *string             `json:"category"`
	Merchant    *string             `json:"merchant"`
	AccountIds  []uuid.UUID         `json:"account_ids"`
	MinAmount   decimal.NullDecimal `json:"min_amount"`
	MaxAmount   decimal.NullDecimal `json:"max_amount"`
	Source      *string             `json:"source"`
	Lim         int32               `json:"lim"`
}

type ListQueriedTransactionsRow struct {
	Date             stdtime.Time    `json:"date"`
	Merchant         string          `json:"merchant"`
	Amount           decimal.Decimal `json:"amount"`
	Direction        string          `json:"direction"`
	CategoryName     string          `json:"category_name"`
	AccountName      string          `json:"account_name"`
	IsIncome         bool            `json:"is_income"`
	IsTransfer       bool            `json:"is_transfer"`
	PlaidPfcDetailed *string         `json:"plaid_pfc_detailed"`
	Source           string          `json:"source"`
}

// The per-row list behind the flexible assistant query tool. Same filters and
// visibility scoping as SumQueriedTransactions; the list may be capped by the
// limit while that sum stays exact over every match. Amount is reported as a
// positive magnitude with a direction ('in'/'out') so income and spending read
// consistently without the model doing sign arithmetic.
func (q *Queries) ListQueriedTransactions(ctx context.Context, arg ListQueriedTransactionsParams) ([]ListQueriedTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listQueriedTransactions,
		arg.HouseholdID,
		arg.UserID,
		arg.Date,
		arg.Date_2,
		arg.Flow,
		arg.Category,
		arg.Merchant,
		arg.AccountIds,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Source,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueriedTransactionsRow{}
	for rows.Next() {
		var i ListQueriedTransactionsRow
		if err := rows.Scan(
			&i.Date,
			&i.Merchant,
			&i.Amount,
			&i.Direction,
			&i.CategoryName,
			&i.AccountName,
			&i.IsIncome,
			&i.IsTransfer,
			&i.PlaidPfcDetailed,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleTransactions = `-- name: ListVisibleTransactions :many
SELECT t.id, t.account_id, t.plaid_transaction_id, t.amount, t.currency, t.date, t.authorized_date, t.name, t.merchant_name, t.merchant_key, t.pending, t.pending_transaction_id, t.plaid_pfc_primary, t.plaid_pfc_detailed, t.category_id, t.category_source, t.is_recurring, t.excluded_from_reports, t.notes, t.source, t.raw, t.created_at, t.updated_at, t.is_one_time, t.obligation_id, a.name AS account_name, v.institution_name,
    -- The RESOLVED merchant key, so a row can address the merchant detail view.
    -- Raw t.merchant_key addresses one DESCRIPTOR; this addresses the BUSINESS,
    -- collapsing every fragment the household has grouped. Without it a row
    -- links to a merchant that no longer exists under that key — see the
    -- canonicalisation contract at the top of merchants.sql.
    --
    -- merchant_aliases is UNIQUE (household_id, merchant_key), so the LEFT JOIN
    -- cannot fan a transaction out into several rows.
    COALESCE(ma.entity_id::text, t.merchant_key, '')::text AS resolved_merchant_key,
    -- The name to DISPLAY for this row: the canonical name of the merchant the
    -- descriptor resolves to when the household has grouped or renamed it, else
    -- the raw merchant_name/name the bank sent. Mirrors what every report reads
    -- (COALESCE(me.canonical_name, t.merchant_name, t.name)), so renaming a
    -- merchant is reflected on the row and not only on the merchant pages. The
    -- raw columns above are still returned so search and the manual editor keep
    -- working against the bank's own text.
    COALESCE(me.canonical_name, t.merchant_name, t.name) AS merchant,
    -- A manual row is a "possible duplicate" when a Plaid-synced row exists on
    -- the same account for the same amount within four days — the issuer having
    -- finally delivered a charge the user already entered by hand. Computed at
    -- read time (never in the sync hot path) and only ever true for manual rows.
    (t.source = 'manual' AND EXISTS (
        SELECT 1 FROM transactions p
        WHERE p.source = 'plaid'
          AND p.account_id = t.account_id
          AND p.amount = t.amount
          AND abs(p.date - t.date) <= 4
    )) AS is_possible_duplicate
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
LEFT JOIN merchant_aliases ma
       ON ma.household_id = $1
      AND ma.merchant_key = t.merchant_key
      AND ma.source <> 'suggested'
LEFT JOIN merchant_entities me ON me.id = ma.entity_id
WHERE v.household_id = $1
  AND (v.user_id = $2 OR v.is_shared)
  AND a.is_active
  -- Excluded rows are hidden by default, because the ledger should read like the
  -- reports it feeds. They are NOT hidden unconditionally: this list is the only
  -- surface that can clear the flag, and a row that vanishes the moment it is set
  -- would make exclusion a one-way trip. NULL/false narg gives the ordinary view.
  AND ($7::bool IS TRUE OR NOT t.excluded_from_reports)
  AND t.date >= $3
  AND t.date <= $4
  -- Optional multi-account filter: NULL/empty array passes everything, so "all
  -- accounts" needs no special case. Anything else narrows to the listed ids.
  AND (
    $8::uuid[] IS NULL
    OR cardinality($8::uuid[]) = 0
    OR t.account_id = ANY($8::uuid[])
  )
  -- Optional category filter (a null narg passes everything).
  AND ($9::uuid IS NULL OR t.category_id = $9::uuid)
  -- Optional canonical merchant filter, for drilling in from a merchant page.
  --
  -- Matched against the RESOLVED key first, so filtering by a grouped merchant
  -- returns every descriptor's charges rather than one fragment's — the whole
  -- point of the grouping.
  --
  -- The raw key is also accepted, and that second comparison is not redundant. A
  -- descriptor belonging to a grouped merchant resolves to the entity id, so
  -- resolved-only matching would answer "no charges" for a perfectly valid
  -- descriptor key — the same stranded-link failure this column exists to
  -- prevent, just one level down. With both, an entity id gives the whole
  -- merchant and a descriptor gives that fragment, and neither ever comes back
  -- empty for a key the household really has.
  AND (
    $10::text IS NULL
    OR COALESCE(ma.entity_id::text, t.merchant_key) = $10::text
    OR t.merchant_key = $10::text
  )
  -- Optional free-text search over what the user actually reads in the row: the
  -- resolved (canonical) merchant name the UI now displays, the raw name the bank
  -- sent, and the descriptor key. Both name forms are matched so a renamed
  -- merchant is findable by what it shows now AND by the bank's original wording.
  --
  -- These three columns are the DEFINITION of free-text matching in this app.
  -- GET /api/transactions no longer passes this narg — ` + "`" + `q` + "`" + ` is now a composable
  -- query and its bare words go through internal/search — but that package
  -- matches this same list on purpose, so ` + "`" + `q=coffee` + "`" + ` returns what it always did.
  -- Change one and change the other.
  AND (
    $11::text IS NULL
    OR t.merchant_key ILIKE '%' || $11::text || '%'
    OR COALESCE(t.merchant_name, t.name) ILIKE '%' || $11::text || '%'
    OR me.canonical_name ILIKE '%' || $11::text || '%'
  )
  -- Optional "needs a category" filter for draining the backlog: a row is
  -- uncategorised when it has no category or sits in the fallback 'uncategorised'
  -- category. NULL/false narg passes everything.
  AND (
    $12::bool IS NOT TRUE
    OR t.category_id IS NULL
    OR t.category_id IN (SELECT id FROM categories WHERE slug = 'uncategorised')
  )
  -- Optional tag filter: rows carrying ANY of the listed tags. OR rather than
  -- AND, matching how the account filter above reads — picking two tags widens
  -- the view to "the trip or the remodel", which is the question a household
  -- actually asks. The tags are re-checked against the household here so a
  -- foreign tag id narrows to nothing rather than matching by id alone. EXISTS
  -- rather than a join, so a row with three matching tags stays one row.
  AND (
    $13::uuid[] IS NULL
    OR cardinality($13::uuid[]) = 0
    OR EXISTS (
      SELECT 1 FROM transaction_tags tt
      JOIN tags tg ON tg.id = tt.tag_id
      WHERE tt.transaction_id = t.id
        AND tg.household_id = $1
        AND tt.tag_id = ANY($13::uuid[])
    )
  )
  -- Optional "only rows nobody has labelled yet", the tag counterpart of the
  -- uncategorised filter above and the way a household drains the backlog of
  -- charges that belong to a trip or a project. NULL/false passes everything.
  AND (
    $14::bool IS NOT TRUE
    OR NOT EXISTS (
      SELECT 1 FROM transaction_tags tt
      JOIN tags tg ON tg.id = tt.tag_id
      WHERE tt.transaction_id = t.id AND tg.household_id = $1
    )
  )
  -- Optional restriction to an explicit set of ids, which is how the composable
  -- search bar gets its rows (see internal/search and transaction_search.go).
  --
  -- A query with ` + "`" + `key:value` + "`" + ` operators cannot be expressed as a fixed set of
  -- nargs, so that path builds its own predicate and resolves it to an ordered,
  -- paged list of ids. Handing those ids back here means the row PROJECTION —
  -- every column above, the resolved merchant key, the duplicate check — has
  -- exactly one definition, and the household/viewer scoping at the top of this
  -- WHERE is applied a second time to the search's answer rather than replaced
  -- by it. A search can therefore only ever narrow what this query would have
  -- returned; it can never widen it.
  --
  -- The search path already applied the window, the chips and the excluded rule
  -- when it chose those ids, and passes the remaining filters wide open. A NULL
  -- narg (every other caller) passes everything, as usual.
  AND (
    $15::uuid[] IS NULL
    OR t.id = ANY($15::uuid[])
  )
ORDER BY t.date DESC, t.created_at DESC
LIMIT $5 OFFSET $6
`

type ListVisibleTransactionsParams struct {
	HouseholdID     uuid.UUID    `json:"household_id"`
	UserID          uuid.UUID    `json:"user_id"`
	Date            stdtime.Time `json:"date"`
	Date_2          stdtime.Time `json:"date_2"`
	Limit           int32        `json:"limit"`
	Offset          int32        `json:"offset"`
	IncludeExcluded *bool        `json:"include_excluded"`
	AccountIds      []uuid.UUID  `json:"account_ids"`
	CategoryID      *uuid.UUID   `json:"category_id"`
	MerchantKey     *string      `json:"merchant_key"`
	Search          *string      `json:"search"`
	Uncategorised   *bool        `json:"uncategorised"`
	TagIds          []uuid.UUID  `json:"tag_ids"`
	Untagged        *bool        `json:"untagged"`
	TransactionIds  []uuid.UUID  `json:"transaction_ids"`
}

type ListVisibleTransactionsRow struct {
	ID                   uuid.UUID       `json:"id"`
	AccountID            uuid.UUID       `json:"account_id"`
	PlaidTransactionID   *string         `json:"plaid_transaction_id"`
	Amount               decimal.Decimal `json:"amount"`
	Currency             string          `json:"currency"`
	Date                 stdtime.Time    `json:"date"`
	AuthorizedDate       *stdtime.Time   `json:"authorized_date"`
	Name                 string          `json:"name"`
	MerchantName         *string         `json:"merchant_name"`
	MerchantKey          *string         `json:"merchant_key"`
	Pending              bool            `json:"pending"`
	PendingTransactionID *string         `json:"pending_transaction_id"`
	PlaidPfcPrimary      *string         `json:"plaid_pfc_primary"`
	PlaidPfcDetailed     *string         `json:"plaid_pfc_detailed"`
	CategoryID           *uuid.UUID      `json:"category_id"`
	CategorySource       *string         `json:"category_source"`
	IsRecurring          bool            `json:"is_recurring"`
	ExcludedFromReports  bool            `json:"excluded_from_reports"`
	Notes                *string         `json:"notes"`
	Source               string          `json:"source"`
	Raw                  []byte          `json:"raw"`
	CreatedAt            stdtime.Time    `json:"created_at"`
	UpdatedAt            stdtime.Time    `json:"updated_at"`
	IsOneTime            bool            `json:"is_one_time"`
	ObligationID         *uuid.UUID      `json:"obligation_id"`
	AccountName          string          `json:"account_name"`
	InstitutionName      *string         `json:"institution_name"`
	ResolvedMerchantKey  string          `json:"resolved_merchant_key"`
	Merchant             string          `json:"merchant"`
	IsPossibleDuplicate  *bool           `json:"is_possible_duplicate"`
}

// merchant_entities sits behind the alias join, so a row whose descriptor has
// not been grouped gets NULL here and the COALESCE above falls back to the raw
// name. No fan-out: ma is unique on (household_id, merchant_key).
func (q *Queries) ListVisibleTransactions(ctx context.Context, arg ListVisibleTransactionsParams) ([]ListVisibleTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleTransactions,
		arg.HouseholdID,
		arg.UserID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
		arg.IncludeExcluded,
		arg.AccountIds,
		arg.CategoryID,
		arg.MerchantKey,
		arg.Search,
		arg.Uncategorised,
		arg.TagIds,
		arg.Untagged,
		arg.TransactionIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleTransactionsRow{}
	for rows.Next() {
		var i ListVisibleTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PlaidTransactionID,
			&i.Amount,
			&i.Currency,
			&i.Date,
			&i.AuthorizedDate,
			&i.Name,
			&i.MerchantName,
			&i.MerchantKey,
			&i.Pending,
			&i.PendingTransactionID,
			&i.PlaidPfcPrimary,
			&i.PlaidPfcDetailed,
			&i.CategoryID,
			&i.CategorySource,
			&i.IsRecurring,
			&i.ExcludedFromReports,
			&i.Notes,
			&i.Source,
			&i.Raw,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsOneTime,
			&i.ObligationID,
			&i.AccountName,
			&i.InstitutionName,
			&i.ResolvedMerchantKey,
			&i.Merchant,
			&i.IsPossibleDuplicate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionFlags = `-- name: SetTransactionFlags :one
UPDATE transactions t
SET excluded_from_reports = COALESCE($1::bool, t.excluded_from_reports),
    is_one_time           = COALESCE($2::bool, t.is_one_time),
    updated_at            = now()
FROM accounts a, account_access v
WHERE t.id = $3
  AND v.account_id = a.id
  AND a.id = t.account_id
  AND v.household_id = $4
RETURNING t.id, t.account_id, t.plaid_transaction_id, t.amount, t.currency, t.date, t.authorized_date, t.name, t.merchant_name, t.merchant_key, t.pending, t.pending_transaction_id, t.plaid_pfc_primary, t.plaid_pfc_detailed, t.category_id, t.category_source, t.is_recurring, t.excluded_from_reports, t.notes, t.source, t.raw, t.created_at, t.updated_at, t.is_one_time, t.obligation_id
`

type SetTransactionFlagsParams struct {
	ExcludedFromReports *bool     `json:"excluded_from_reports"`
	IsOneTime           *bool     `json:"is_one_time"`
	ID                  uuid.UUID `json:"id"`
	HouseholdID         uuid.UUID `json:"household_id"`
}

// Sets the two user-state flags that decide how a row is counted. Unlike the
// manual-row editors above there is no source='manual' guard: these flags are
// judgements ABOUT a transaction, not edits TO it, so a Plaid-synced row is
// exactly the case they exist for (a synced loan payoff is the motivating
// example). Both are nargs — a NULL leaves that flag alone, so the handler can
// set either independently without read-modify-write.
//
// The household join is the authorisation: a caller with a valid id from
// another household matches no rows and the handler returns 404.
func (q *Queries) SetTransactionFlags(ctx context.Context, arg SetTransactionFlagsParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, setTransactionFlags,
		arg.ExcludedFromReports,
		arg.IsOneTime,
		arg.ID,
		arg.HouseholdID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PlaidTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.AuthorizedDate,
		&i.Name,
		&i.MerchantName,
		&i.MerchantKey,
		&i.Pending,
		&i.PendingTransactionID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.CategoryID,
		&i.CategorySource,
		&i.IsRecurring,
		&i.ExcludedFromReports,
		&i.Notes,
		&i.Source,
		&i.Raw,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsOneTime,
		&i.ObligationID,
	)
	return i, err
}

const sumFilteredTransactions = `-- name: SumFilteredTransactions :one
SELECT
    COUNT(*)::bigint                    AS transaction_count,
    COALESCE(SUM(t.amount), 0)::numeric AS total
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
JOIN categories c  ON c.id = t.category_id
WHERE v.household_id = $1
  AND (v.user_id = $2 OR v.is_shared)
  AND a.is_active
  AND NOT t.excluded_from_reports
  AND NOT t.pending
  AND t.date >= $3 AND t.date <= $4
  AND NOT c.is_income
  AND NOT c.is_transfer
  AND t.amount > 0
  AND ($5::text IS NULL
       OR c.slug = lower($5::text)
       OR c.name ILIKE '%' || $5::text || '%')
  AND ($6::text IS NULL
       OR COALESCE(t.merchant_name, t.name) ILIKE '%' || $6::text || '%')
`

type SumFilteredTransactionsParams struct {
	HouseholdID uuid.UUID    `json:"household_id"`
	UserID      uuid.UUID    `json:"user_id"`
	Date        stdtime.Time `json:"date"`
	Date_2      stdtime.Time `json:"date_2"`
	Category    *string      `json:"category"`
	Merchant    *string      `json:"merchant"`
}

type SumFilteredTransactionsRow struct {
	TransactionCount int64           `json:"transaction_count"`
	Total            decimal.Decimal `json:"total"`
}

// Exact count and total of spending transactions in a period, optionally
// narrowed to a category and/or merchant. Backs the assistant's breakdown tool
// so the model quotes SQL-computed figures rather than summing rows itself.
//
// Filters mirror GetSpendingByCategory exactly (money out, non-income,
// non-transfer, categorised) so a category count here reconciles with that
// report. Category matches on exact slug or a name substring; merchant matches
// on a name substring — both case-insensitive, both optional.
func (q *Queries) SumFilteredTransactions(ctx context.Context, arg SumFilteredTransactionsParams) (SumFilteredTransactionsRow, error) {
	row := q.db.QueryRow(ctx, sumFilteredTransactions,
		arg.HouseholdID,
		arg.UserID,
		arg.Date,
		arg.Date_2,
		arg.Category,
		arg.Merchant,
	)
	var i SumFilteredTransactionsRow
	err := row.Scan(&i.TransactionCount, &i.Total)
	return i, err
}

const sumQueriedTransactions = `-- name: SumQueriedTransactions :one
SELECT
    COUNT(*)::bigint AS transaction_count,
    COALESCE(SUM(-t.amount) FILTER (WHERE t.amount < 0), 0)::numeric AS total_in,
    COALESCE(SUM(t.amount)  FILTER (WHERE t.amount > 0), 0)::numeric AS total_out
FROM transactions t
JOIN accounts a    ON a.id = t.account_id
JOIN account_access v ON v.account_id = a.id
LEFT JOIN categories c ON c.id = t.category_id
WHERE v.household_id = $1
  AND (v.user_id = $2 OR v.is_shared)
  AND a.is_active
  AND NOT t.excluded_from_reports
  AND NOT t.pending
  AND t.date >= $3 AND t.date <= $4
  AND (
    $5::text = 'all'
    OR ($5::text = 'income'    AND COALESCE(c.is_income, false))
    OR ($5::text = 'transfers' AND COALESCE(c.is_transfer, false))
    OR ($5::text = 'spending'
          AND NOT COALESCE(c.is_income, false)
          AND NOT COALESCE(c.is_transfer, false)
          AND t.amount > 0)
  )
  AND ($6::text IS NULL
       OR c.slug = lower($6::text)
       OR c.name ILIKE '%' || $6::text || '%')
  AND ($7::text IS NULL
       OR COALESCE(t.merchant_name, t.name) ILIKE '%' || $7::text || '%')
  AND ($8::uuid[] IS NULL
       OR cardinality($8::uuid[]) = 0
       OR t.account_id = ANY($8::uuid[]))
  AND ($9::numeric IS NULL OR abs(t.amount) >= $9::numeric)
  AND ($10::numeric IS NULL OR abs(t.amount) <= $10::numeric)
  AND ($11::text IS NULL OR t.source = $11::text)
`

type SumQueriedTransactionsParams struct {
	HouseholdID uuid.UUID           `json:"household_id"`
	UserID      uuid.UUID           `json:"user_id"`
	Date        stdtime.Time        `json:"date"`
	Date_2      stdtime.Time        `json:"date_2"`
	Flow        string              `json:"flow"`
	Category    *string             `json:"category"`
	Merchant    *string             `json:"merchant"`
	AccountIds  []uuid.UUID         `json:"account_ids"`
	MinAmount   decimal.NullDecimal `json:"min_amount"`
	MaxAmount   decimal.NullDecimal `json:"max_amount"`
	Source      *string             `json:"source"`
}

type SumQueriedTransactionsRow struct {
	TransactionCount int64           `json:"transaction_count"`
	TotalIn          decimal.Decimal `json:"total_in"`
	TotalOut         decimal.Decimal `json:"total_out"`
}

// Exact count and split totals for the flexible assistant query tool. Unlike
// SumFilteredTransactions (spending only), this spans any flow — spending,
// income, transfers, or all — selected by sqlc.arg('flow'), with a set of
// optional filters. Totals are split by direction and always positive:
//   - total_in  = money IN  = SUM(-amount) over inflow rows  (amount < 0)
//   - total_out = money OUT = SUM(amount)  over outflow rows (amount > 0)
//
// which matches how the app reports income and spending (both positive) and
// stays meaningful for a mixed flow='all' result. All arithmetic is in NUMERIC
// here, never in the application. LEFT JOIN categories so uncategorised rows are
// not silently dropped. Same visibility scoping as every report.
func (q *Queries) SumQueriedTransactions(ctx context.Context, arg SumQueriedTransactionsParams) (SumQueriedTransactionsRow, error) {
	row := q.db.QueryRow(ctx, sumQueriedTransactions,
		arg.HouseholdID,
		arg.UserID,
		arg.Date,
		arg.Date_2,
		arg.Flow,
		arg.Category,
		arg.Merchant,
		arg.AccountIds,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Source,
	)
	var i SumQueriedTransactionsRow
	err := row.Scan(&i.TransactionCount, &i.TotalIn, &i.TotalOut)
	return i, err
}

const updateManualTransaction = `-- name: UpdateManualTransaction :one
UPDATE transactions t
SET amount          = $1,
    date            = $2,
    name            = $3,
    merchant_name   = $4,
    merchant_key    = $5,
    category_id     = $6,
    category_source = CASE WHEN $6::uuid IS NULL THEN NULL ELSE 'manual' END,
    notes           = $7,
    updated_at      = now()
FROM accounts a, account_access v
WHERE t.id = $8
  AND v.account_id = a.id
  AND t.source = 'manual'
  AND a.id = t.account_id
  AND v.household_id = $9
RETURNING t.id, t.account_id, t.plaid_transaction_id, t.amount, t.currency, t.date, t.authorized_date, t.name, t.merchant_name, t.merchant_key, t.pending, t.pending_transaction_id, t.plaid_pfc_primary, t.plaid_pfc_detailed, t.category_id, t.category_source, t.is_recurring, t.excluded_from_reports, t.notes, t.source, t.raw, t.created_at, t.updated_at, t.is_one_time, t.obligation_id
`

type UpdateManualTransactionParams struct {
	Amount       decimal.Decimal `json:"amount"`
	Date         stdtime.Time    `json:"date"`
	Name         string          `json:"name"`
	MerchantName *string         `json:"merchant_name"`
	MerchantKey  *string         `json:"merchant_key"`
	CategoryID   *uuid.UUID      `json:"category_id"`
	Notes        *string         `json:"notes"`
	ID           uuid.UUID       `json:"id"`
	HouseholdID  uuid.UUID       `json:"household_id"`
}

// Edits a manual row in place. The source='manual' guard means this can never
// mutate a Plaid-synced transaction even with a valid id, and the household
// join means it can never touch another household's row.
func (q *Queries) UpdateManualTransaction(ctx context.Context, arg UpdateManualTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateManualTransaction,
		arg.Amount,
		arg.Date,
		arg.Name,
		arg.MerchantName,
		arg.MerchantKey,
		arg.CategoryID,
		arg.Notes,
		arg.ID,
		arg.HouseholdID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PlaidTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.AuthorizedDate,
		&i.Name,
		&i.MerchantName,
		&i.MerchantKey,
		&i.Pending,
		&i.PendingTransactionID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.CategoryID,
		&i.CategorySource,
		&i.IsRecurring,
		&i.ExcludedFromReports,
		&i.Notes,
		&i.Source,
		&i.Raw,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsOneTime,
		&i.ObligationID,
	)
	return i, err
}

const upsertTransaction = `-- name: UpsertTransaction :one
INSERT INTO transactions (
    account_id, plaid_transaction_id, amount, currency, date, authorized_date,
    name, merchant_name, merchant_key, pending, pending_transaction_id,
    plaid_pfc_primary, plaid_pfc_detailed, source, raw
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, 'plaid', $14)
ON CONFLICT (plaid_transaction_id) DO UPDATE SET
    account_id             = EXCLUDED.account_id,
    amount                 = EXCLUDED.amount,
    currency               = EXCLUDED.currency,
    date                   = EXCLUDED.date,
    authorized_date        = EXCLUDED.authorized_date,
    name                   = EXCLUDED.name,
    merchant_name          = EXCLUDED.merchant_name,
    merchant_key           = EXCLUDED.merchant_key,
    pending                = EXCLUDED.pending,
    pending_transaction_id = EXCLUDED.pending_transaction_id,
    plaid_pfc_primary      = EXCLUDED.plaid_pfc_primary,
    plaid_pfc_detailed     = EXCLUDED.plaid_pfc_detailed,
    raw                    = EXCLUDED.raw,
    category_id     = CASE WHEN transactions.category_source = 'manual'
                           THEN transactions.category_id ELSE NULL END,
    category_source = CASE WHEN transactions.category_source = 'manual'
                           THEN transactions.category_source ELSE NULL END
RETURNING id, account_id, plaid_transaction_id, amount, currency, date, authorized_date, name, merchant_name, merchant_key, pending, pending_transaction_id, plaid_pfc_primary, plaid_pfc_detailed, category_id, category_source, is_recurring, excluded_from_reports, notes, source, raw, created_at, updated_at, is_one_time, obligation_id
`

type UpsertTransactionParams struct {
	AccountID            uuid.UUID       `json:"account_id"`
	PlaidTransactionID   *string         `json:"plaid_transaction_id"`
	Amount               decimal.Decimal `json:"amount"`
	Currency             string          `json:"currency"`
	Date                 stdtime.Time    `json:"date"`
	AuthorizedDate       *stdtime.Time   `json:"authorized_date"`
	Name                 string          `json:"name"`
	MerchantName         *string         `json:"merchant_name"`
	MerchantKey          *string         `json:"merchant_key"`
	Pending              bool            `json:"pending"`
	PendingTransactionID *string         `json:"pending_transaction_id"`
	PlaidPfcPrimary      *string         `json:"plaid_pfc_primary"`
	PlaidPfcDetailed     *string         `json:"plaid_pfc_detailed"`
	Raw                  []byte          `json:"raw"`
}

// The idempotency guarantee for syncing.
//
// Plaid's /transactions/sync can legitimately redeliver a transaction (a
// replayed page after a crash, or a genuine `modified` event), so this is
// keyed on plaid_transaction_id and updates in place. Re-running an entire
// sync therefore converges rather than duplicating.
//
// Two fields are deliberately preserved across updates:
//   - a manual category, because Plaid must never overwrite a human decision
//   - excluded_from_reports, is_one_time and notes, which are purely user state
//
// The preservation is structural, not conditional: those columns are simply
// absent from the DO UPDATE SET list, so a redelivery cannot touch them.
func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, upsertTransaction,
		arg.AccountID,
		arg.PlaidTransactionID,
		arg.Amount,
		arg.Currency,
		arg.Date,
		arg.AuthorizedDate,
		arg.Name,
		arg.MerchantName,
		arg.MerchantKey,
		arg.Pending,
		arg.PendingTransactionID,
		arg.PlaidPfcPrimary,
		arg.PlaidPfcDetailed,
		arg.Raw,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PlaidTransactionID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.AuthorizedDate,
		&i.Name,
		&i.MerchantName,
		&i.MerchantKey,
		&i.Pending,
		&i.PendingTransactionID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.CategoryID,
		&i.CategorySource,
		&i.IsRecurring,
		&i.ExcludedFromReports,
		&i.Notes,
		&i.Source,
		&i.Raw,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsOneTime,
		&i.ObligationID,
	)
	return i, err
}
