// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	stdtime "time"
)

const beginWebhookAttempt = `-- name: BeginWebhookAttempt :one
UPDATE webhook_messages
SET attempts = attempts + 1
WHERE id = $1
RETURNING attempts
`

// Claims the next attempt number and stamps it on the message BEFORE the
// request goes out, so a worker killed mid-flight still leaves evidence that a
// request was started. Returns the number the attempt row should carry.
func (q *Queries) BeginWebhookAttempt(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, beginWebhookAttempt, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (household_id, user_id, name, url, secret_encrypted, active, triggers)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, url, active, triggers, created_at, updated_at
`

type CreateWebhookParams struct {
	HouseholdID     uuid.UUID `json:"household_id"`
	UserID          uuid.UUID `json:"user_id"`
	Name            string    `json:"name"`
	Url             string    `json:"url"`
	SecretEncrypted []byte    `json:"secret_encrypted"`
	Active          bool      `json:"active"`
	Triggers        []string  `json:"triggers"`
}

type CreateWebhookRow struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Name      string       `json:"name"`
	Url       string       `json:"url"`
	Active    bool         `json:"active"`
	Triggers  []string     `json:"triggers"`
	CreatedAt stdtime.Time `json:"created_at"`
	UpdatedAt stdtime.Time `json:"updated_at"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (CreateWebhookRow, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.HouseholdID,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.SecretEncrypted,
		arg.Active,
		arg.Triggers,
	)
	var i CreateWebhookRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.Active,
		&i.Triggers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldWebhookMessages = `-- name: DeleteOldWebhookMessages :execrows
DELETE FROM webhook_messages WHERE created_at < $1
`

// Retention. Delivery history is a debugging aid with a short useful life, and
// an instance that fires a few hundred events a day would otherwise grow this
// table without bound. Attempts go with the message by cascade.
func (q *Queries) DeleteOldWebhookMessages(ctx context.Context, createdAt stdtime.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldWebhookMessages, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebhook = `-- name: DeleteWebhook :execrows
DELETE FROM webhooks WHERE id = $1 AND household_id = $2
`

type DeleteWebhookParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

// execrows lets the handler tell "not yours" from "deleted" without a second
// query. The messages and attempts go with it by cascade.
func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhook, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueAlertEventWebhookMessages = `-- name: EnqueueAlertEventWebhookMessages :many
INSERT INTO webhook_messages (webhook_id, trigger_type, payload, dedupe_key)
SELECT w.id, $1, $2, $3
FROM webhooks w
WHERE w.household_id = $4
  AND w.active
  AND $1::text = ANY (w.triggers)
  AND EXISTS (
      SELECT 1
      FROM alert_events e
      LEFT JOIN transactions t   ON t.id = e.transaction_id
      LEFT JOIN accounts a       ON a.id = t.account_id
      LEFT JOIN account_access v ON v.account_id = a.id
      WHERE e.id = $5
        AND (e.transaction_id IS NULL OR v.user_id = w.user_id OR v.is_shared)
  )
ON CONFLICT (webhook_id, dedupe_key) DO NOTHING
RETURNING id
`

type EnqueueAlertEventWebhookMessagesParams struct {
	TriggerType  string    `json:"trigger_type"`
	Payload      []byte    `json:"payload"`
	DedupeKey    string    `json:"dedupe_key"`
	HouseholdID  uuid.UUID `json:"household_id"`
	AlertEventID uuid.UUID `json:"alert_event_id"`
}

// EnqueueWebhookMessages, plus the alert visibility rule.
//
// An aggregate alert (budget_threshold, low_leftover) carries no transaction and
// is household-visible, so it reaches every subscriber. A transaction-linked
// alert (big_spend, unusual_merchant) reaches a subscriber only when its owner
// could see that transaction in the app: their own item, or a shared one.
// Without this, wiring up a webhook would be a way to read a partner's private
// account — the one thing the visibility model exists to prevent.
func (q *Queries) EnqueueAlertEventWebhookMessages(ctx context.Context, arg EnqueueAlertEventWebhookMessagesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, enqueueAlertEventWebhookMessages,
		arg.TriggerType,
		arg.Payload,
		arg.DedupeKey,
		arg.HouseholdID,
		arg.AlertEventID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueWebhookMessageForWebhook = `-- name: EnqueueWebhookMessageForWebhook :one
INSERT INTO webhook_messages (webhook_id, trigger_type, payload, dedupe_key)
SELECT w.id, $1, $2, $3
FROM webhooks w
WHERE w.id = $4 AND w.household_id = $5
RETURNING id
`

type EnqueueWebhookMessageForWebhookParams struct {
	TriggerType string    `json:"trigger_type"`
	Payload     []byte    `json:"payload"`
	DedupeKey   string    `json:"dedupe_key"`
	WebhookID   uuid.UUID `json:"webhook_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

// The "send a test" path: one named subscriber rather than a household fan-out.
// household_id stays in the predicate so the id alone cannot reach across
// households, and `active` is deliberately NOT required — testing a paused
// webhook while fixing its receiver is the whole reason to pause it.
func (q *Queries) EnqueueWebhookMessageForWebhook(ctx context.Context, arg EnqueueWebhookMessageForWebhookParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueWebhookMessageForWebhook,
		arg.TriggerType,
		arg.Payload,
		arg.DedupeKey,
		arg.WebhookID,
		arg.HouseholdID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const enqueueWebhookMessages = `-- name: EnqueueWebhookMessages :many

INSERT INTO webhook_messages (webhook_id, trigger_type, payload, dedupe_key)
SELECT w.id, $1, $2, $3
FROM webhooks w
WHERE w.household_id = $4
  AND w.active
  AND $1::text = ANY (w.triggers)
ON CONFLICT (webhook_id, dedupe_key) DO NOTHING
RETURNING id
`

type EnqueueWebhookMessagesParams struct {
	TriggerType string    `json:"trigger_type"`
	Payload     []byte    `json:"payload"`
	DedupeKey   string    `json:"dedupe_key"`
	HouseholdID uuid.UUID `json:"household_id"`
}

// --------------------------------------------------------------------------
// Producing messages (write-before-deliver)
// --------------------------------------------------------------------------
// One message per active subscriber in this household that asked for this
// trigger. Returns the ids so the caller can queue a delivery job for each.
//
// The event is durable the moment this returns, which is the entire point: from
// here on a receiver being down costs a retry, never the event.
func (q *Queries) EnqueueWebhookMessages(ctx context.Context, arg EnqueueWebhookMessagesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, enqueueWebhookMessages,
		arg.TriggerType,
		arg.Payload,
		arg.DedupeKey,
		arg.HouseholdID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, user_id, name, url, active, triggers, created_at, updated_at
FROM webhooks
WHERE id = $1 AND household_id = $2
`

type GetWebhookParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetWebhookRow struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Name      string       `json:"name"`
	Url       string       `json:"url"`
	Active    bool         `json:"active"`
	Triggers  []string     `json:"triggers"`
	CreatedAt stdtime.Time `json:"created_at"`
	UpdatedAt stdtime.Time `json:"updated_at"`
}

// household_id is in the predicate, so a caller cannot read another household's
// subscription even with a valid id. Used as the guard before every messages or
// attempts read.
func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (GetWebhookRow, error) {
	row := q.db.QueryRow(ctx, getWebhook, arg.ID, arg.HouseholdID)
	var i GetWebhookRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.Active,
		&i.Triggers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookMessageForDelivery = `-- name: GetWebhookMessageForDelivery :one

SELECT
    m.id, m.webhook_id, m.trigger_type, m.payload, m.status, m.attempts,
    m.dedupe_key, m.created_at,
    w.household_id, w.url, w.secret_encrypted, w.active
FROM webhook_messages m
JOIN webhooks w ON w.id = m.webhook_id
WHERE m.id = $1
`

type GetWebhookMessageForDeliveryRow struct {
	ID              uuid.UUID    `json:"id"`
	WebhookID       uuid.UUID    `json:"webhook_id"`
	TriggerType     string       `json:"trigger_type"`
	Payload         []byte       `json:"payload"`
	Status          string       `json:"status"`
	Attempts        int32        `json:"attempts"`
	DedupeKey       string       `json:"dedupe_key"`
	CreatedAt       stdtime.Time `json:"created_at"`
	HouseholdID     uuid.UUID    `json:"household_id"`
	Url             string       `json:"url"`
	SecretEncrypted []byte       `json:"secret_encrypted"`
	Active          bool         `json:"active"`
}

// --------------------------------------------------------------------------
// Delivering
// --------------------------------------------------------------------------
// Everything one delivery needs, in one round trip: the body to send and sign,
// and the subscription's current url, secret and enabled state.
//
// url/active/secret are read HERE rather than baked into the job args, so a
// webhook edited between enqueue and delivery is honoured — a user who fixed a
// typo in the URL should not have to wait out the backlog queued against the
// old one. The payload is the opposite: it was frozen at enqueue time and is
// never rebuilt.
func (q *Queries) GetWebhookMessageForDelivery(ctx context.Context, id uuid.UUID) (GetWebhookMessageForDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getWebhookMessageForDelivery, id)
	var i GetWebhookMessageForDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.TriggerType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.DedupeKey,
		&i.CreatedAt,
		&i.HouseholdID,
		&i.Url,
		&i.SecretEncrypted,
		&i.Active,
	)
	return i, err
}

const listPendingWebhookMessages = `-- name: ListPendingWebhookMessages :many
SELECT id FROM webhook_messages
WHERE status = 'pending' AND created_at < $1
ORDER BY created_at
LIMIT $2
`

type ListPendingWebhookMessagesParams struct {
	CreatedAt stdtime.Time `json:"created_at"`
	Limit     int32        `json:"limit"`
}

// The sweep's backlog: messages still owed a delivery whose job is not obviously
// in flight. Bounded, oldest first, and served by the partial index — on a
// healthy instance this returns nothing at all.
//
// The age cutoff is what keeps the sweep from racing the queue: a message
// enqueued a second ago already has a job, and re-enqueuing it would only be
// collapsed by the job's uniqueness anyway.
func (q *Queries) ListPendingWebhookMessages(ctx context.Context, arg ListPendingWebhookMessagesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPendingWebhookMessages, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookAttempts = `-- name: ListWebhookAttempts :many
SELECT a.id, a.message_id, a.attempt, a.request_headers, a.request_body,
       a.response_status, a.response_headers, a.response_body, a.error,
       a.duration_ms, a.created_at
FROM webhook_attempts a
JOIN webhook_messages m ON m.id = a.message_id
WHERE a.message_id = $1 AND m.webhook_id = $2
ORDER BY a.attempt
`

type ListWebhookAttemptsParams struct {
	MessageID uuid.UUID `json:"message_id"`
	WebhookID uuid.UUID `json:"webhook_id"`
}

// Attempts for one message, oldest first — the order they happened, which is
// the order somebody debugging wants to read them in. webhook_id is in the
// predicate so a message id from another subscription cannot be read through a
// webhook the caller does own.
func (q *Queries) ListWebhookAttempts(ctx context.Context, arg ListWebhookAttemptsParams) ([]WebhookAttempt, error) {
	rows, err := q.db.Query(ctx, listWebhookAttempts, arg.MessageID, arg.WebhookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookAttempt{}
	for rows.Next() {
		var i WebhookAttempt
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Attempt,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.ResponseStatus,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookMessages = `-- name: ListWebhookMessages :many

SELECT id, webhook_id, trigger_type, payload, status, attempts,
       delivered_at, last_error, created_at
FROM webhook_messages
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListWebhookMessagesParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Limit     int32     `json:"limit"`
}

type ListWebhookMessagesRow struct {
	ID          uuid.UUID     `json:"id"`
	WebhookID   uuid.UUID     `json:"webhook_id"`
	TriggerType string        `json:"trigger_type"`
	Payload     []byte        `json:"payload"`
	Status      string        `json:"status"`
	Attempts    int32         `json:"attempts"`
	DeliveredAt *stdtime.Time `json:"delivered_at"`
	LastError   *string       `json:"last_error"`
	CreatedAt   stdtime.Time  `json:"created_at"`
}

// --------------------------------------------------------------------------
// Inspecting
// --------------------------------------------------------------------------
// The message list for one subscription. The handler has already proved the
// webhook belongs to the caller's household via GetWebhook; the predicate here
// is by webhook alone.
func (q *Queries) ListWebhookMessages(ctx context.Context, arg ListWebhookMessagesParams) ([]ListWebhookMessagesRow, error) {
	rows, err := q.db.Query(ctx, listWebhookMessages, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookMessagesRow{}
	for rows.Next() {
		var i ListWebhookMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.TriggerType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.DeliveredAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many


SELECT id, user_id, name, url, active, triggers, created_at, updated_at
FROM webhooks
WHERE household_id = $1
ORDER BY created_at DESC
`

type ListWebhooksRow struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Name      string       `json:"name"`
	Url       string       `json:"url"`
	Active    bool         `json:"active"`
	Triggers  []string     `json:"triggers"`
	CreatedAt stdtime.Time `json:"created_at"`
	UpdatedAt stdtime.Time `json:"updated_at"`
}

// Outgoing webhooks: subscriptions, the messages they are owed, and the
// delivery attempts made for each.
//
// Two things in here are load-bearing and should be read before editing:
//
//   - The enqueue statements are INSERT ... SELECT over `webhooks`. That is not
//     a style choice. Scoping lives in the SELECT's WHERE, so a message can
//     only ever be created for a subscriber in the household the event belongs
//     to — there is no application-side loop that could forget the predicate.
//   - EnqueueAlertEventWebhookMessages carries the household visibility rule on
//     top of that: an alert raised by a charge on a PRIVATE account reaches only
//     a webhook whose owner may see that transaction. It is the same
//     `(v.user_id = ... OR v.is_shared)` shape ListAlertEvents uses.
//
// Every enqueue is ON CONFLICT DO NOTHING against (webhook_id, dedupe_key), so
// the periodic sweeps that re-examine the same events are free to run as often
// as they like without duplicating deliveries.
// --------------------------------------------------------------------------
// Subscriptions
// --------------------------------------------------------------------------
// The settings list. secret_encrypted is deliberately absent: nothing above the
// delivery worker has any use for it, and a sealed credential has no business
// being carried through a handler.
func (q *Queries) ListWebhooks(ctx context.Context, householdID uuid.UUID) ([]ListWebhooksRow, error) {
	rows, err := q.db.Query(ctx, listWebhooks, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhooksRow{}
	for rows.Next() {
		var i ListWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.Active,
			&i.Triggers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookMessageFailed = `-- name: MarkWebhookMessageFailed :exec
UPDATE webhook_messages
SET status = 'failed', last_error = $2
WHERE id = $1
`

type MarkWebhookMessageFailedParams struct {
	ID        uuid.UUID `json:"id"`
	LastError *string   `json:"last_error"`
}

// The dead letter. The row stays forever (until retention collects it) and
// keeps every attempt behind it, because "it silently stopped working three
// weeks ago" is the failure mode this whole table exists to make visible.
func (q *Queries) MarkWebhookMessageFailed(ctx context.Context, arg MarkWebhookMessageFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookMessageFailed, arg.ID, arg.LastError)
	return err
}

const markWebhookMessageSent = `-- name: MarkWebhookMessageSent :exec
UPDATE webhook_messages
SET status = 'sent', delivered_at = now(), last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkWebhookMessageSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookMessageSent, id)
	return err
}

const recordWebhookAttempt = `-- name: RecordWebhookAttempt :one
INSERT INTO webhook_attempts (
    message_id, attempt, request_headers, request_body,
    response_status, response_headers, response_body, error, duration_ms
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, message_id, attempt, request_headers, request_body,
          response_status, response_headers, response_body, error,
          duration_ms, created_at
`

type RecordWebhookAttemptParams struct {
	MessageID       uuid.UUID `json:"message_id"`
	Attempt         int32     `json:"attempt"`
	RequestHeaders  []byte    `json:"request_headers"`
	RequestBody     string    `json:"request_body"`
	ResponseStatus  *int32    `json:"response_status"`
	ResponseHeaders []byte    `json:"response_headers"`
	ResponseBody    *string   `json:"response_body"`
	Error           *string   `json:"error"`
	DurationMs      int32     `json:"duration_ms"`
}

// The delivery record. Bodies are truncated by the caller before they get here
// — a receiver that answers with a 40 KB HTML error page should cost a few
// hundred bytes of history, not forty kilobytes per retry.
func (q *Queries) RecordWebhookAttempt(ctx context.Context, arg RecordWebhookAttemptParams) (WebhookAttempt, error) {
	row := q.db.QueryRow(ctx, recordWebhookAttempt,
		arg.MessageID,
		arg.Attempt,
		arg.RequestHeaders,
		arg.RequestBody,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.Error,
		arg.DurationMs,
	)
	var i WebhookAttempt
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Attempt,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.Error,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const rotateWebhookSecret = `-- name: RotateWebhookSecret :execrows
UPDATE webhooks
SET secret_encrypted = $3, updated_at = now()
WHERE id = $1 AND household_id = $2
`

type RotateWebhookSecretParams struct {
	ID              uuid.UUID `json:"id"`
	HouseholdID     uuid.UUID `json:"household_id"`
	SecretEncrypted []byte    `json:"secret_encrypted"`
}

func (q *Queries) RotateWebhookSecret(ctx context.Context, arg RotateWebhookSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateWebhookSecret, arg.ID, arg.HouseholdID, arg.SecretEncrypted)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET name = $3, url = $4, active = $5, triggers = $6, updated_at = now()
WHERE id = $1 AND household_id = $2
RETURNING id, user_id, name, url, active, triggers, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
	Name        string    `json:"name"`
	Url         string    `json:"url"`
	Active      bool      `json:"active"`
	Triggers    []string  `json:"triggers"`
}

type UpdateWebhookRow struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Name      string       `json:"name"`
	Url       string       `json:"url"`
	Active    bool         `json:"active"`
	Triggers  []string     `json:"triggers"`
	CreatedAt stdtime.Time `json:"created_at"`
	UpdatedAt stdtime.Time `json:"updated_at"`
}

// The secret is not editable here. Rotating it is a separate, deliberate act
// (RotateWebhookSecret) because it breaks every receiver at once, and burying
// that inside "I renamed my webhook" would be a trap.
func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (UpdateWebhookRow, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Url,
		arg.Active,
		arg.Triggers,
	)
	var i UpdateWebhookRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.Active,
		&i.Triggers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
